USE [CENTRA_ID]
GO

CREATE TABLE
    SCH_CENTRA_ID_AUDIT.LOG_EXCEPTIONS
    (
        ID BIGINT NOT NULL IDENTITY,
        GUID NVARCHAR(50)  NOT NULL,
        CREATED_DATE DATETIME NOT NULL,
        APP_CALLED NVARCHAR(50)  NOT NULL,
        ACTION_CALLED NVARCHAR(500)  NOT NULL,
        JSON_INPUT TEXT  NOT NULL,
        EXCEPTION TEXT  NOT NULL,
        CONSTRAINT LOG_EXCEPTIONS_PK PRIMARY KEY (ID)
    )
GO

CREATE TABLE
    SCH_CENTRA_ID_AUDIT.LOG_PERFORMANCE
    (
        ID BIGINT NOT NULL IDENTITY,
        GUID NVARCHAR(50)  NOT NULL,
        REQUEST_DATE DATETIME NOT NULL,
        RESPONSE_DATE DATETIME,
        APP_CALLED NVARCHAR(500)  NOT NULL,
        ACTION_CALLED NVARCHAR(500)  NOT NULL,
        CONSTRAINT LOG_PERFORMANCE_PK PRIMARY KEY (ID)
    )
GO

CREATE TABLE
    SCH_CENTRA_ID_AUDIT.LOG_TRANSACTIONAL
    (
        ID BIGINT NOT NULL IDENTITY,
        GUID NVARCHAR(50)  NOT NULL,
        TYPE NVARCHAR(1)  NOT NULL,
        APP_CALLED NVARCHAR(50)  NOT NULL,
        ACTION_CALLED NVARCHAR(500)  NOT NULL,
        DATE_CALLED DATETIME,
        JSON_INPUT TEXT  NOT NULL,
        JSON_RESPONSE TEXT  NOT NULL,
        USERNAME NVARCHAR(50)  NOT NULL,
        STATUS NVARCHAR(50) ,
        CONSTRAINT LOG_TRANSACTIONAL_PK PRIMARY KEY (ID)
    )
GO


