USE [CENTRA_ID]
GO

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

INSERT INTO SCH_CENTRA_ID.GLOBAL_PARAMETERS (CODE, NAME, DESCRIPTION, TYPE, VALUE_TEXT, VALUE_NUMBER, VALUE_DATE, VALUE_BOOLEAN, VALID) 
VALUES ('PROCREUSUINT', 'ID PROCESO CREAR USUARIO INTERNO', 'ID PROCESO CREAR USUARIO INTERNO', 'S', 'createInternalUserId:1:5220', NULL, NULL, NULL, 1)
GO

INSERT INTO SCH_CENTRA_ID.GLOBAL_PARAMETERS (CODE, NAME, DESCRIPTION, TYPE, VALUE_TEXT, VALUE_NUMBER, VALUE_DATE, VALUE_BOOLEAN, VALID) 
VALUES ('PROCREUSUEXT', 'ID PROCESO CREAR USUARIO EXTERNO', 'ID PROCESO CREAR USUARIO EXTERNO', 'S', 'createExternalUserId:1:5223', NULL, NULL, NULL, 1)
GO

INSERT INTO SCH_CENTRA_ID.GLOBAL_PARAMETERS (CODE, NAME, DESCRIPTION, TYPE, VALUE_TEXT, VALUE_NUMBER, VALUE_DATE, VALUE_BOOLEAN, VALID) 
VALUES ('PROCREUSUGEN', 'ID PROCESO CREAR USUARIO GENÉRICO', 'ID PROCESO CREAR USUARIO GENÉRICO', 'S', 'createGenericUserId:1:5221', NULL, NULL, NULL, 1)
GO

INSERT INTO SCH_CENTRA_ID.GLOBAL_PARAMETERS (CODE, NAME, DESCRIPTION, TYPE, VALUE_TEXT, VALUE_NUMBER, VALUE_DATE, VALUE_BOOLEAN, VALID) 
VALUES ('PROCREUSUGENROT', 'ID PROCESO CREAR USUARIO GENÉRICO ROTATIVO', 'ID PROCESO CREAR USUARIO GENÉRICO ROTATIVO', 'S', 'createGenericRotaryUserId:1:5222', NULL, NULL, NULL, 1)
GO


