--USE [CENTRA_ID]
--GO

SELECT 'ANTES' AS 'RFC_ C00018923',* FROM [SCH_CENTRA_ID].[TEMPLATE_PROFILES]
GO
DELETE FROM sch_centra_id.TEMPLATE_PROFILES  
GO
SELECT 'DESPUES' AS 'RFC_ C00018923',* FROM [SCH_CENTRA_ID].[TEMPLATE_PROFILES]
 
SELECT 'ANTES' AS 'RFC_ C00018923',* FROM [SCH_CENTRA_ID].[TEMPLATE_PROFILES_MATRICES_DETAIL]
GO
DELETE FROM sch_centra_id.TEMPLATE_PROFILES_MATRICES_DETAIL  
GO
SELECT 'DESPUES' AS 'RFC_ C00018923',* FROM [SCH_CENTRA_ID].[TEMPLATE_PROFILES_MATRICES_DETAIL]
GO

SELECT 'ANTES' AS 'RFC_ C00018923',* FROM [SCH_CENTRA_ID].[TEMPLATE_PROFILES_MATRICES_GROUP]
GO
DELETE FROM sch_centra_id.TEMPLATE_PROFILES_MATRICES_GROUP  
GO 
SELECT 'DESPUES' AS 'RFC_ C00018923',* FROM [SCH_CENTRA_ID].[TEMPLATE_PROFILES_MATRICES_GROUP]
GO

SELECT 'ANTES' AS 'RFC_ C00018923',* FROM [SCH_CENTRA_ID].[TEMPLATE_PROFILES_MATRICES]
GO
DELETE FROM sch_centra_id.TEMPLATE_PROFILES_MATRICES  
GO 
SELECT 'DESPUES' AS 'RFC_ C00018923',* FROM [SCH_CENTRA_ID].[TEMPLATE_PROFILES_MATRICES]
GO

SELECT 'ANTES' AS 'RFC_ C00018923',* FROM [SCH_CENTRA_ID].[GLOBAL_TRANSACTIONAL_PROFILES]
GO
DELETE FROM sch_centra_id.GLOBAL_TRANSACTIONAL_PROFILES  
GO 
SELECT 'DESPUES' AS 'RFC_ C00018923',* FROM [SCH_CENTRA_ID].[GLOBAL_TRANSACTIONAL_PROFILES]
GO


SELECT 'ANTES' AS 'RFC_ C00018923',* FROM [SCH_CENTRA_ID].[TRANSACTIONAL_PROFILES]
GO
DELETE FROM sch_centra_id.TRANSACTIONAL_PROFILES  
GO 
SELECT 'DESPUES' AS 'RFC_ C00018923',* FROM [SCH_CENTRA_ID].[TRANSACTIONAL_PROFILES]
GO

SELECT 'ANTES' AS 'RFC_ C00018923',* FROM [SCH_CENTRA_ID].[APPLICATIONS]
GO
DELETE FROM sch_centra_id.APPLICATIONS  
GO 
SELECT 'DESPUES' AS 'RFC_ C00018923',* FROM [SCH_CENTRA_ID].[APPLICATIONS]
GO

SELECT 'ANTES' AS 'RFC_ C00018923',* FROM [SCH_CENTRA_ID].[FIELDS]
GO
DELETE FROM sch_centra_id.FIELDS  
GO 
SELECT 'DESPUES' AS 'RFC_ C00018923',* FROM [SCH_CENTRA_ID].[FIELDS]
GO

SELECT 'ANTES' AS 'RFC_ C00018923',* FROM [SCH_CENTRA_ID].[MATRICES_DETAIL]
GO
DELETE FROM sch_centra_id.MATRICES_DETAIL  
GO 
SELECT 'DESPUES' AS 'RFC_ C00018923',* FROM [SCH_CENTRA_ID].[MATRICES_DETAIL]
GO

SELECT 'ANTES' AS 'RFC_ C00018923',* FROM [SCH_CENTRA_ID].[MATRICES]
GO
DELETE FROM sch_centra_id.MATRICES  
GO 
SELECT 'DESPUES' AS 'RFC_ C00018923',* FROM [SCH_CENTRA_ID].[MATRICES]
GO


SELECT 'ANTES' AS 'RFC_ C00018923',* FROM [SCH_CENTRA_ID].[APPLICATIONS_GROUP]
GO
DELETE FROM sch_centra_id.APPLICATIONS_GROUP  
GO 
 
INSERT INTO sch_centra_id.APPLICATIONS_GROUP (CODE, NAME, ENDPOINT_TYPE,ORDINAL,VALID,NUMBER_RETRIES,TIME_BETWEEN_RETRIES,ERRORS_NOT_REQUIRE_TICKET) VALUES ('BANCS','BANCS','API',1,1,0,0,0)
GO
INSERT INTO sch_centra_id.APPLICATIONS_GROUP (CODE, NAME, ENDPOINT_TYPE,ORDINAL,VALID,NUMBER_RETRIES,TIME_BETWEEN_RETRIES,ERRORS_NOT_REQUIRE_TICKET) VALUES ('PPRD','PPRD','API',2,1,0,0,0)
GO
INSERT INTO sch_centra_id.APPLICATIONS_GROUP (CODE, NAME, ENDPOINT_TYPE,ORDINAL,VALID,NUMBER_RETRIES,TIME_BETWEEN_RETRIES,ERRORS_NOT_REQUIRE_TICKET) VALUES ('LOGICIEL','LOGICIEL','API',2,1,0,0,0)
GO
INSERT INTO sch_centra_id.APPLICATIONS_GROUP (CODE, NAME, ENDPOINT_TYPE,ORDINAL,VALID,NUMBER_RETRIES,TIME_BETWEEN_RETRIES,ERRORS_NOT_REQUIRE_TICKET) VALUES ('RHDS','RHDS','API',2,1,0,0,0)
GO
INSERT INTO sch_centra_id.APPLICATIONS_GROUP (CODE, NAME, ENDPOINT_TYPE,ORDINAL,VALID,NUMBER_RETRIES,TIME_BETWEEN_RETRIES,ERRORS_NOT_REQUIRE_TICKET) VALUES ('AD','AD','DIRECT',1,1,0,0,0)
GO
INSERT INTO sch_centra_id.APPLICATIONS_GROUP (CODE, NAME, ENDPOINT_TYPE,ORDINAL,VALID,NUMBER_RETRIES,TIME_BETWEEN_RETRIES,ERRORS_NOT_REQUIRE_TICKET) VALUES ('CAPITAL','CAPITAL','TICKET',2,1,0,0,0)
GO
INSERT INTO sch_centra_id.APPLICATIONS_GROUP (CODE, NAME, ENDPOINT_TYPE,ORDINAL,VALID,NUMBER_RETRIES,TIME_BETWEEN_RETRIES,ERRORS_NOT_REQUIRE_TICKET) VALUES ('EASYPAGOS','EASYPAGOS','TICKET',2,1,0,0,0)
GO
INSERT INTO sch_centra_id.APPLICATIONS_GROUP (CODE, NAME, ENDPOINT_TYPE,ORDINAL,VALID,NUMBER_RETRIES,TIME_BETWEEN_RETRIES,ERRORS_NOT_REQUIRE_TICKET) VALUES ('EBS','EBS','TICKET',2,1,0,0,0)
GO
INSERT INTO sch_centra_id.APPLICATIONS_GROUP (CODE, NAME, ENDPOINT_TYPE,ORDINAL,VALID,NUMBER_RETRIES,TIME_BETWEEN_RETRIES,ERRORS_NOT_REQUIRE_TICKET) VALUES ('LYNC','LYNC','TICKET',2,1,0,0,0)
GO
INSERT INTO sch_centra_id.APPLICATIONS_GROUP (CODE, NAME, ENDPOINT_TYPE,ORDINAL,VALID,NUMBER_RETRIES,TIME_BETWEEN_RETRIES,ERRORS_NOT_REQUIRE_TICKET) VALUES ('TALLA','TALLA','TICKET',2,1,0,0,0)
GO
INSERT INTO sch_centra_id.APPLICATIONS_GROUP (CODE, NAME, ENDPOINT_TYPE,ORDINAL,VALID,NUMBER_RETRIES,TIME_BETWEEN_RETRIES,ERRORS_NOT_REQUIRE_TICKET) VALUES ('HP_SERVICE_MANAGER','HP SERVICE MANAGER','TICKET',2,1,0,0,0)
GO
INSERT INTO sch_centra_id.APPLICATIONS_GROUP (CODE, NAME, ENDPOINT_TYPE,ORDINAL,VALID,NUMBER_RETRIES,TIME_BETWEEN_RETRIES,ERRORS_NOT_REQUIRE_TICKET) VALUES ('SES','SES','TICKET',2,1,0,0,0)
GO
INSERT INTO sch_centra_id.APPLICATIONS_GROUP (CODE, NAME, ENDPOINT_TYPE,ORDINAL,VALID,NUMBER_RETRIES,TIME_BETWEEN_RETRIES,ERRORS_NOT_REQUIRE_TICKET) VALUES ('HUMMINGBIRD','HUMMINGBIRD','TICKET',2,1,0,0,0)
GO
INSERT INTO sch_centra_id.APPLICATIONS_GROUP (CODE, NAME, ENDPOINT_TYPE,ORDINAL,VALID,NUMBER_RETRIES,TIME_BETWEEN_RETRIES,ERRORS_NOT_REQUIRE_TICKET) VALUES ('PORTAL_AZURE','PORTAL AZURE','TICKET',2,1,0,0,0)
GO
INSERT INTO sch_centra_id.APPLICATIONS_GROUP (CODE, NAME, ENDPOINT_TYPE,ORDINAL,VALID,NUMBER_RETRIES,TIME_BETWEEN_RETRIES,ERRORS_NOT_REQUIRE_TICKET) VALUES ('CONSOLA_SYMANTEC','CONSOLA SYMANTEC','TICKET',2,1,0,0,0)
GO
INSERT INTO sch_centra_id.APPLICATIONS_GROUP (CODE, NAME, ENDPOINT_TYPE,ORDINAL,VALID,NUMBER_RETRIES,TIME_BETWEEN_RETRIES,ERRORS_NOT_REQUIRE_TICKET) VALUES ('SAS','SAS','TICKET',2,1,0,0,0)
GO
INSERT INTO sch_centra_id.APPLICATIONS_GROUP (CODE, NAME, ENDPOINT_TYPE,ORDINAL,VALID,NUMBER_RETRIES,TIME_BETWEEN_RETRIES,ERRORS_NOT_REQUIRE_TICKET) VALUES ('RYR','RYR','TICKET',2,1,0,0,0)
GO
INSERT INTO sch_centra_id.APPLICATIONS_GROUP (CODE, NAME, ENDPOINT_TYPE,ORDINAL,VALID,NUMBER_RETRIES,TIME_BETWEEN_RETRIES,ERRORS_NOT_REQUIRE_TICKET) VALUES ('CANJE','CANJE','TICKET',2,1,0,0,0)
GO
INSERT INTO sch_centra_id.APPLICATIONS_GROUP (CODE, NAME, ENDPOINT_TYPE,ORDINAL,VALID,NUMBER_RETRIES,TIME_BETWEEN_RETRIES,ERRORS_NOT_REQUIRE_TICKET) VALUES ('CITRIX','CITRIX','TICKET',2,1,0,0,0)
GO
INSERT INTO sch_centra_id.APPLICATIONS_GROUP (CODE, NAME, ENDPOINT_TYPE,ORDINAL,VALID,NUMBER_RETRIES,TIME_BETWEEN_RETRIES,ERRORS_NOT_REQUIRE_TICKET) VALUES ('GAF','GAF','TICKET',2,1,0,0,0)
GO
INSERT INTO sch_centra_id.APPLICATIONS_GROUP (CODE, NAME, ENDPOINT_TYPE,ORDINAL,VALID,NUMBER_RETRIES,TIME_BETWEEN_RETRIES,ERRORS_NOT_REQUIRE_TICKET) VALUES ('AS400_GAF','AS400 GAF','TICKET',2,1,0,0,0)
GO
INSERT INTO sch_centra_id.APPLICATIONS_GROUP (CODE, NAME, ENDPOINT_TYPE,ORDINAL,VALID,NUMBER_RETRIES,TIME_BETWEEN_RETRIES,ERRORS_NOT_REQUIRE_TICKET) VALUES ('BLOQUEAR_CORREO_EXTERNO','BLOQUEAR CORREO EXTERNO','TICKET',2,1,0,0,0)
GO
INSERT INTO sch_centra_id.APPLICATIONS_GROUP (CODE, NAME, ENDPOINT_TYPE,ORDINAL,VALID,NUMBER_RETRIES,TIME_BETWEEN_RETRIES,ERRORS_NOT_REQUIRE_TICKET) VALUES ('IDENTITY_MINDER','IDENTITY MINDER','TICKET',2,1,0,0,0)
GO
INSERT INTO sch_centra_id.APPLICATIONS_GROUP (CODE, NAME, ENDPOINT_TYPE,ORDINAL,VALID,NUMBER_RETRIES,TIME_BETWEEN_RETRIES,ERRORS_NOT_REQUIRE_TICKET) VALUES ('ARCHIVO_DIGITAL','ARCHIVO DIGITAL','TICKET',2,1,0,0,0)
GO
INSERT INTO sch_centra_id.APPLICATIONS_GROUP (CODE, NAME, ENDPOINT_TYPE,ORDINAL,VALID,NUMBER_RETRIES,TIME_BETWEEN_RETRIES,ERRORS_NOT_REQUIRE_TICKET) VALUES ('BACTRADER','BACTRADER','TICKET',2,1,0,0,0)
GO
INSERT INTO sch_centra_id.APPLICATIONS_GROUP (CODE, NAME, ENDPOINT_TYPE,ORDINAL,VALID,NUMBER_RETRIES,TIME_BETWEEN_RETRIES,ERRORS_NOT_REQUIRE_TICKET) VALUES ('CREDIFE','CREDIFE','TICKET',2,1,0,0,0)
GO
INSERT INTO sch_centra_id.APPLICATIONS_GROUP (CODE, NAME, ENDPOINT_TYPE,ORDINAL,VALID,NUMBER_RETRIES,TIME_BETWEEN_RETRIES,ERRORS_NOT_REQUIRE_TICKET) VALUES ('ICS','ICS','TICKET',2,1,0,0,0)
GO
INSERT INTO sch_centra_id.APPLICATIONS_GROUP (CODE, NAME, ENDPOINT_TYPE,ORDINAL,VALID,NUMBER_RETRIES,TIME_BETWEEN_RETRIES,ERRORS_NOT_REQUIRE_TICKET) VALUES ('SOS','SOS','TICKET',2,1,0,0,0)
GO
INSERT INTO sch_centra_id.APPLICATIONS_GROUP (CODE, NAME, ENDPOINT_TYPE,ORDINAL,VALID,NUMBER_RETRIES,TIME_BETWEEN_RETRIES,ERRORS_NOT_REQUIRE_TICKET) VALUES ('CREDITLENS','CREDITLENS','TICKET',2,1,0,0,0)
GO
INSERT INTO sch_centra_id.APPLICATIONS_GROUP (CODE, NAME, ENDPOINT_TYPE,ORDINAL,VALID,NUMBER_RETRIES,TIME_BETWEEN_RETRIES,ERRORS_NOT_REQUIRE_TICKET) VALUES ('BDD_PLSQL','BDD PLSQL','TICKET',2,1,0,0,0)
GO
INSERT INTO sch_centra_id.APPLICATIONS_GROUP (CODE, NAME, ENDPOINT_TYPE,ORDINAL,VALID,NUMBER_RETRIES,TIME_BETWEEN_RETRIES,ERRORS_NOT_REQUIRE_TICKET) VALUES ('PIVI','PIVI','TICKET',2,1,0,0,0)
GO
INSERT INTO sch_centra_id.APPLICATIONS_GROUP (CODE, NAME, ENDPOINT_TYPE,ORDINAL,VALID,NUMBER_RETRIES,TIME_BETWEEN_RETRIES,ERRORS_NOT_REQUIRE_TICKET) VALUES ('PIVI_WEB','PIVI WEB','TICKET',2,1,0,0,0)
GO
INSERT INTO sch_centra_id.APPLICATIONS_GROUP (CODE, NAME, ENDPOINT_TYPE,ORDINAL,VALID,NUMBER_RETRIES,TIME_BETWEEN_RETRIES,ERRORS_NOT_REQUIRE_TICKET) VALUES ('SENTINEL','SENTINEL','TICKET',2,1,0,0,0)
GO
INSERT INTO sch_centra_id.APPLICATIONS_GROUP (CODE, NAME, ENDPOINT_TYPE,ORDINAL,VALID,NUMBER_RETRIES,TIME_BETWEEN_RETRIES,ERRORS_NOT_REQUIRE_TICKET) VALUES ('COBIS','COBIS','TICKET',2,1,0,0,0)
GO
INSERT INTO sch_centra_id.APPLICATIONS_GROUP (CODE, NAME, ENDPOINT_TYPE,ORDINAL,VALID,NUMBER_RETRIES,TIME_BETWEEN_RETRIES,ERRORS_NOT_REQUIRE_TICKET) VALUES ('SEC','SEC','TICKET',2,1,0,0,0)
GO
INSERT INTO sch_centra_id.APPLICATIONS_GROUP (CODE, NAME, ENDPOINT_TYPE,ORDINAL,VALID,NUMBER_RETRIES,TIME_BETWEEN_RETRIES,ERRORS_NOT_REQUIRE_TICKET) VALUES ('GEORUTA','GEORUTA','TICKET',2,1,0,0,0)
GO
INSERT INTO sch_centra_id.APPLICATIONS_GROUP (CODE, NAME, ENDPOINT_TYPE,ORDINAL,VALID,NUMBER_RETRIES,TIME_BETWEEN_RETRIES,ERRORS_NOT_REQUIRE_TICKET) VALUES ('MISRIESGO','MISRIESGO','TICKET',2,1,0,0,0)
GO
INSERT INTO sch_centra_id.APPLICATIONS_GROUP (CODE, NAME, ENDPOINT_TYPE,ORDINAL,VALID,NUMBER_RETRIES,TIME_BETWEEN_RETRIES,ERRORS_NOT_REQUIRE_TICKET) VALUES ('CRM_BP','CRM BP','TICKET',2,1,0,0,0)
GO
INSERT INTO sch_centra_id.APPLICATIONS_GROUP (CODE, NAME, ENDPOINT_TYPE,ORDINAL,VALID,NUMBER_RETRIES,TIME_BETWEEN_RETRIES,ERRORS_NOT_REQUIRE_TICKET) VALUES ('NETMANAGER','NETMANAGER','TICKET',2,1,0,0,0)
GO
INSERT INTO sch_centra_id.APPLICATIONS_GROUP (CODE, NAME, ENDPOINT_TYPE,ORDINAL,VALID,NUMBER_RETRIES,TIME_BETWEEN_RETRIES,ERRORS_NOT_REQUIRE_TICKET) VALUES ('BANCKTRADE','BANCKTRADE','TICKET',2,1,0,0,0)
GO
INSERT INTO sch_centra_id.APPLICATIONS_GROUP (CODE, NAME, ENDPOINT_TYPE,ORDINAL,VALID,NUMBER_RETRIES,TIME_BETWEEN_RETRIES,ERRORS_NOT_REQUIRE_TICKET) VALUES ('CRM_DINERS','CRM DINERS','TICKET',2,1,0,0,0)
GO
INSERT INTO sch_centra_id.APPLICATIONS_GROUP (CODE, NAME, ENDPOINT_TYPE,ORDINAL,VALID,NUMBER_RETRIES,TIME_BETWEEN_RETRIES,ERRORS_NOT_REQUIRE_TICKET) VALUES ('FASTWORK','FASTWORK','TICKET',2,1,0,0,0)
GO
INSERT INTO sch_centra_id.APPLICATIONS_GROUP (CODE, NAME, ENDPOINT_TYPE,ORDINAL,VALID,NUMBER_RETRIES,TIME_BETWEEN_RETRIES,ERRORS_NOT_REQUIRE_TICKET) VALUES ('TURBOSWIFT','TURBOSWIFT','TICKET',2,1,0,0,0)
GO
INSERT INTO sch_centra_id.APPLICATIONS_GROUP (CODE, NAME, ENDPOINT_TYPE,ORDINAL,VALID,NUMBER_RETRIES,TIME_BETWEEN_RETRIES,ERRORS_NOT_REQUIRE_TICKET) VALUES ('MOODYS','MOODYS','TICKET',2,1,0,0,0)
GO
INSERT INTO sch_centra_id.APPLICATIONS_GROUP (CODE, NAME, ENDPOINT_TYPE,ORDINAL,VALID,NUMBER_RETRIES,TIME_BETWEEN_RETRIES,ERRORS_NOT_REQUIRE_TICKET) VALUES ('VCM','VCM','TICKET',2,1,0,0,0)
GO
INSERT INTO sch_centra_id.APPLICATIONS_GROUP (CODE, NAME, ENDPOINT_TYPE,ORDINAL,VALID,NUMBER_RETRIES,TIME_BETWEEN_RETRIES,ERRORS_NOT_REQUIRE_TICKET) VALUES ('CAO','CAO','TICKET',2,1,0,0,0)
GO
INSERT INTO sch_centra_id.APPLICATIONS_GROUP (CODE, NAME, ENDPOINT_TYPE,ORDINAL,VALID,NUMBER_RETRIES,TIME_BETWEEN_RETRIES,ERRORS_NOT_REQUIRE_TICKET) VALUES ('BIOSERVER','BIOSERVER','TICKET',2,1,0,0,0)
GO
INSERT INTO sch_centra_id.APPLICATIONS_GROUP (CODE, NAME, ENDPOINT_TYPE,ORDINAL,VALID,NUMBER_RETRIES,TIME_BETWEEN_RETRIES,ERRORS_NOT_REQUIRE_TICKET) VALUES ('BRIDGER_INSIGHT','BRIDGER INSIGHT','TICKET',2,1,0,0,0)
GO
INSERT INTO sch_centra_id.APPLICATIONS_GROUP (CODE, NAME, ENDPOINT_TYPE,ORDINAL,VALID,NUMBER_RETRIES,TIME_BETWEEN_RETRIES,ERRORS_NOT_REQUIRE_TICKET) VALUES ('CAPTOVATION','CAPTOVATION','TICKET',2,1,0,0,0)
GO
INSERT INTO sch_centra_id.APPLICATIONS_GROUP (CODE, NAME, ENDPOINT_TYPE,ORDINAL,VALID,NUMBER_RETRIES,TIME_BETWEEN_RETRIES,ERRORS_NOT_REQUIRE_TICKET) VALUES ('BDD_SQL','BDD SQL','TICKET',2,1,0,0,0)
GO
INSERT INTO sch_centra_id.APPLICATIONS_GROUP (CODE, NAME, ENDPOINT_TYPE,ORDINAL,VALID,NUMBER_RETRIES,TIME_BETWEEN_RETRIES,ERRORS_NOT_REQUIRE_TICKET) VALUES ('HYPERION','HYPERION','TICKET',2,1,0,0,0)
GO
INSERT INTO sch_centra_id.APPLICATIONS_GROUP (CODE, NAME, ENDPOINT_TYPE,ORDINAL,VALID,NUMBER_RETRIES,TIME_BETWEEN_RETRIES,ERRORS_NOT_REQUIRE_TICKET) VALUES ('BDD_POSTGRES','BDD POSTGRES','TICKET',2,1,0,0,0)
GO
INSERT INTO sch_centra_id.APPLICATIONS_GROUP (CODE, NAME, ENDPOINT_TYPE,ORDINAL,VALID,NUMBER_RETRIES,TIME_BETWEEN_RETRIES,ERRORS_NOT_REQUIRE_TICKET) VALUES ('MUREX','MUREX','TICKET',2,1,0,0,0)
GO
INSERT INTO sch_centra_id.APPLICATIONS_GROUP (CODE, NAME, ENDPOINT_TYPE,ORDINAL,VALID,NUMBER_RETRIES,TIME_BETWEEN_RETRIES,ERRORS_NOT_REQUIRE_TICKET) VALUES ('SO_UNIX','SO UNIX','TICKET',2,1,0,0,0)
GO
INSERT INTO sch_centra_id.APPLICATIONS_GROUP (CODE, NAME, ENDPOINT_TYPE,ORDINAL,VALID,NUMBER_RETRIES,TIME_BETWEEN_RETRIES,ERRORS_NOT_REQUIRE_TICKET) VALUES ('SO_UNIX_STORAGE','SO UNIX STORAGE','TICKET',2,1,0,0,0)
GO
INSERT INTO sch_centra_id.APPLICATIONS_GROUP (CODE, NAME, ENDPOINT_TYPE,ORDINAL,VALID,NUMBER_RETRIES,TIME_BETWEEN_RETRIES,ERRORS_NOT_REQUIRE_TICKET) VALUES ('TOTEM','TOTEM','TICKET',2,1,0,0,0)
GO
INSERT INTO sch_centra_id.APPLICATIONS_GROUP (CODE, NAME, ENDPOINT_TYPE,ORDINAL,VALID,NUMBER_RETRIES,TIME_BETWEEN_RETRIES,ERRORS_NOT_REQUIRE_TICKET) VALUES ('CONTACTOS_EXCHANGE','CONTACTOS EXCHANGE','TICKET',2,1,0,0,0)
GO
INSERT INTO sch_centra_id.APPLICATIONS_GROUP (CODE, NAME, ENDPOINT_TYPE,ORDINAL,VALID,NUMBER_RETRIES,TIME_BETWEEN_RETRIES,ERRORS_NOT_REQUIRE_TICKET) VALUES ('TRANSACCION_MOTIVO_BANCS','TRANSACCION MOTIVO BANCS','TICKET',2,1,0,0,0)
GO
INSERT INTO sch_centra_id.APPLICATIONS_GROUP (CODE, NAME, ENDPOINT_TYPE,ORDINAL,VALID,NUMBER_RETRIES,TIME_BETWEEN_RETRIES,ERRORS_NOT_REQUIRE_TICKET) VALUES ('GEENERA','GEENERA','TICKET',2,1,0,0,0)
GO
INSERT INTO sch_centra_id.APPLICATIONS_GROUP (CODE, NAME, ENDPOINT_TYPE,ORDINAL,VALID,NUMBER_RETRIES,TIME_BETWEEN_RETRIES,ERRORS_NOT_REQUIRE_TICKET) VALUES ('APPL _INTERNA_LIBRARIAN','APPL  INTERNA LIBRARIAN','TICKET',2,1,0,0,0)
GO
INSERT INTO sch_centra_id.APPLICATIONS_GROUP (CODE, NAME, ENDPOINT_TYPE,ORDINAL,VALID,NUMBER_RETRIES,TIME_BETWEEN_RETRIES,ERRORS_NOT_REQUIRE_TICKET) VALUES ('SERVIDORES_ADMI','SERVIDORES ADMI','TICKET',2,1,0,0,0)
GO
INSERT INTO sch_centra_id.APPLICATIONS_GROUP (CODE, NAME, ENDPOINT_TYPE,ORDINAL,VALID,NUMBER_RETRIES,TIME_BETWEEN_RETRIES,ERRORS_NOT_REQUIRE_TICKET) VALUES ('SERVIDORES_LIBRARIAN','SERVIDORES LIBRARIAN','TICKET',2,1,0,0,0)
GO
INSERT INTO sch_centra_id.APPLICATIONS_GROUP (CODE, NAME, ENDPOINT_TYPE,ORDINAL,VALID,NUMBER_RETRIES,TIME_BETWEEN_RETRIES,ERRORS_NOT_REQUIRE_TICKET) VALUES ('SERVIDORES_MANT_APPL','SERVIDORES MANT APPL','TICKET',2,1,0,0,0)
GO
INSERT INTO sch_centra_id.APPLICATIONS_GROUP (CODE, NAME, ENDPOINT_TYPE,ORDINAL,VALID,NUMBER_RETRIES,TIME_BETWEEN_RETRIES,ERRORS_NOT_REQUIRE_TICKET) VALUES ('SERVIDORES_RED_TEAM','SERVIDORES RED TEAM','TICKET',2,1,0,0,0)
GO
INSERT INTO sch_centra_id.APPLICATIONS_GROUP (CODE, NAME, ENDPOINT_TYPE,ORDINAL,VALID,NUMBER_RETRIES,TIME_BETWEEN_RETRIES,ERRORS_NOT_REQUIRE_TICKET) VALUES ('FTP_EXTERNO','FTP EXTERNO','TICKET',2,1,0,0,0)
GO
INSERT INTO sch_centra_id.APPLICATIONS_GROUP (CODE, NAME, ENDPOINT_TYPE,ORDINAL,VALID,NUMBER_RETRIES,TIME_BETWEEN_RETRIES,ERRORS_NOT_REQUIRE_TICKET) VALUES ('TOKEN_BCE','TOKEN BCE','TICKET',2,1,0,0,0)
GO
INSERT INTO sch_centra_id.APPLICATIONS_GROUP (CODE, NAME, ENDPOINT_TYPE,ORDINAL,VALID,NUMBER_RETRIES,TIME_BETWEEN_RETRIES,ERRORS_NOT_REQUIRE_TICKET) VALUES ('ANF','ANF','TICKET',2,1,0,0,0)
GO
INSERT INTO sch_centra_id.APPLICATIONS_GROUP (CODE, NAME, ENDPOINT_TYPE,ORDINAL,VALID,NUMBER_RETRIES,TIME_BETWEEN_RETRIES,ERRORS_NOT_REQUIRE_TICKET) VALUES ('CLEARSTREAM','CLEARSTREAM','TICKET',2,1,0,0,0)
GO
INSERT INTO sch_centra_id.APPLICATIONS_GROUP (CODE, NAME, ENDPOINT_TYPE,ORDINAL,VALID,NUMBER_RETRIES,TIME_BETWEEN_RETRIES,ERRORS_NOT_REQUIRE_TICKET) VALUES ('VERTICES','VERTICES','TICKET',2,1,0,0,0)
GO
INSERT INTO sch_centra_id.APPLICATIONS_GROUP (CODE, NAME, ENDPOINT_TYPE,ORDINAL,VALID,NUMBER_RETRIES,TIME_BETWEEN_RETRIES,ERRORS_NOT_REQUIRE_TICKET) VALUES ('SYSTEM_CENTER','SYSTEM CENTER','TICKET',2,1,0,0,0)
GO
INSERT INTO sch_centra_id.APPLICATIONS_GROUP (CODE, NAME, ENDPOINT_TYPE,ORDINAL,VALID,NUMBER_RETRIES,TIME_BETWEEN_RETRIES,ERRORS_NOT_REQUIRE_TICKET) VALUES ('RCSA','RCSA','TICKET',2,1,0,0,0)
GO
INSERT INTO sch_centra_id.APPLICATIONS_GROUP (CODE, NAME, ENDPOINT_TYPE,ORDINAL,VALID,NUMBER_RETRIES,TIME_BETWEEN_RETRIES,ERRORS_NOT_REQUIRE_TICKET) VALUES ('OTROS','OTROS','TICKET',2,1,0,0,0)
GO
INSERT INTO sch_centra_id.APPLICATIONS_GROUP (CODE, NAME, ENDPOINT_TYPE,ORDINAL,VALID,NUMBER_RETRIES,TIME_BETWEEN_RETRIES,ERRORS_NOT_REQUIRE_TICKET) VALUES ('CAPITAL_CREDIFE','CAPITAL CREDIFE','TICKET',2,1,0,0,0)
GO
INSERT INTO sch_centra_id.APPLICATIONS_GROUP (CODE, NAME, ENDPOINT_TYPE,ORDINAL,VALID,NUMBER_RETRIES,TIME_BETWEEN_RETRIES,ERRORS_NOT_REQUIRE_TICKET) VALUES ('GAF_PANAMA','GAF PANAMA','TICKET',2,1,0,0,0)
GO
INSERT INTO sch_centra_id.APPLICATIONS_GROUP (CODE, NAME, ENDPOINT_TYPE,ORDINAL,VALID,NUMBER_RETRIES,TIME_BETWEEN_RETRIES,ERRORS_NOT_REQUIRE_TICKET) VALUES ('RIESGO_DETALLADO','RIESGO DETALLADO','TICKET',2,1,0,0,0)
GO
INSERT INTO sch_centra_id.APPLICATIONS_GROUP (CODE, NAME, ENDPOINT_TYPE,ORDINAL,VALID,NUMBER_RETRIES,TIME_BETWEEN_RETRIES,ERRORS_NOT_REQUIRE_TICKET) VALUES ('REPORTING_SERVICES','REPORTING SERVICES','TICKET',2,1,0,0,0)
GO
INSERT INTO sch_centra_id.APPLICATIONS_GROUP (CODE, NAME, ENDPOINT_TYPE,ORDINAL,VALID,NUMBER_RETRIES,TIME_BETWEEN_RETRIES,ERRORS_NOT_REQUIRE_TICKET) VALUES ('OPENBANK','OPENBANK','TICKET',2,1,0,0,0)
GO
INSERT INTO sch_centra_id.APPLICATIONS_GROUP (CODE, NAME, ENDPOINT_TYPE,ORDINAL,VALID,NUMBER_RETRIES,TIME_BETWEEN_RETRIES,ERRORS_NOT_REQUIRE_TICKET) VALUES ('TURBO_SWIFT','TURBO SWIFT','TICKET',2,1,0,0,0)
GO
INSERT INTO sch_centra_id.APPLICATIONS_GROUP (CODE, NAME, ENDPOINT_TYPE,ORDINAL,VALID,NUMBER_RETRIES,TIME_BETWEEN_RETRIES,ERRORS_NOT_REQUIRE_TICKET) VALUES ('BANKTRADE','BANKTRADE','TICKET',2,1,0,0,0)
GO
INSERT INTO sch_centra_id.APPLICATIONS_GROUP (CODE, NAME, ENDPOINT_TYPE,ORDINAL,VALID,NUMBER_RETRIES,TIME_BETWEEN_RETRIES,ERRORS_NOT_REQUIRE_TICKET) VALUES ('ADAM','ADAM','TICKET',2,1,0,0,0)
GO
INSERT INTO sch_centra_id.APPLICATIONS_GROUP (CODE, NAME, ENDPOINT_TYPE,ORDINAL,VALID,NUMBER_RETRIES,TIME_BETWEEN_RETRIES,ERRORS_NOT_REQUIRE_TICKET) VALUES ('GRUPO_PORTAL_ADICIONAL','GRUPO PORTAL ADICIONAL','TICKET',2,1,0,0,0)
GO
INSERT INTO sch_centra_id.APPLICATIONS_GROUP (CODE, NAME, ENDPOINT_TYPE,ORDINAL,VALID,NUMBER_RETRIES,TIME_BETWEEN_RETRIES,ERRORS_NOT_REQUIRE_TICKET) VALUES ('UNICENTER','UNICENTER','TICKET',2,1,0,0,0)
GO
SELECT 'DESPUES' AS 'RFC_ C00018923',* FROM [SCH_CENTRA_ID].[APPLICATIONS_GROUP]
GO

SELECT 'ANTES' AS 'RFC_ C00018923',* FROM [SCH_CENTRA_ID].[APPLICATIONS]
GO
INSERT INTO sch_centra_id.APPLICATIONS (CODE, NAME, automatic_provision,valid,APPLICATION_GROUP_ID,STATUS) VALUES ('BANCS','BANCS',1,1,(select id from sch_centra_id.APPLICATIONS_GROUP where code='BANCS'),'ACTIVO')
GO
INSERT INTO sch_centra_id.APPLICATIONS (CODE, NAME, automatic_provision,valid,APPLICATION_GROUP_ID,STATUS) VALUES ('PPRD','PPRD',1,1,(select id from sch_centra_id.APPLICATIONS_GROUP where code='PPRD'),'ACTIVO')
GO
INSERT INTO sch_centra_id.APPLICATIONS (CODE, NAME, automatic_provision,valid,APPLICATION_GROUP_ID,STATUS) VALUES ('LOGIFLOW','LOGIFLOW',1,1,(select id from sch_centra_id.APPLICATIONS_GROUP where code='LOGICIEL'),'ACTIVO')
GO
INSERT INTO sch_centra_id.APPLICATIONS (CODE, NAME, automatic_provision,valid,APPLICATION_GROUP_ID,STATUS) VALUES ('LGD','LOGIGENDOCS',1,1,(select id from sch_centra_id.APPLICATIONS_GROUP where code='LOGICIEL'),'ACTIVO')
GO
INSERT INTO sch_centra_id.APPLICATIONS (CODE, NAME, automatic_provision,valid,APPLICATION_GROUP_ID,STATUS) VALUES ('LPT','LOGIPORTAL',1,1,(select id from sch_centra_id.APPLICATIONS_GROUP where code='LOGICIEL'),'ACTIVO')
GO
INSERT INTO sch_centra_id.APPLICATIONS (CODE, NAME, automatic_provision,valid,APPLICATION_GROUP_ID,STATUS) VALUES ('SCR','LOGISCORE',1,1,(select id from sch_centra_id.APPLICATIONS_GROUP where code='LOGICIEL'),'ACTIVO')
GO
INSERT INTO sch_centra_id.APPLICATIONS (CODE, NAME, automatic_provision,valid,APPLICATION_GROUP_ID,STATUS) VALUES ('LSG','LOGISEG',1,1,(select id from sch_centra_id.APPLICATIONS_GROUP where code='LOGICIEL'),'ACTIVO')
GO
INSERT INTO sch_centra_id.APPLICATIONS (CODE, NAME, automatic_provision,valid,APPLICATION_GROUP_ID,STATUS) VALUES ('LSX','LOGISIEX',1,1,(select id from sch_centra_id.APPLICATIONS_GROUP where code='LOGICIEL'),'ACTIVO')
GO
INSERT INTO sch_centra_id.APPLICATIONS (CODE, NAME, automatic_provision,valid,APPLICATION_GROUP_ID,STATUS) VALUES ('LTR','LOGITRACE',1,1,(select id from sch_centra_id.APPLICATIONS_GROUP where code='LOGICIEL'),'ACTIVO')
GO
INSERT INTO sch_centra_id.APPLICATIONS (CODE, NAME, automatic_provision,valid,APPLICATION_GROUP_ID,STATUS) VALUES ('LGP','GESTORPARAMETROS',1,1,(select id from sch_centra_id.APPLICATIONS_GROUP where code='LOGICIEL'),'ACTIVO')
GO
INSERT INTO sch_centra_id.APPLICATIONS (CODE, NAME, automatic_provision,valid,APPLICATION_GROUP_ID,STATUS) VALUES ('RHDS','RHDS',1,1,(select id from sch_centra_id.APPLICATIONS_GROUP where code='RHDS'),'ACTIVO')
GO
INSERT INTO sch_centra_id.APPLICATIONS (CODE, NAME, automatic_provision,valid,APPLICATION_GROUP_ID,STATUS) VALUES ('AD','ACTIVE DIRECTORY',1,1,(select id from sch_centra_id.APPLICATIONS_GROUP where code='AD'),'ACTIVO')
GO
INSERT INTO sch_centra_id.APPLICATIONS (CODE, NAME, automatic_provision,valid,APPLICATION_GROUP_ID,STATUS) VALUES ('CAPITAL','CAPITAL',0,1,(select id from sch_centra_id.APPLICATIONS_GROUP where code='CAPITAL'),'ACTIVO')
GO
INSERT INTO sch_centra_id.APPLICATIONS (CODE, NAME, automatic_provision,valid,APPLICATION_GROUP_ID,STATUS) VALUES ('EASYPAGOS','EASYPAGOS',0,1,(select id from sch_centra_id.APPLICATIONS_GROUP where code='EASYPAGOS'),'ACTIVO')
GO
INSERT INTO sch_centra_id.APPLICATIONS (CODE, NAME, automatic_provision,valid,APPLICATION_GROUP_ID,STATUS) VALUES ('EBS','EBS',0,1,(select id from sch_centra_id.APPLICATIONS_GROUP where code='EBS'),'ACTIVO')
GO
INSERT INTO sch_centra_id.APPLICATIONS (CODE, NAME, automatic_provision,valid,APPLICATION_GROUP_ID,STATUS) VALUES ('LYNC','LYNC',0,1,(select id from sch_centra_id.APPLICATIONS_GROUP where code='LYNC'),'ACTIVO')
GO
INSERT INTO sch_centra_id.APPLICATIONS (CODE, NAME, automatic_provision,valid,APPLICATION_GROUP_ID,STATUS) VALUES ('TALLA','TALLA',0,1,(select id from sch_centra_id.APPLICATIONS_GROUP where code='TALLA'),'ACTIVO')
GO
INSERT INTO sch_centra_id.APPLICATIONS (CODE, NAME, automatic_provision,valid,APPLICATION_GROUP_ID,STATUS) VALUES ('HP_SERVICE_MANAGER','HP SERVICE MANAGER',0,1,(select id from sch_centra_id.APPLICATIONS_GROUP where code='HP_SERVICE_MANAGER'),'ACTIVO')
GO
INSERT INTO sch_centra_id.APPLICATIONS (CODE, NAME, automatic_provision,valid,APPLICATION_GROUP_ID,STATUS) VALUES ('SES','SOPORTE EN SITIO',0,1,(select id from sch_centra_id.APPLICATIONS_GROUP where code='SES'),'ACTIVO')
GO
INSERT INTO sch_centra_id.APPLICATIONS (CODE, NAME, automatic_provision,valid,APPLICATION_GROUP_ID,STATUS) VALUES ('HUMMINGBIRD','HUMMINGBIRD',0,1,(select id from sch_centra_id.APPLICATIONS_GROUP where code='HUMMINGBIRD'),'ACTIVO')
GO
INSERT INTO sch_centra_id.APPLICATIONS (CODE, NAME, automatic_provision,valid,APPLICATION_GROUP_ID,STATUS) VALUES ('PORTAL_AZURE','PORTAL AZURE',0,1,(select id from sch_centra_id.APPLICATIONS_GROUP where code='PORTAL_AZURE'),'ACTIVO')
GO
INSERT INTO sch_centra_id.APPLICATIONS (CODE, NAME, automatic_provision,valid,APPLICATION_GROUP_ID,STATUS) VALUES ('CONSOLA_SYMANTEC','CONSOLA SYMANTEC',0,1,(select id from sch_centra_id.APPLICATIONS_GROUP where code='CONSOLA_SYMANTEC'),'ACTIVO')
GO
INSERT INTO sch_centra_id.APPLICATIONS (CODE, NAME, automatic_provision,valid,APPLICATION_GROUP_ID,STATUS) VALUES ('SAS','SAS',0,1,(select id from sch_centra_id.APPLICATIONS_GROUP where code='SAS'),'ACTIVO')
GO
INSERT INTO sch_centra_id.APPLICATIONS (CODE, NAME, automatic_provision,valid,APPLICATION_GROUP_ID,STATUS) VALUES ('RYR','RECLAMOS Y REQUERIMIENTOS',0,1,(select id from sch_centra_id.APPLICATIONS_GROUP where code='RYR'),'ACTIVO')
GO
INSERT INTO sch_centra_id.APPLICATIONS (CODE, NAME, automatic_provision,valid,APPLICATION_GROUP_ID,STATUS) VALUES ('CANJE','CANJE',0,1,(select id from sch_centra_id.APPLICATIONS_GROUP where code='CANJE'),'ACTIVO')
GO
INSERT INTO sch_centra_id.APPLICATIONS (CODE, NAME, automatic_provision,valid,APPLICATION_GROUP_ID,STATUS) VALUES ('CITRIX','CITRIX',0,1,(select id from sch_centra_id.APPLICATIONS_GROUP where code='CITRIX'),'ACTIVO')
GO
INSERT INTO sch_centra_id.APPLICATIONS (CODE, NAME, automatic_provision,valid,APPLICATION_GROUP_ID,STATUS) VALUES ('GAF','GAF',0,1,(select id from sch_centra_id.APPLICATIONS_GROUP where code='GAF'),'ACTIVO')
GO
INSERT INTO sch_centra_id.APPLICATIONS (CODE, NAME, automatic_provision,valid,APPLICATION_GROUP_ID,STATUS) VALUES ('AS400_GAF','AS400 GAF',0,1,(select id from sch_centra_id.APPLICATIONS_GROUP where code='AS400_GAF'),'ACTIVO')
GO
INSERT INTO sch_centra_id.APPLICATIONS (CODE, NAME, automatic_provision,valid,APPLICATION_GROUP_ID,STATUS) VALUES ('BLOQUEAR_CORREO_EXTERNO','BLOQUEAR CORREO EXTERNO',0,1,(select id from sch_centra_id.APPLICATIONS_GROUP where code='BLOQUEAR_CORREO_EXTERNO'),'ACTIVO')
GO
INSERT INTO sch_centra_id.APPLICATIONS (CODE, NAME, automatic_provision,valid,APPLICATION_GROUP_ID,STATUS) VALUES ('IDENTITY_MINDER','IDENTITY MINDER',0,1,(select id from sch_centra_id.APPLICATIONS_GROUP where code='IDENTITY_MINDER'),'ACTIVO')
GO
INSERT INTO sch_centra_id.APPLICATIONS (CODE, NAME, automatic_provision,valid,APPLICATION_GROUP_ID,STATUS) VALUES ('ARCHIVO_DIGITAL','ARCHIVO DIGITAL',0,1,(select id from sch_centra_id.APPLICATIONS_GROUP where code='ARCHIVO_DIGITAL'),'ACTIVO')
GO
INSERT INTO sch_centra_id.APPLICATIONS (CODE, NAME, automatic_provision,valid,APPLICATION_GROUP_ID,STATUS) VALUES ('BACTRADER','BACTRADER',0,1,(select id from sch_centra_id.APPLICATIONS_GROUP where code='BACTRADER'),'ACTIVO')
GO
INSERT INTO sch_centra_id.APPLICATIONS (CODE, NAME, automatic_provision,valid,APPLICATION_GROUP_ID,STATUS) VALUES ('CREDIFE','CREDIFE',0,1,(select id from sch_centra_id.APPLICATIONS_GROUP where code='CREDIFE'),'ACTIVO')
GO
INSERT INTO sch_centra_id.APPLICATIONS (CODE, NAME, automatic_provision,valid,APPLICATION_GROUP_ID,STATUS) VALUES ('ICS','ICS',0,1,(select id from sch_centra_id.APPLICATIONS_GROUP where code='ICS'),'ACTIVO')
GO
INSERT INTO sch_centra_id.APPLICATIONS (CODE, NAME, automatic_provision,valid,APPLICATION_GROUP_ID,STATUS) VALUES ('SOS','SOS',0,1,(select id from sch_centra_id.APPLICATIONS_GROUP where code='SOS'),'ACTIVO')
GO
INSERT INTO sch_centra_id.APPLICATIONS (CODE, NAME, automatic_provision,valid,APPLICATION_GROUP_ID,STATUS) VALUES ('CREDITLENS','CREDITLENS',0,1,(select id from sch_centra_id.APPLICATIONS_GROUP where code='CREDITLENS'),'ACTIVO')
GO
INSERT INTO sch_centra_id.APPLICATIONS (CODE, NAME, automatic_provision,valid,APPLICATION_GROUP_ID,STATUS) VALUES ('BDD_PLSQL','BDD PLSQL',0,1,(select id from sch_centra_id.APPLICATIONS_GROUP where code='BDD_PLSQL'),'ACTIVO')
GO
INSERT INTO sch_centra_id.APPLICATIONS (CODE, NAME, automatic_provision,valid,APPLICATION_GROUP_ID,STATUS) VALUES ('PIVI','PIVI',0,1,(select id from sch_centra_id.APPLICATIONS_GROUP where code='PIVI'),'ACTIVO')
GO
INSERT INTO sch_centra_id.APPLICATIONS (CODE, NAME, automatic_provision,valid,APPLICATION_GROUP_ID,STATUS) VALUES ('PIVI_WEB','PIVI WEB',0,1,(select id from sch_centra_id.APPLICATIONS_GROUP where code='PIVI_WEB'),'ACTIVO')
GO
INSERT INTO sch_centra_id.APPLICATIONS (CODE, NAME, automatic_provision,valid,APPLICATION_GROUP_ID,STATUS) VALUES ('SENTINEL','SENTINEL',0,1,(select id from sch_centra_id.APPLICATIONS_GROUP where code='SENTINEL'),'ACTIVO')
GO
INSERT INTO sch_centra_id.APPLICATIONS (CODE, NAME, automatic_provision,valid,APPLICATION_GROUP_ID,STATUS) VALUES ('COBIS','COBIS',0,1,(select id from sch_centra_id.APPLICATIONS_GROUP where code='COBIS'),'ACTIVO')
GO
INSERT INTO sch_centra_id.APPLICATIONS (CODE, NAME, automatic_provision,valid,APPLICATION_GROUP_ID,STATUS) VALUES ('SEC','SEC',0,1,(select id from sch_centra_id.APPLICATIONS_GROUP where code='SEC'),'ACTIVO')
GO
INSERT INTO sch_centra_id.APPLICATIONS (CODE, NAME, automatic_provision,valid,APPLICATION_GROUP_ID,STATUS) VALUES ('GEORUTA','GEORUTA',0,1,(select id from sch_centra_id.APPLICATIONS_GROUP where code='GEORUTA'),'ACTIVO')
GO
INSERT INTO sch_centra_id.APPLICATIONS (CODE, NAME, automatic_provision,valid,APPLICATION_GROUP_ID,STATUS) VALUES ('MISRIESGO','MISRIESGO',0,1,(select id from sch_centra_id.APPLICATIONS_GROUP where code='MISRIESGO'),'ACTIVO')
GO
INSERT INTO sch_centra_id.APPLICATIONS (CODE, NAME, automatic_provision,valid,APPLICATION_GROUP_ID,STATUS) VALUES ('CRM BP','CRM BP',0,1,(select id from sch_centra_id.APPLICATIONS_GROUP where code='CRM_BP'),'ACTIVO')
GO
INSERT INTO sch_centra_id.APPLICATIONS (CODE, NAME, automatic_provision,valid,APPLICATION_GROUP_ID,STATUS) VALUES ('NETMANAGER','NETMANAGER',0,1,(select id from sch_centra_id.APPLICATIONS_GROUP where code='NETMANAGER'),'ACTIVO')
GO
INSERT INTO sch_centra_id.APPLICATIONS (CODE, NAME, automatic_provision,valid,APPLICATION_GROUP_ID,STATUS) VALUES ('BANCKTRADE','BANCKTRADE',0,1,(select id from sch_centra_id.APPLICATIONS_GROUP where code='BANCKTRADE'),'ACTIVO')
GO
INSERT INTO sch_centra_id.APPLICATIONS (CODE, NAME, automatic_provision,valid,APPLICATION_GROUP_ID,STATUS) VALUES ('CRM_DINERS','CRM DINERS',0,1,(select id from sch_centra_id.APPLICATIONS_GROUP where code='CRM_DINERS'),'ACTIVO')
GO
INSERT INTO sch_centra_id.APPLICATIONS (CODE, NAME, automatic_provision,valid,APPLICATION_GROUP_ID,STATUS) VALUES ('FASTWORK','FASTWORK',0,1,(select id from sch_centra_id.APPLICATIONS_GROUP where code='FASTWORK'),'ACTIVO')
GO
INSERT INTO sch_centra_id.APPLICATIONS (CODE, NAME, automatic_provision,valid,APPLICATION_GROUP_ID,STATUS) VALUES ('TURBOSWIFT','TURBOSWIFT',0,1,(select id from sch_centra_id.APPLICATIONS_GROUP where code='TURBOSWIFT'),'ACTIVO')
GO
INSERT INTO sch_centra_id.APPLICATIONS (CODE, NAME, automatic_provision,valid,APPLICATION_GROUP_ID,STATUS) VALUES ('MOODYS','MOODYS',0,1,(select id from sch_centra_id.APPLICATIONS_GROUP where code='MOODYS'),'ACTIVO')
GO
INSERT INTO sch_centra_id.APPLICATIONS (CODE, NAME, automatic_provision,valid,APPLICATION_GROUP_ID,STATUS) VALUES ('VCM','VCM',0,1,(select id from sch_centra_id.APPLICATIONS_GROUP where code='VCM'),'ACTIVO')
GO
INSERT INTO sch_centra_id.APPLICATIONS (CODE, NAME, automatic_provision,valid,APPLICATION_GROUP_ID,STATUS) VALUES ('CAO','CAO',0,1,(select id from sch_centra_id.APPLICATIONS_GROUP where code='CAO'),'ACTIVO')
GO
INSERT INTO sch_centra_id.APPLICATIONS (CODE, NAME, automatic_provision,valid,APPLICATION_GROUP_ID,STATUS) VALUES ('BIOSERVER','BIOSERVER',0,1,(select id from sch_centra_id.APPLICATIONS_GROUP where code='BIOSERVER'),'ACTIVO')
GO
INSERT INTO sch_centra_id.APPLICATIONS (CODE, NAME, automatic_provision,valid,APPLICATION_GROUP_ID,STATUS) VALUES ('BRIDGER_INSIGHT','BRIDGER INSIGHT',0,1,(select id from sch_centra_id.APPLICATIONS_GROUP where code='BRIDGER_INSIGHT'),'ACTIVO')
GO
INSERT INTO sch_centra_id.APPLICATIONS (CODE, NAME, automatic_provision,valid,APPLICATION_GROUP_ID,STATUS) VALUES ('CAPTOVATION','CAPTOVATION',0,1,(select id from sch_centra_id.APPLICATIONS_GROUP where code='CAPTOVATION'),'ACTIVO')
GO
INSERT INTO sch_centra_id.APPLICATIONS (CODE, NAME, automatic_provision,valid,APPLICATION_GROUP_ID,STATUS) VALUES ('BDD_SQL','BDD SQL',0,1,(select id from sch_centra_id.APPLICATIONS_GROUP where code='BDD_SQL'),'ACTIVO')
GO
INSERT INTO sch_centra_id.APPLICATIONS (CODE, NAME, automatic_provision,valid,APPLICATION_GROUP_ID,STATUS) VALUES ('HYPERION','HYPERION',0,1,(select id from sch_centra_id.APPLICATIONS_GROUP where code='HYPERION'),'ACTIVO')
GO
INSERT INTO sch_centra_id.APPLICATIONS (CODE, NAME, automatic_provision,valid,APPLICATION_GROUP_ID,STATUS) VALUES ('BDD _POSTGRES','BDD POSTGRES',0,1,(select id from sch_centra_id.APPLICATIONS_GROUP where code='BDD_POSTGRES'),'ACTIVO')
GO
INSERT INTO sch_centra_id.APPLICATIONS (CODE, NAME, automatic_provision,valid,APPLICATION_GROUP_ID,STATUS) VALUES ('MUREX','MUREX',0,1,(select id from sch_centra_id.APPLICATIONS_GROUP where code='MUREX'),'ACTIVO')
GO
INSERT INTO sch_centra_id.APPLICATIONS (CODE, NAME, automatic_provision,valid,APPLICATION_GROUP_ID,STATUS) VALUES ('SO_UNIX','SO UNIX',0,1,(select id from sch_centra_id.APPLICATIONS_GROUP where code='SO_UNIX'),'ACTIVO')
GO
INSERT INTO sch_centra_id.APPLICATIONS (CODE, NAME, automatic_provision,valid,APPLICATION_GROUP_ID,STATUS) VALUES ('SO_UNIX_STORAGE','SO UNIX STORAGE',0,1,(select id from sch_centra_id.APPLICATIONS_GROUP where code='SO_UNIX_STORAGE'),'ACTIVO')
GO
INSERT INTO sch_centra_id.APPLICATIONS (CODE, NAME, automatic_provision,valid,APPLICATION_GROUP_ID,STATUS) VALUES ('TOTEM','TOTEM',0,1,(select id from sch_centra_id.APPLICATIONS_GROUP where code='TOTEM'),'ACTIVO')
GO
INSERT INTO sch_centra_id.APPLICATIONS (CODE, NAME, automatic_provision,valid,APPLICATION_GROUP_ID,STATUS) VALUES ('CONTACTOS_EXCHANGE','CONTACTOS EXCHANGE',0,1,(select id from sch_centra_id.APPLICATIONS_GROUP where code='CONTACTOS_EXCHANGE'),'ACTIVO')
GO
INSERT INTO sch_centra_id.APPLICATIONS (CODE, NAME, automatic_provision,valid,APPLICATION_GROUP_ID,STATUS) VALUES ('TRANSACCION_MOTIVO_BANCS','TRANSACCION MOTIVO BANCS',0,1,(select id from sch_centra_id.APPLICATIONS_GROUP where code='TRANSACCION_MOTIVO_BANCS'),'ACTIVO')
GO
INSERT INTO sch_centra_id.APPLICATIONS (CODE, NAME, automatic_provision,valid,APPLICATION_GROUP_ID,STATUS) VALUES ('GEENERA','GEENERA',0,1,(select id from sch_centra_id.APPLICATIONS_GROUP where code='GEENERA'),'ACTIVO')
GO
INSERT INTO sch_centra_id.APPLICATIONS (CODE, NAME, automatic_provision,valid,APPLICATION_GROUP_ID,STATUS) VALUES ('APPL _INTERNA_LIBRARIAN','APPL INTERNA LIBRARIAN',0,1,(select id from sch_centra_id.APPLICATIONS_GROUP where code='APPL _INTERNA_LIBRARIAN'),'ACTIVO')
GO
INSERT INTO sch_centra_id.APPLICATIONS (CODE, NAME, automatic_provision,valid,APPLICATION_GROUP_ID,STATUS) VALUES ('SERVIDORES_ADMI','SERVIDORES ADMI',0,1,(select id from sch_centra_id.APPLICATIONS_GROUP where code='SERVIDORES_ADMI'),'ACTIVO')
GO
INSERT INTO sch_centra_id.APPLICATIONS (CODE, NAME, automatic_provision,valid,APPLICATION_GROUP_ID,STATUS) VALUES ('SERVIDORES_LIBRARIAN','SERVIDORES LIBRARIAN',0,1,(select id from sch_centra_id.APPLICATIONS_GROUP where code='SERVIDORES_LIBRARIAN'),'ACTIVO')
GO
INSERT INTO sch_centra_id.APPLICATIONS (CODE, NAME, automatic_provision,valid,APPLICATION_GROUP_ID,STATUS) VALUES ('SERVIDORES_MANT_APPL','SERVIDORES MANT APPL',0,1,(select id from sch_centra_id.APPLICATIONS_GROUP where code='SERVIDORES_MANT_APPL'),'ACTIVO')
GO
INSERT INTO sch_centra_id.APPLICATIONS (CODE, NAME, automatic_provision,valid,APPLICATION_GROUP_ID,STATUS) VALUES ('SERVIDORES_RED_TEAM','SERVIDORES RED TEAM',0,1,(select id from sch_centra_id.APPLICATIONS_GROUP where code='SERVIDORES_RED_TEAM'),'ACTIVO')
GO
INSERT INTO sch_centra_id.APPLICATIONS (CODE, NAME, automatic_provision,valid,APPLICATION_GROUP_ID,STATUS) VALUES ('FTP_EXTERNO','FTP EXTERNO',0,1,(select id from sch_centra_id.APPLICATIONS_GROUP where code='FTP_EXTERNO'),'ACTIVO')
GO
INSERT INTO sch_centra_id.APPLICATIONS (CODE, NAME, automatic_provision,valid,APPLICATION_GROUP_ID,STATUS) VALUES ('TOKEN_BCE','TOKEN BCE',0,1,(select id from sch_centra_id.APPLICATIONS_GROUP where code='TOKEN_BCE'),'ACTIVO')
GO
INSERT INTO sch_centra_id.APPLICATIONS (CODE, NAME, automatic_provision,valid,APPLICATION_GROUP_ID,STATUS) VALUES ('ANF','ANF',0,1,(select id from sch_centra_id.APPLICATIONS_GROUP where code='ANF'),'ACTIVO')
GO
INSERT INTO sch_centra_id.APPLICATIONS (CODE, NAME, automatic_provision,valid,APPLICATION_GROUP_ID,STATUS) VALUES ('CLEARSTREAM','CLEARSTREAM',0,1,(select id from sch_centra_id.APPLICATIONS_GROUP where code='CLEARSTREAM'),'ACTIVO')
GO
INSERT INTO sch_centra_id.APPLICATIONS (CODE, NAME, automatic_provision,valid,APPLICATION_GROUP_ID,STATUS) VALUES ('VERTICES','VERTICES',0,1,(select id from sch_centra_id.APPLICATIONS_GROUP where code='VERTICES'),'ACTIVO')
GO
INSERT INTO sch_centra_id.APPLICATIONS (CODE, NAME, automatic_provision,valid,APPLICATION_GROUP_ID,STATUS) VALUES ('SYSTEM_CENTER','SYSTEM CENTER',0,1,(select id from sch_centra_id.APPLICATIONS_GROUP where code='SYSTEM_CENTER'),'ACTIVO')
GO
INSERT INTO sch_centra_id.APPLICATIONS (CODE, NAME, automatic_provision,valid,APPLICATION_GROUP_ID,STATUS) VALUES ('RCSA','RCSA',0,1,(select id from sch_centra_id.APPLICATIONS_GROUP where code='RCSA'),'ACTIVO')
GO
INSERT INTO sch_centra_id.APPLICATIONS (CODE, NAME, automatic_provision,valid,APPLICATION_GROUP_ID,STATUS) VALUES ('OTROS','OTROS',0,1,(select id from sch_centra_id.APPLICATIONS_GROUP where code='OTROS'),'ACTIVO')
GO
INSERT INTO sch_centra_id.APPLICATIONS (CODE, NAME, automatic_provision,valid,APPLICATION_GROUP_ID,STATUS) VALUES ('CAPITAL_CREDIFE','CAPITAL CREDIFE',0,1,(select id from sch_centra_id.APPLICATIONS_GROUP where code='CAPITAL_CREDIFE'),'ACTIVO')
GO
INSERT INTO sch_centra_id.APPLICATIONS (CODE, NAME, automatic_provision,valid,APPLICATION_GROUP_ID,STATUS) VALUES ('GAF_PANAMA','GAF PANAMA',0,1,(select id from sch_centra_id.APPLICATIONS_GROUP where code='GAF_PANAMA'),'ACTIVO')
GO
INSERT INTO sch_centra_id.APPLICATIONS (CODE, NAME, automatic_provision,valid,APPLICATION_GROUP_ID,STATUS) VALUES ('RIESGO_DETALLADO','RIESGO DETALLADO',0,1,(select id from sch_centra_id.APPLICATIONS_GROUP where code='RIESGO_DETALLADO'),'ACTIVO')
GO
INSERT INTO sch_centra_id.APPLICATIONS (CODE, NAME, automatic_provision,valid,APPLICATION_GROUP_ID,STATUS) VALUES ('REPORTING_SERVICES','REPORTING SERVICES',0,1,(select id from sch_centra_id.APPLICATIONS_GROUP where code='REPORTING_SERVICES'),'ACTIVO')
GO
INSERT INTO sch_centra_id.APPLICATIONS (CODE, NAME, automatic_provision,valid,APPLICATION_GROUP_ID,STATUS) VALUES ('OPENBANK','OPENBANK',0,1,(select id from sch_centra_id.APPLICATIONS_GROUP where code='OPENBANK'),'ACTIVO')
GO
INSERT INTO sch_centra_id.APPLICATIONS (CODE, NAME, automatic_provision,valid,APPLICATION_GROUP_ID,STATUS) VALUES ('TURBO_SWIFT','TURBO SWIFT',0,1,(select id from sch_centra_id.APPLICATIONS_GROUP where code='TURBO_SWIFT'),'ACTIVO')
GO
INSERT INTO sch_centra_id.APPLICATIONS (CODE, NAME, automatic_provision,valid,APPLICATION_GROUP_ID,STATUS) VALUES ('BANKTRADE','BANKTRADE',0,1,(select id from sch_centra_id.APPLICATIONS_GROUP where code='BANKTRADE'),'ACTIVO')
GO
INSERT INTO sch_centra_id.APPLICATIONS (CODE, NAME, automatic_provision,valid,APPLICATION_GROUP_ID,STATUS) VALUES ('ADAM','ADAM',0,1,(select id from sch_centra_id.APPLICATIONS_GROUP where code='ADAM'),'ACTIVO')
GO
INSERT INTO sch_centra_id.APPLICATIONS (CODE, NAME, automatic_provision,valid,APPLICATION_GROUP_ID,STATUS) VALUES ('GRUPO_PORTAL_ADICIONAL','GRUPO PORTAL ADICIONAL',0,1,(select id from sch_centra_id.APPLICATIONS_GROUP where code='GRUPO_PORTAL_ADICIONAL'),'ACTIVO')
GO
INSERT INTO sch_centra_id.APPLICATIONS (CODE, NAME, automatic_provision,valid,APPLICATION_GROUP_ID,STATUS) VALUES ('UNICENTER','UNICENTER',0,1,(select id from sch_centra_id.APPLICATIONS_GROUP where code='UNICENTER'),'ACTIVO')
GO
SELECT 'DESPUES' AS 'RFC_ C00018923',* FROM [SCH_CENTRA_ID].[APPLICATIONS]
GO

