SELECT 'ANTES' AS 'RFC_ C00018923',* FROM [SCH_CENTRA_ID].[FIELDS]
GO
DELETE FROM sch_centra_id.FIELDS 
GO
INSERT INTO sch_centra_id.FIELDS (CODE, NAME, PREDETERMINED,LENGTH,REQUIRED,TYPE,VALID,APPLICATION_GROUP_ID) VALUES ('grupoTransaccion','GRUPO TRANSACCIÓN',null,2,1,'NUMBER',1,(SELECT id FROM sch_centra_id.APPLICATIONS_GROUP WHERE CODE='BANCS'))
GO
INSERT INTO sch_centra_id.FIELDS (CODE, NAME, PREDETERMINED,LENGTH,REQUIRED,TYPE,VALID,APPLICATION_GROUP_ID) VALUES ('nivelCapacidad','NIVEL CAPACIDAD',null,2,1,'NUMBER',1,(SELECT id FROM sch_centra_id.APPLICATIONS_GROUP WHERE CODE='BANCS'))
GO
INSERT INTO sch_centra_id.FIELDS (CODE, NAME, PREDETERMINED,LENGTH,REQUIRED,TYPE,VALID,APPLICATION_GROUP_ID) VALUES ('nivelCorreo','NIVEL CORREO',null,2,1,'NUMBER',1,(SELECT id FROM sch_centra_id.APPLICATIONS_GROUP WHERE CODE='BANCS'))
GO
INSERT INTO sch_centra_id.FIELDS (CODE, NAME, PREDETERMINED,LENGTH,REQUIRED,TYPE,VALID,APPLICATION_GROUP_ID) VALUES ('userType','TIPO USUARIO',null,2,1,'NUMBER',1,(SELECT id FROM sch_centra_id.APPLICATIONS_GROUP WHERE CODE='BANCS'))
GO
INSERT INTO sch_centra_id.FIELDS (CODE, NAME, PREDETERMINED,LENGTH,REQUIRED,TYPE,VALID,APPLICATION_GROUP_ID) VALUES ('accignmod','MODO DE ACCESO DE ASIGNACIÓN',null,10,1,'STRING',1,(SELECT id FROM sch_centra_id.APPLICATIONS_GROUP WHERE CODE='BANCS'))
GO
INSERT INTO sch_centra_id.FIELDS (CODE, NAME, PREDETERMINED,LENGTH,REQUIRED,TYPE,VALID,APPLICATION_GROUP_ID) VALUES ('atmflag','BANDERA DE ATM','N',10,1,'STRING',1,(SELECT id FROM sch_centra_id.APPLICATIONS_GROUP WHERE CODE='BANCS'))
GO
INSERT INTO sch_centra_id.FIELDS (CODE, NAME, PREDETERMINED,LENGTH,REQUIRED,TYPE,VALID,APPLICATION_GROUP_ID) VALUES ('brchSup','BRANCH SUPERIOR','Y',10,1,'STRING',1,(SELECT id FROM sch_centra_id.APPLICATIONS_GROUP WHERE CODE='BANCS'))
GO
INSERT INTO sch_centra_id.FIELDS (CODE, NAME, PREDETERMINED,LENGTH,REQUIRED,TYPE,VALID,APPLICATION_GROUP_ID) VALUES ('casualApprovallim','LIMITE APROVISIONAMIENTO CASUAL',null,10,1,'STRING',1,(SELECT id FROM sch_centra_id.APPLICATIONS_GROUP WHERE CODE='BANCS'))
GO
INSERT INTO sch_centra_id.FIELDS (CODE, NAME, PREDETERMINED,LENGTH,REQUIRED,TYPE,VALID,APPLICATION_GROUP_ID) VALUES ('chngBranchallow','PERMITE CAMBIOS DE BRANCH',null,10,1,'STRING',1,(SELECT id FROM sch_centra_id.APPLICATIONS_GROUP WHERE CODE='BANCS'))
GO
INSERT INTO sch_centra_id.FIELDS (CODE, NAME, PREDETERMINED,LENGTH,REQUIRED,TYPE,VALID,APPLICATION_GROUP_ID) VALUES ('nivelSeguridad','NIVEL SEGURIDAD',null,2,1,'NUMBER',1,(SELECT id FROM sch_centra_id.APPLICATIONS_GROUP WHERE CODE='BANCS'))
GO
INSERT INTO sch_centra_id.FIELDS (CODE, NAME, PREDETERMINED,LENGTH,REQUIRED,TYPE,VALID,APPLICATION_GROUP_ID) VALUES ('estadoUsuario','ESTADO USUARIO','1',2,1,'NUMBER',1,(SELECT id FROM sch_centra_id.APPLICATIONS_GROUP WHERE CODE='BANCS'))
GO
INSERT INTO sch_centra_id.FIELDS (CODE, NAME, PREDETERMINED,LENGTH,REQUIRED,TYPE,VALID,APPLICATION_GROUP_ID) VALUES ('perfilUsuario','PERFIL USUARIO','No',8,1,'STRING',1,(SELECT id FROM sch_centra_id.APPLICATIONS_GROUP WHERE CODE='PPRD'))
GO
INSERT INTO sch_centra_id.FIELDS (CODE, NAME, PREDETERMINED,LENGTH,REQUIRED,TYPE,VALID,APPLICATION_GROUP_ID) VALUES ('enviarMail','ENVÍA MAIL DE CREACIÓN DE USUARIO','S',1,1,'STRING',1,(SELECT id FROM sch_centra_id.APPLICATIONS_GROUP WHERE CODE='LOGICIEL'))
GO
INSERT INTO sch_centra_id.FIELDS (CODE, NAME, PREDETERMINED,LENGTH,REQUIRED,TYPE,VALID,APPLICATION_GROUP_ID) VALUES ('cambioPwdInicial','CAMBIO DE PASSWORD AL LOGUEARSE','S',1,1,'STRING',1,(SELECT id FROM sch_centra_id.APPLICATIONS_GROUP WHERE CODE='LOGICIEL'))
GO
INSERT INTO sch_centra_id.FIELDS (CODE, NAME, PREDETERMINED,LENGTH,REQUIRED,TYPE,VALID,APPLICATION_GROUP_ID) VALUES ('codigoRol ','CÓDIGO ROL ',null,30,1,'STRING',1,(SELECT id FROM sch_centra_id.APPLICATIONS_GROUP WHERE CODE='LOGICIEL'))
GO
INSERT INTO sch_centra_id.FIELDS (CODE, NAME, PREDETERMINED,LENGTH,REQUIRED,TYPE,VALID,APPLICATION_GROUP_ID) VALUES ('codigoHorario','CÓDIGO HORARIO','HN',1,1,'STRING',1,(SELECT id FROM sch_centra_id.APPLICATIONS_GROUP WHERE CODE='LOGICIEL'))
GO
INSERT INTO sch_centra_id.FIELDS (CODE, NAME, PREDETERMINED,LENGTH,REQUIRED,TYPE,VALID,APPLICATION_GROUP_ID) VALUES ('validarAtributosPerfil','VALIDAR ATRIBUTOS PERFIL','S',1,1,'STRING',1,(SELECT id FROM sch_centra_id.APPLICATIONS_GROUP WHERE CODE='LOGICIEL'))
GO
INSERT INTO sch_centra_id.FIELDS (CODE, NAME, PREDETERMINED,LENGTH,REQUIRED,TYPE,VALID,APPLICATION_GROUP_ID) VALUES ('codigoAtributo','CÓODIGO ATRIBUTO','16',2,1,'NUMBER',1,(SELECT id FROM sch_centra_id.APPLICATIONS_GROUP WHERE CODE='LOGICIEL'))
GO
INSERT INTO sch_centra_id.FIELDS (CODE, NAME, PREDETERMINED,LENGTH,REQUIRED,TYPE,VALID,APPLICATION_GROUP_ID) VALUES ('gruposLoginCentralizado','GRUPOS LOGIN CENTRALIZADO',null,100,1,'STRING',1,(SELECT id FROM sch_centra_id.APPLICATIONS_GROUP WHERE CODE='RHDS'))
GO
INSERT INTO sch_centra_id.FIELDS (CODE, NAME, PREDETERMINED,LENGTH,REQUIRED,TYPE,VALID,APPLICATION_GROUP_ID) VALUES ('crearCorreo','CREAR CORREO',null,1,1,'STRING',1,(SELECT id FROM sch_centra_id.APPLICATIONS_GROUP WHERE CODE='AD'))
GO
INSERT INTO sch_centra_id.FIELDS (CODE, NAME, PREDETERMINED,LENGTH,REQUIRED,TYPE,VALID,APPLICATION_GROUP_ID) VALUES ('tipoBuzon','TIPO DE BUZÓN',null,100,1,'STRING',1,(SELECT id FROM sch_centra_id.APPLICATIONS_GROUP WHERE CODE='AD'))
GO
INSERT INTO sch_centra_id.FIELDS (CODE, NAME, PREDETERMINED,LENGTH,REQUIRED,TYPE,VALID,APPLICATION_GROUP_ID) VALUES ('changePasswordNextLogon','USER MUST CHANGE PASSWORD AT NEXT LOGON',null,1,1,'STRING',1,(SELECT id FROM sch_centra_id.APPLICATIONS_GROUP WHERE CODE='AD'))
GO
INSERT INTO sch_centra_id.FIELDS (CODE, NAME, PREDETERMINED,LENGTH,REQUIRED,TYPE,VALID,APPLICATION_GROUP_ID) VALUES ('userCannotChangePassword','USER CANNOT CHANGE PASSWORD',null,1,1,'STRING',1,(SELECT id FROM sch_centra_id.APPLICATIONS_GROUP WHERE CODE='AD'))
GO
INSERT INTO sch_centra_id.FIELDS (CODE, NAME, PREDETERMINED,LENGTH,REQUIRED,TYPE,VALID,APPLICATION_GROUP_ID) VALUES ('passwordNeverExpires','PASSWORD NEVER EXPIRES',null,1,1,'STRING',1,(SELECT id FROM sch_centra_id.APPLICATIONS_GROUP WHERE CODE='AD'))
GO
INSERT INTO sch_centra_id.FIELDS (CODE, NAME, PREDETERMINED,LENGTH,REQUIRED,TYPE,VALID,APPLICATION_GROUP_ID) VALUES ('contenedor','CONTENEDOR',null,500,1,'STRING',1,(SELECT id FROM sch_centra_id.APPLICATIONS_GROUP WHERE CODE='AD'))
GO
INSERT INTO sch_centra_id.FIELDS (CODE, NAME, PREDETERMINED,LENGTH,REQUIRED,TYPE,VALID,APPLICATION_GROUP_ID) VALUES ('grupos','GRUPOS',null,500,1,'STRING',1,(SELECT id FROM sch_centra_id.APPLICATIONS_GROUP WHERE CODE='AD'))
GO
INSERT INTO sch_centra_id.FIELDS (CODE, NAME, PREDETERMINED,LENGTH,REQUIRED,TYPE,VALID,APPLICATION_GROUP_ID) VALUES ('owa','OWA',null,1,1,'STRING',1,(SELECT id FROM sch_centra_id.APPLICATIONS_GROUP WHERE CODE='AD'))
GO
INSERT INTO sch_centra_id.FIELDS (CODE, NAME, PREDETERMINED,LENGTH,REQUIRED,TYPE,VALID,APPLICATION_GROUP_ID) VALUES ('activesync','ACTIVESYNC',null,1,1,'STRING',1,(SELECT id FROM sch_centra_id.APPLICATIONS_GROUP WHERE CODE='AD'))
GO
INSERT INTO sch_centra_id.FIELDS (CODE, NAME, PREDETERMINED,LENGTH,REQUIRED,TYPE,VALID,APPLICATION_GROUP_ID) VALUES ('sip','SIP',null,1,1,'STRING',1,(SELECT id FROM sch_centra_id.APPLICATIONS_GROUP WHERE CODE='AD'))
GO
INSERT INTO sch_centra_id.FIELDS (CODE, NAME, PREDETERMINED,LENGTH,REQUIRED,TYPE,VALID,APPLICATION_GROUP_ID) VALUES ('terminalServicesProfile','TERMINAL SERVICES PROFILE',null,100,1,'STRING',1,(SELECT id FROM sch_centra_id.APPLICATIONS_GROUP WHERE CODE='AD'))
GO
INSERT INTO sch_centra_id.FIELDS (CODE, NAME, PREDETERMINED,LENGTH,REQUIRED,TYPE,VALID,APPLICATION_GROUP_ID) VALUES ('connectFollowingDrive','CONNECT THE FOLLOWING DRIVE',null,100,1,'STRING',1,(SELECT id FROM sch_centra_id.APPLICATIONS_GROUP WHERE CODE='AD'))
GO
INSERT INTO sch_centra_id.FIELDS (CODE, NAME, PREDETERMINED,LENGTH,REQUIRED,TYPE,VALID,APPLICATION_GROUP_ID) VALUES ('terminalServicesHomeDirectory','TERMINAL SERVICES HOME DIRECTORY',null,100,1,'STRING',1,(SELECT id FROM sch_centra_id.APPLICATIONS_GROUP WHERE CODE='AD'))
GO
INSERT INTO sch_centra_id.FIELDS (CODE, NAME, PREDETERMINED,LENGTH,REQUIRED,TYPE,VALID,APPLICATION_GROUP_ID) VALUES ('allowLogonTerminalServer','ALLOW LOGON TO TERMINAL SERVER',null,1,1,'STRING',1,(SELECT id FROM sch_centra_id.APPLICATIONS_GROUP WHERE CODE='AD'))
GO

DELETE FROM sch_centra_id.MATRICES_DETAIL 
GO
DELETE FROM sch_centra_id.MATRICES 
GO
 
INSERT INTO sch_centra_id.MATRICES (CODE, NAME, QUANTITY,VALID,APPLICATION_GROUP_ID) VALUES ('aplicaciones','APLICACIONES',3,1,(SELECT id FROM sch_centra_id.APPLICATIONS_GROUP WHERE CODE='LOGICIEL'))
GO
INSERT INTO sch_centra_id.MATRICES (CODE, NAME, QUANTITY,VALID,APPLICATION_GROUP_ID) VALUES ('perfiles','PERFILES',3,1,(SELECT id FROM sch_centra_id.APPLICATIONS_GROUP WHERE CODE='RHDS'))
GO

INSERT INTO sch_centra_id.MATRICES_DETAIL (CODE, NAME,VALID,MATRIX_ID) VALUES ('application','APLICACIÓN',1,(SELECT id FROM sch_centra_id.MATRICES WHERE CODE='aplicaciones'))
GO
INSERT INTO sch_centra_id.MATRICES_DETAIL (CODE, NAME,VALID,MATRIX_ID) VALUES ('perfil','PERFILES',1,(SELECT id FROM sch_centra_id.MATRICES WHERE CODE='aplicaciones'))
GO
INSERT INTO sch_centra_id.MATRICES_DETAIL (CODE, NAME,VALID,MATRIX_ID) VALUES ('perfilUsuario','PERFIL USUARIO',1,(SELECT id FROM sch_centra_id.MATRICES WHERE CODE='perfiles'))
GO
INSERT INTO sch_centra_id.MATRICES_DETAIL (CODE, NAME,VALID,MATRIX_ID) VALUES ('roles','ROLES',1,(SELECT id FROM sch_centra_id.MATRICES WHERE CODE='perfiles'))
GO
SELECT 'DESPUES' AS 'RFC_ C00018923',* FROM [SCH_CENTRA_ID].[FIELDS]
GO

