USE [CENTRA_ID]
GO

---$ Alter table sch_centra_id.TRANSACTIONAL_PROFILES
PRINT 'Alter table sch_centra_id.TRANSACTIONAL_PROFILES alter column [name]'
ALTER TABLE sch_centra_id.TRANSACTIONAL_PROFILES
    ALTER COLUMN [name] NVARCHAR(100) NOT NULL
GO


---$ Alter table sch_centra_id.USERDATA
PRINT 'Alter table sch_centra_id.USERDATA alter column CATALOG_AREA_ID'
ALTER TABLE sch_centra_id.USERDATA
    ALTER COLUMN CATALOG_AREA_ID BIGINT NOT NULL
GO

PRINT 'Alter table sch_centra_id.USERDATA alter column CATALOG_DEPARTMENT_ID'
ALTER TABLE sch_centra_id.USERDATA
    ALTER COLUMN CATALOG_DEPARTMENT_ID BIGINT NOT NULL
GO

---$ Create Index/PK: TRANSACTIONAL_PROFILES_NAME_UK, Table : sch_centra_id.TRANSACTIONAL_PROFILES
PRINT 'Add index : sch_centra_id.TRANSACTIONAL_PROFILES.TRANSACTIONAL_PROFILES_NAME_UK'
ALTER TABLE sch_centra_id.TRANSACTIONAL_PROFILES
        ADD CONSTRAINT TRANSACTIONAL_PROFILES_NAME_UK UNIQUE NONCLUSTERED(NAME)

