CREATE TABLE
    MGI_REPROCESO
    (
        GUID VARCHAR(50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
        FECHA_INGRESO DATETIME NOT NULL,
        ID_MENSAJE VARCHAR(50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
        ESTADO VARCHAR(16) COLLATE SQL_Latin1_General_CP1_CI_AS,
        USER_STORE VARCHAR(16) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
        MENSAJE_PETICION TEXT COLLATE SQL_Latin1_General_CP1_CI_AS,
        MENSAJE_RESPUESTA TEXT COLLATE SQL_Latin1_General_CP1_CI_AS,
        PRIORIDAD TINYINT NOT NULL,
        REINTENTO TINYINT NOT NULL,
        SOAP_ACTION VARCHAR(400) COLLATE SQL_Latin1_General_CP1_CI_AS,
        STATUS_COD_RESP VARCHAR(10) COLLATE SQL_Latin1_General_CP1_CI_AS,
        MENSAJE_PETICION_VALORES TEXT COLLATE SQL_Latin1_General_CP1_CI_AS,
        MENSAJE_RESPUESTA_VALORES TEXT COLLATE SQL_Latin1_General_CP1_CI_AS,
        ULTIMA_FECHA_REINTENTO DATETIME,
        HP_TICKET_NUMERO VARCHAR(50) COLLATE SQL_Latin1_General_CP1_CI_AS,
        HP_TICKET_CONTENIDO TEXT COLLATE SQL_Latin1_General_CP1_CI_AS,
        HP_TICKET_FECHA_RESPUESTA DATETIME,
        HP_TICKET_ESTADO VARCHAR(20) COLLATE SQL_Latin1_General_CP1_CI_AS,
        HP_TICKET_LOGS VARCHAR(2048) COLLATE SQL_Latin1_General_CP1_CI_AS,
        UUID_GI VARCHAR(50) COLLATE SQL_Latin1_General_CP1_CI_AS,
        CONSTRAINT MGI_REPROCESO_PK PRIMARY KEY (GUID)
    );
