USE [CENTRA_ID]
GO

DROP  VIEW sch_centra_id.USERDATA_VW 
GO

DROP VIEW sch_centra_id.TEMPLATE_PROFILES_VW
GO



SELECT 'ANTES' AS 'RFC_ C00018923',* FROM [SCH_CENTRA_ID].[GLOBAL_PARAMETERS]
GO
DELETE FROM  "sch_centra_id"."GLOBAL_PARAMETERS" WHERE CODE='DURTRA'
GO
SELECT 'DESPUES' AS 'RFC_ C00018923',* FROM [SCH_CENTRA_ID].[GLOBAL_PARAMETERS]
GO


SELECT 'ANTES' AS 'RFC_ C00018923',* FROM [SCH_CENTRA_ID].[MENUS]
GO
DELETE FROM SCH_CENTRA_ID.MENUS
GO
SELECT 'DESPUES' AS 'RFC_ C00018923',* FROM [SCH_CENTRA_ID].[MENUS]
GO

