USE [CENTRA_ID]
GO

CREATE OR ALTER VIEW sch_centra_id.USERDATA_VW AS
select 
ud.USERNAME USERNAME,
ud.EMPLOYEE_CODE CODIGO_EMPLEADO,
ud.WORKER_CODE CODIGO_TRABAJADOR,
ud.IDENTIFICATION IDENTIFICACION,
ud.EMPLOYEE_FIRST_SURNAME+' ' +ud.EMPLOYEE_SECOND_SURNAME APELLIDOS_EMPLEADO,
ud.EMPLOYEE_FIRST_NAME+' ' +ud.EMPLOYEE_SECOND_NAME NOMBRES_EMPLEADO,
ud.MOBILE CELULAR,
ud.DEPOSIT_ACCOUNT_NUMBER NUMERO_CUENTA_DEPOSITO,
ud.EMPLOYEE_INCOME_DATE FECHA_INGRESO,
ud.EMPLOYEE_DEPARTURE_DATE FECHA_SALIDA,
su.IDENTIFICATION IDENTIFICACION_SUPERVISOR,
su.EMPLOYEE_COMPLETE_NAME  NOMBRE_SUPERVISOR,
c.CODE CODIGO_COMPANIA,
c.BUSINESS_NAME NOMBRE_COMPANIA,
div.CODE CODIGO_DIVISION,
div.NAME NOMBRE_DIVISION,
are.CODE CODIGO_AREA,
are.NAME NOMBRE_AREA,
dto.CODE CODIGO_DEPARTAMENTO,
dto.NAME NOMBRE_DEPARTAMENTO,
car.CODE CODIGO_CARGO,
car.NAME NOMBRE_CARGO,
cc.CODE CODIGO_CENTRO_COSTO,
cc.NAME NOMBRE_CENTRO_COSTO,
ud.GROUPING_CODE CODIGO_AGRUPACION,
ud.HIERARCHICAL_LEVEL CODIGO_NIVEL_JERARQUICO,
tu.CODE TIPOUSUARIO,
stu.CODE SUBTIPO,
ud.EMPLOYEE_STATUS ESTADO_EMPLEADO,
ud.LOCATION_NAME NOMBRELOCALIDAD,
ud.MAIL CORREO_ELECTRONICO,
gp.ID ID_PERFIL_GLOBAL,
gp.CODE CODIGO_PERFIL_GLOBAL,
gp.NAME NOMBRE_PERFIL_GLOBAL,
ud.id ID_USUARIO
from SCH_CENTRA_ID.USERDATA ud
left join SCH_CENTRA_ID.USERDATA su on ud.USERDATA_SUPERVISOR_ID=su.id
left join SCH_CENTRA_ID.COMPANIES c on ud.COMPANY_ID=c.id
left join SCH_CENTRA_ID.CATALOGS div on ud.CATALOG_DIVISION_ID=div.id
left join SCH_CENTRA_ID.CATALOGS are on ud.CATALOG_AREA_ID=are.id
left join SCH_CENTRA_ID.CATALOGS dto on ud.CATALOG_DEPARTMENT_ID=dto.id
left join SCH_CENTRA_ID.CATALOGS car on ud.CATALOG_POSITION_ID=car.id
left join SCH_CENTRA_ID.COSTS_CENTERS cc on ud.COST_CENTER_ID=cc.id
left join SCH_CENTRA_ID.TYPE_USERS tu on ud.TYPE_USER_ID=tu.ID
left join SCH_CENTRA_ID.TYPE_USERS stu on ud.SUBTYPE_USER_ID=stu.ID
left join SCH_CENTRA_ID.GLOBAL_PROFILES gp on ud.GLOBAL_PROFILE_ID=gp.ID
where ud.EMPLOYEE_STATUS='ACTIVO' and
ud.VALID=1
GO

CREATE VIEW sch_centra_id.TEMPLATE_PROFILES_VW AS
SELECT 
tp.ID,
f.CODE FIELD_CODE,
f.NAME FIELD_NAME,
tp.FIELD_VALUE FIELD_VALUE,
tp.TRANSACTIONAL_PROFILE_ID,
ap.CODE APPLICATION_CODE,
tp.VALID
FROM SCH_CENTRA_ID.TEMPLATE_PROFILES tp
left join SCH_CENTRA_ID.FIELDS f on tp.FIELD_ID=f.ID
left join SCH_CENTRA_ID.TRANSACTIONAL_PROFILES tr on  tr.ID=tp.TRANSACTIONAL_PROFILE_ID
left join SCH_CENTRA_ID.APPLICATIONS ap on ap.id=tr.application_id
GO

CREATE VIEW sch_centra_id.TEMPLATE_PROFILES_MATRIX_VW AS
select 
tpmd.ID,
tpm.TRANSACTIONAL_PROFILE_ID,
m.CODE FIELD_CODE,
m.NAME FIELD_NAME,
md.CODE FIELD_DETAIL_CODE,
md.NAME FIELD_DETAIL_NAME,
tpmd.VALUE FIELD_DETAIL_VALUE,
ap.CODE APPLICATION_CODE,
tpmd.VALID
from SCH_CENTRA_ID.TEMPLATE_PROFILES_MATRICES tpm
join SCH_CENTRA_ID.TEMPLATE_PROFILES_MATRICES_GROUP tpmg on tpmg.TEMPLATE_PROFILE_MATRIX_ID=tpm.ID
join SCH_CENTRA_ID.TEMPLATE_PROFILES_MATRICES_DETAIL tpmd on tpmd.TEMPLATE_PROFILE_MATRIX_GROUP_ID=tpmg.ID
join SCH_CENTRA_ID.MATRICES_DETAIL md on tpmd.MATRIX_DETAIL_ID=md.ID
join SCH_CENTRA_ID.MATRICES m on tpm.MATRIX_ID=m.ID
join SCH_CENTRA_ID.TRANSACTIONAL_PROFILES tr on  tr.ID=tpm.TRANSACTIONAL_PROFILE_ID
join SCH_CENTRA_ID.APPLICATIONS ap on ap.id=tr.application_id
GO

