USE [CENTRA_ID]
GO

---$ Alter table sch_centra_id.APPLICATIONS
PRINT 'Alter table sch_centra_id.APPLICATIONS alter column code'
ALTER TABLE sch_centra_id.APPLICATIONS
    ALTER COLUMN code NVARCHAR(50) NOT NULL
GO


---$ Alter table sch_centra_id.APPLICATIONS_GROUP
PRINT 'Alter table sch_centra_id.APPLICATIONS_GROUP alter column CODE'
ALTER TABLE sch_centra_id.APPLICATIONS_GROUP
    ALTER COLUMN CODE NVARCHAR(50) NOT NULL
GO

PRINT 'Alter table sch_centra_id.APPLICATIONS_GROUP alter column ENDPOINT_TYPE'
ALTER TABLE sch_centra_id.APPLICATIONS_GROUP
    ALTER COLUMN ENDPOINT_TYPE NVARCHAR(50) NOT NULL
GO

IF NOT EXISTS(SELECT * FROM SYS.COLUMNS WHERE OBJECT_ID = OBJECT_ID(N'sch_centra_id.APPLICATIONS_GROUP') AND NAME = 'NUMBER_RETRIES')
BEGIN
    PRINT 'Add column : sch_centra_id.APPLICATIONS_GROUP.NUMBER_RETRIES'
    ALTER TABLE sch_centra_id.APPLICATIONS_GROUP
        ADD NUMBER_RETRIES INT NULL
END
GO

IF NOT EXISTS(SELECT * FROM SYS.COLUMNS WHERE OBJECT_ID = OBJECT_ID(N'sch_centra_id.APPLICATIONS_GROUP') AND NAME = 'TIME_BETWEEN_RETRIES')
BEGIN
    PRINT 'Add column : sch_centra_id.APPLICATIONS_GROUP.TIME_BETWEEN_RETRIES'
    ALTER TABLE sch_centra_id.APPLICATIONS_GROUP
        ADD TIME_BETWEEN_RETRIES INT NULL
END
GO

IF NOT EXISTS(SELECT * FROM SYS.COLUMNS WHERE OBJECT_ID = OBJECT_ID(N'sch_centra_id.APPLICATIONS_GROUP') AND NAME = 'ERRORS_NOT_REQUIRE_TICKET')
BEGIN
    PRINT 'Add column : sch_centra_id.APPLICATIONS_GROUP.ERRORS_NOT_REQUIRE_TICKET'
    ALTER TABLE sch_centra_id.APPLICATIONS_GROUP
        ADD ERRORS_NOT_REQUIRE_TICKET NVARCHAR(100) NULL
END
GO


---$ Alter table sch_centra_id.GLOBAL_PROFILES
PRINT 'Alter table sch_centra_id.GLOBAL_PROFILES alter column catalog_position_owner_id'
ALTER TABLE sch_centra_id.GLOBAL_PROFILES
    ALTER COLUMN catalog_position_owner_id BIGINT NULL
GO

PRINT 'Alter table sch_centra_id.GLOBAL_PROFILES alter column SCOPE_RULES_WHO'
ALTER TABLE sch_centra_id.GLOBAL_PROFILES
    ALTER COLUMN SCOPE_RULES_WHO NVARCHAR(max) NULL
GO

PRINT 'Alter table sch_centra_id.GLOBAL_PROFILES alter column SCOPE_RULES_THAT'
ALTER TABLE sch_centra_id.GLOBAL_PROFILES
    ALTER COLUMN SCOPE_RULES_THAT NVARCHAR(max) NULL
GO


---$ Alter table SCH_CENTRA_ID_AUDIT.LOG_PERFORMANCE
PRINT 'Alter table SCH_CENTRA_ID_AUDIT.LOG_PERFORMANCE alter column APP_CALLED'
ALTER TABLE SCH_CENTRA_ID_AUDIT.LOG_PERFORMANCE
    ALTER COLUMN APP_CALLED NVARCHAR(50) NOT NULL
GO


---$ Create table sch_centra_id.MENUS
IF OBJECT_ID(N'sch_centra_id.MENUS') IS NULL
BEGIN
    PRINT 'Create table sch_centra_id.MENUS'
    CREATE TABLE sch_centra_id.MENUS
    (
        [ID] BIGINT IDENTITY(1,1) NOT NULL,
        TITLE NVARCHAR(100) NOT NULL,
        TRANSLATE NVARCHAR(100) NOT NULL,
        [TYPE] NVARCHAR(10) NOT NULL,
        ICON NVARCHAR(20) NOT NULL,
        URL NVARCHAR(200) NOT NULL,
        APP NVARCHAR(20) NOT NULL,
        PERMISSION NVARCHAR(100) NOT NULL,
        VALID INT NOT NULL
    )
    END
GO


---$ Create table sch_centra_id.OPERATIONS_PROVISIONING
IF OBJECT_ID(N'sch_centra_id.OPERATIONS_PROVISIONING') IS NULL
BEGIN
    PRINT 'Create table sch_centra_id.OPERATIONS_PROVISIONING'
    CREATE TABLE sch_centra_id.OPERATIONS_PROVISIONING
    (
        [ID] BIGINT IDENTITY(1,1) NOT NULL,
        TRANSACTIONAL_IDENTITY_ID BIGINT NOT NULL,
        GLOBAL_PROFILE_ID BIGINT NOT NULL,
        USER_DATA_ID BIGINT NOT NULL,
        CREATED_DATE datetime NOT NULL,
        PROFILE_START_DATE datetime NOT NULL,
        PROFILE_END_DATE datetime NOT NULL,
        START_DATE datetime NOT NULL,
        END_DATE datetime NOT NULL,
        MODIFY_DATA INT NOT NULL,
        PROFILE_RECALCULATION INT NOT NULL,
        [STATUS] NVARCHAR(20) NOT NULL,
        VALID INT NOT NULL
    )
    END
GO


---$ Create table sch_centra_id.REST_USER_STORE_SCIM
IF OBJECT_ID(N'sch_centra_id.REST_USER_STORE_SCIM') IS NULL
BEGIN
    PRINT 'Create table sch_centra_id.REST_USER_STORE_SCIM'
    CREATE TABLE sch_centra_id.REST_USER_STORE_SCIM
    (
        [ID] BIGINT IDENTITY(1,1) NOT NULL,
        USERNAME NVARCHAR(25) NOT NULL,
        SCIM NVARCHAR(255) NOT NULL,
        [DOMAIN] NVARCHAR(255) NOT NULL,
        VALID INT NOT NULL
    )
    END
GO


---$ Create table sch_centra_id.TAKS_PROVISIONING
IF OBJECT_ID(N'sch_centra_id.TAKS_PROVISIONING') IS NULL
BEGIN
    PRINT 'Create table sch_centra_id.TAKS_PROVISIONING'
    CREATE TABLE sch_centra_id.TAKS_PROVISIONING
    (
        [ID] BIGINT IDENTITY(1,1) NOT NULL,
        OPERATION_PROVISIONING_ID BIGINT NOT NULL,
        TRANSACTIONAL_PROFILE_ID BIGINT NOT NULL,
        APPLICATION_ID BIGINT NOT NULL,
        PROVISIONING_DATE datetime NULL,
        PROVISIONING_STATUS NVARCHAR(20) NOT NULL,
        PROVISIONING_COMMENTS NVARCHAR(400) NULL,
        [STATUS] NVARCHAR(20) NOT NULL,
        [ACTION] NVARCHAR(20) NOT NULL,
        CREATION_DATE datetime NOT NULL,
        VALID INT NOT NULL,
        UUID NVARCHAR(100) NOT NULL,
        UUID_PARENT NVARCHAR(100) NULL,
        TICKET_NUMBER NVARCHAR(20) NULL,
        TICKET_DATE datetime NULL,
        TICKET_CONTENT NVARCHAR(1000) NULL,
        TICKET_ERROR NVARCHAR(1000) NULL,
        RETRY_NUMBER INT NULL,
        RETRY_LAST_DATE datetime NULL,
        [TYPE] NVARCHAR(3) NULL
    )
    END
GO


---$ Create table sch_centra_id.TAKS_PROVISIONING_HISTORY
IF OBJECT_ID(N'sch_centra_id.TAKS_PROVISIONING_HISTORY') IS NULL
BEGIN
    PRINT 'Create table sch_centra_id.TAKS_PROVISIONING_HISTORY'
    CREATE TABLE sch_centra_id.TAKS_PROVISIONING_HISTORY
    (
        [ID] BIGINT IDENTITY(1,1) NOT NULL,
        TASK_PROVISIONING_ID BIGINT NOT NULL,
        [STATUS] NVARCHAR(100) NOT NULL,
        CREATION_DATE datetime NOT NULL,
        VALID INT NOT NULL,
        RETRY_NUMBER INT NULL,
        RETRY_DATE datetime NULL
    )
    END
GO


---$ Alter table sch_centra_id.TRANSACTIONAL_IDENTITY
PRINT 'Alter table sch_centra_id.TRANSACTIONAL_IDENTITY alter column EMPLOYEE_START_DATE'
ALTER TABLE sch_centra_id.TRANSACTIONAL_IDENTITY
    ALTER COLUMN EMPLOYEE_START_DATE NVARCHAR(50) NULL
GO

PRINT 'Alter table sch_centra_id.TRANSACTIONAL_IDENTITY alter column EMPLOYEE_END_DATE'
ALTER TABLE sch_centra_id.TRANSACTIONAL_IDENTITY
    ALTER COLUMN EMPLOYEE_END_DATE NVARCHAR(50) NULL
GO


---$ Alter table sch_centra_id.TRANSACTIONAL_PROFILES
PRINT 'Alter table sch_centra_id.TRANSACTIONAL_PROFILES alter column code'
ALTER TABLE sch_centra_id.TRANSACTIONAL_PROFILES
    ALTER COLUMN code NVARCHAR(50) NOT NULL
GO


---$ Drop table SCH_CENTRA_ID.USER_ACTION_PROFILE_TRANSACTIONAL
IF OBJECT_ID(N'SCH_CENTRA_ID.USER_ACTION_PROFILE_TRANSACTIONAL') is not null
BEGIN
    PRINT 'Drop table SCH_CENTRA_ID.USER_ACTION_PROFILE_TRANSACTIONAL'
    DROP TABLE SCH_CENTRA_ID.USER_ACTION_PROFILE_TRANSACTIONAL
END
GO

---$ Drop table SCH_CENTRA_ID.USER_PROFILE_TRANSACTIONAL_HISTORY
IF OBJECT_ID(N'SCH_CENTRA_ID.USER_PROFILE_TRANSACTIONAL_HISTORY') is not null
BEGIN
    PRINT 'Drop table SCH_CENTRA_ID.USER_PROFILE_TRANSACTIONAL_HISTORY'
    DROP TABLE SCH_CENTRA_ID.USER_PROFILE_TRANSACTIONAL_HISTORY
END
GO

---$ Drop Constraint: FIELDS_TYPE_UK, Table: SCH_CENTRA_ID.FIELDS
IF OBJECT_ID(N'FIELDS_TYPE_UK') IS NOT NULL
BEGIN
    PRINT 'Drop Constraint : FIELDS_TYPE_UK'
    ALTER TABLE SCH_CENTRA_ID.FIELDS
        DROP CONSTRAINT FIELDS_TYPE_UK
END

GO

---$ Drop Constraint: global_profiles_status_uk, Table: SCH_CENTRA_ID.GLOBAL_PROFILES
IF OBJECT_ID(N'global_profiles_status_uk') IS NOT NULL
BEGIN
    PRINT 'Drop Constraint : global_profiles_status_uk'
    ALTER TABLE SCH_CENTRA_ID.GLOBAL_PROFILES
        DROP CONSTRAINT global_profiles_status_uk
END

GO

---$ Drop Index/PK: GLOBAL_PROFILES_CODE_UK, Table : sch_centra_id.GLOBAL_PROFILES
IF OBJECT_ID(N'sch_centra_id.GLOBAL_PROFILES_CODE_UK') IS NOT NULL
BEGIN
    PRINT 'Drop constraint GLOBAL_PROFILES_CODE_UK'
    ALTER TABLE sch_centra_id.GLOBAL_PROFILES
        DROP CONSTRAINT GLOBAL_PROFILES_CODE_UK
END
GO

---$ Drop Index/PK: GLOBAL_PROFILES_NAME_UK, Table : sch_centra_id.GLOBAL_PROFILES
IF OBJECT_ID(N'sch_centra_id.GLOBAL_PROFILES_NAME_UK') IS NOT NULL
BEGIN
    PRINT 'Drop constraint GLOBAL_PROFILES_NAME_UK'
    ALTER TABLE sch_centra_id.GLOBAL_PROFILES
        DROP CONSTRAINT GLOBAL_PROFILES_NAME_UK
END
GO

---$ Create Index/PK: GLOBAL_PROFILES_UK, Table : sch_centra_id.GLOBAL_PROFILES
IF OBJECT_ID(N'sch_centra_id.GLOBAL_PROFILES_UK') IS NULL
BEGIN
    PRINT 'Add index : sch_centra_id.GLOBAL_PROFILES.GLOBAL_PROFILES_UK'
    ALTER TABLE sch_centra_id.GLOBAL_PROFILES
        ADD CONSTRAINT GLOBAL_PROFILES_UK UNIQUE NONCLUSTERED(code, name)
END
GO

---$ Create Index/PK: MENUS_PK, Table : sch_centra_id.MENUS
IF OBJECT_ID(N'sch_centra_id.MENUS_PK') IS NULL
BEGIN
    PRINT 'Add PK constraint : MENUS_PK'
    ALTER TABLE sch_centra_id.MENUS
        ADD CONSTRAINT MENUS_PK PRIMARY KEY CLUSTERED(ID)
END
GO

---$ Create Index/PK: USER_PROFILE_TRANSACTIONAL_HISTORY_PK, Table : sch_centra_id.OPERATIONS_PROVISIONING
IF OBJECT_ID(N'sch_centra_id.USER_PROFILE_TRANSACTIONAL_HISTORY_PK') IS NULL
BEGIN
    PRINT 'Add PK constraint : USER_PROFILE_TRANSACTIONAL_HISTORY_PK'
    ALTER TABLE sch_centra_id.OPERATIONS_PROVISIONING
        ADD CONSTRAINT USER_PROFILE_TRANSACTIONAL_HISTORY_PK PRIMARY KEY CLUSTERED(ID)
END
GO

---$ Create Index/PK: REST_USER_STORE_SCIM_PK, Table : sch_centra_id.REST_USER_STORE_SCIM
IF OBJECT_ID(N'sch_centra_id.REST_USER_STORE_SCIM_PK') IS NULL
BEGIN
    PRINT 'Add PK constraint : REST_USER_STORE_SCIM_PK'
    ALTER TABLE sch_centra_id.REST_USER_STORE_SCIM
        ADD CONSTRAINT REST_USER_STORE_SCIM_PK PRIMARY KEY CLUSTERED(ID)
END
GO

---$ Create Index/PK: USER_ACTION_PROFILE_TRANSACTIONAL_PK, Table : sch_centra_id.TAKS_PROVISIONING
IF OBJECT_ID(N'sch_centra_id.USER_ACTION_PROFILE_TRANSACTIONAL_PK') IS NULL
BEGIN
    PRINT 'Add PK constraint : USER_ACTION_PROFILE_TRANSACTIONAL_PK'
    ALTER TABLE sch_centra_id.TAKS_PROVISIONING
        ADD CONSTRAINT USER_ACTION_PROFILE_TRANSACTIONAL_PK PRIMARY KEY CLUSTERED(ID)
END
GO

---$ Create Index/PK: TAKS_PROVISIONING_HISTORY_PK, Table : sch_centra_id.TAKS_PROVISIONING_HISTORY
IF OBJECT_ID(N'sch_centra_id.TAKS_PROVISIONING_HISTORY_PK') IS NULL
BEGIN
    PRINT 'Add PK constraint : TAKS_PROVISIONING_HISTORY_PK'
    ALTER TABLE sch_centra_id.TAKS_PROVISIONING_HISTORY
        ADD CONSTRAINT TAKS_PROVISIONING_HISTORY_PK PRIMARY KEY CLUSTERED(ID)
END
GO
