USE [CENTRA_ID]
GO

---$ Drop Index/PK: GLOBAL_PROFILES_UK, Table : sch_centra_id.GLOBAL_PROFILES
IF OBJECT_ID(N'sch_centra_id.GLOBAL_PROFILES_UK') IS NOT NULL
BEGIN
    PRINT 'Drop constraint GLOBAL_PROFILES_UK'
    ALTER TABLE sch_centra_id.GLOBAL_PROFILES
        DROP CONSTRAINT GLOBAL_PROFILES_UK
END
GO

---$ Drop Index/PK: MENUS_PK, Table : sch_centra_id.MENUS
IF OBJECT_ID(N'sch_centra_id.MENUS_PK') IS NOT NULL
BEGIN
    PRINT 'Drop constraint MENUS_PK'
    ALTER TABLE sch_centra_id.MENUS
        DROP CONSTRAINT MENUS_PK
END
GO

---$ Drop Index/PK: USER_PROFILE_TRANSACTIONAL_HISTORY_PK, Table : sch_centra_id.OPERATIONS_PROVISIONING
IF OBJECT_ID(N'sch_centra_id.USER_PROFILE_TRANSACTIONAL_HISTORY_PK') IS NOT NULL
BEGIN
    PRINT 'Drop constraint USER_PROFILE_TRANSACTIONAL_HISTORY_PK'
    ALTER TABLE sch_centra_id.OPERATIONS_PROVISIONING
        DROP CONSTRAINT USER_PROFILE_TRANSACTIONAL_HISTORY_PK
END
GO

---$ Drop Index/PK: REST_USER_STORE_SCIM_PK, Table : sch_centra_id.REST_USER_STORE_SCIM
IF OBJECT_ID(N'sch_centra_id.REST_USER_STORE_SCIM_PK') IS NOT NULL
BEGIN
    PRINT 'Drop constraint REST_USER_STORE_SCIM_PK'
    ALTER TABLE sch_centra_id.REST_USER_STORE_SCIM
        DROP CONSTRAINT REST_USER_STORE_SCIM_PK
END
GO

---$ Drop Index/PK: USER_ACTION_PROFILE_TRANSACTIONAL_PK, Table : sch_centra_id.TAKS_PROVISIONING
IF OBJECT_ID(N'sch_centra_id.USER_ACTION_PROFILE_TRANSACTIONAL_PK') IS NOT NULL
BEGIN
    PRINT 'Drop constraint USER_ACTION_PROFILE_TRANSACTIONAL_PK'
    ALTER TABLE sch_centra_id.TAKS_PROVISIONING
        DROP CONSTRAINT USER_ACTION_PROFILE_TRANSACTIONAL_PK
END
GO

---$ Drop Index/PK: TAKS_PROVISIONING_HISTORY_PK, Table : sch_centra_id.TAKS_PROVISIONING_HISTORY
IF OBJECT_ID(N'sch_centra_id.TAKS_PROVISIONING_HISTORY_PK') IS NOT NULL
BEGIN
    PRINT 'Drop constraint TAKS_PROVISIONING_HISTORY_PK'
    ALTER TABLE sch_centra_id.TAKS_PROVISIONING_HISTORY
        DROP CONSTRAINT TAKS_PROVISIONING_HISTORY_PK
END
GO

---$ Alter table sch_centra_id.APPLICATIONS
PRINT 'Alter table sch_centra_id.APPLICATIONS alter column code'
ALTER TABLE sch_centra_id.APPLICATIONS
    ALTER COLUMN code NVARCHAR(20) NOT NULL
GO


---$ Alter table sch_centra_id.APPLICATIONS_GROUP
PRINT 'Alter table sch_centra_id.APPLICATIONS_GROUP alter column CODE'
ALTER TABLE sch_centra_id.APPLICATIONS_GROUP
    ALTER COLUMN CODE NVARCHAR(20) NOT NULL
GO

PRINT 'Alter table sch_centra_id.APPLICATIONS_GROUP alter column ENDPOINT_TYPE'
ALTER TABLE sch_centra_id.APPLICATIONS_GROUP
    ALTER COLUMN ENDPOINT_TYPE NVARCHAR(20) NOT NULL
GO

IF EXISTS(SELECT * FROM SYS.COLUMNS WHERE OBJECT_ID = OBJECT_ID(N'sch_centra_id.APPLICATIONS_GROUP') AND NAME = 'NUMBER_RETRIES')
BEGIN
    PRINT 'Drop column : sch_centra_id.APPLICATIONS_GROUP.NUMBER_RETRIES'
    ALTER TABLE sch_centra_id.APPLICATIONS_GROUP
        DROP COLUMN NUMBER_RETRIES
END
GO

IF EXISTS(SELECT * FROM SYS.COLUMNS WHERE OBJECT_ID = OBJECT_ID(N'sch_centra_id.APPLICATIONS_GROUP') AND NAME = 'TIME_BETWEEN_RETRIES')
BEGIN
    PRINT 'Drop column : sch_centra_id.APPLICATIONS_GROUP.TIME_BETWEEN_RETRIES'
    ALTER TABLE sch_centra_id.APPLICATIONS_GROUP
        DROP COLUMN TIME_BETWEEN_RETRIES
END
GO

IF EXISTS(SELECT * FROM SYS.COLUMNS WHERE OBJECT_ID = OBJECT_ID(N'sch_centra_id.APPLICATIONS_GROUP') AND NAME = 'ERRORS_NOT_REQUIRE_TICKET')
BEGIN
    PRINT 'Drop column : sch_centra_id.APPLICATIONS_GROUP.ERRORS_NOT_REQUIRE_TICKET'
    ALTER TABLE sch_centra_id.APPLICATIONS_GROUP
        DROP COLUMN ERRORS_NOT_REQUIRE_TICKET
END
GO


---$ Alter table sch_centra_id.GLOBAL_PROFILES
PRINT 'Alter table sch_centra_id.GLOBAL_PROFILES alter column catalog_position_owner_id'
ALTER TABLE sch_centra_id.GLOBAL_PROFILES
    ALTER COLUMN catalog_position_owner_id BIGINT NOT NULL
GO

PRINT 'Alter table sch_centra_id.GLOBAL_PROFILES alter column SCOPE_RULES_WHO'
ALTER TABLE sch_centra_id.GLOBAL_PROFILES
    ALTER COLUMN SCOPE_RULES_WHO NVARCHAR(400) NULL
GO

PRINT 'Alter table sch_centra_id.GLOBAL_PROFILES alter column SCOPE_RULES_THAT'
ALTER TABLE sch_centra_id.GLOBAL_PROFILES
    ALTER COLUMN SCOPE_RULES_THAT NVARCHAR(400) NULL
GO


---$ Alter table SCH_CENTRA_ID_AUDIT.LOG_PERFORMANCE
PRINT 'Alter table SCH_CENTRA_ID_AUDIT.LOG_PERFORMANCE alter column APP_CALLED'
ALTER TABLE SCH_CENTRA_ID_AUDIT.LOG_PERFORMANCE
    ALTER COLUMN APP_CALLED NVARCHAR(500) NOT NULL
GO


---$ Drop table sch_centra_id.MENUS
IF OBJECT_ID(N'sch_centra_id.MENUS') is not null
BEGIN
    PRINT 'Drop table sch_centra_id.MENUS'
    DROP TABLE sch_centra_id.MENUS
END
GO

---$ Drop table sch_centra_id.OPERATIONS_PROVISIONING
IF OBJECT_ID(N'sch_centra_id.OPERATIONS_PROVISIONING') is not null
BEGIN
    PRINT 'Drop table sch_centra_id.OPERATIONS_PROVISIONING'
    DROP TABLE sch_centra_id.OPERATIONS_PROVISIONING
END
GO

---$ Drop table sch_centra_id.REST_USER_STORE_SCIM
IF OBJECT_ID(N'sch_centra_id.REST_USER_STORE_SCIM') is not null
BEGIN
    PRINT 'Drop table sch_centra_id.REST_USER_STORE_SCIM'
    DROP TABLE sch_centra_id.REST_USER_STORE_SCIM
END
GO

---$ Drop table sch_centra_id.TAKS_PROVISIONING
IF OBJECT_ID(N'sch_centra_id.TAKS_PROVISIONING') is not null
BEGIN
    PRINT 'Drop table sch_centra_id.TAKS_PROVISIONING'
    DROP TABLE sch_centra_id.TAKS_PROVISIONING
END
GO

---$ Drop table sch_centra_id.TAKS_PROVISIONING_HISTORY
IF OBJECT_ID(N'sch_centra_id.TAKS_PROVISIONING_HISTORY') is not null
BEGIN
    PRINT 'Drop table sch_centra_id.TAKS_PROVISIONING_HISTORY'
    DROP TABLE sch_centra_id.TAKS_PROVISIONING_HISTORY
END
GO

---$ Alter table sch_centra_id.TRANSACTIONAL_IDENTITY
PRINT 'Alter table sch_centra_id.TRANSACTIONAL_IDENTITY alter column EMPLOYEE_START_DATE'
ALTER TABLE sch_centra_id.TRANSACTIONAL_IDENTITY
    ALTER COLUMN EMPLOYEE_START_DATE NVARCHAR(20) NULL
GO

PRINT 'Alter table sch_centra_id.TRANSACTIONAL_IDENTITY alter column EMPLOYEE_END_DATE'
ALTER TABLE sch_centra_id.TRANSACTIONAL_IDENTITY
    ALTER COLUMN EMPLOYEE_END_DATE NVARCHAR(20) NULL
GO


---$ Alter table sch_centra_id.TRANSACTIONAL_PROFILES
PRINT 'Alter table sch_centra_id.TRANSACTIONAL_PROFILES alter column code'
ALTER TABLE sch_centra_id.TRANSACTIONAL_PROFILES
    ALTER COLUMN code NVARCHAR(20) NOT NULL
GO


---$ Create table SCH_CENTRA_ID.USER_ACTION_PROFILE_TRANSACTIONAL
IF OBJECT_ID(N'SCH_CENTRA_ID.USER_ACTION_PROFILE_TRANSACTIONAL') IS NULL
BEGIN
    PRINT 'Create table SCH_CENTRA_ID.USER_ACTION_PROFILE_TRANSACTIONAL'
    CREATE TABLE SCH_CENTRA_ID.USER_ACTION_PROFILE_TRANSACTIONAL
    (
        [ID] BIGINT IDENTITY(1,1) NOT NULL,
        USER_PROFILE_TRANSACTIONAL_HISTORY_ID BIGINT NOT NULL,
        TRANSACTIONAL_PROFILE_ID BIGINT NOT NULL,
        APPLICATION_ID BIGINT NOT NULL,
        PROVISIONING_DATE datetime NOT NULL,
        PROVISIONING_STATUS NVARCHAR(20) NOT NULL,
        PROVISIONING_COMMENTS NVARCHAR(400) NOT NULL,
        [STATUS] NVARCHAR(20) NOT NULL,
        [ACTION] NVARCHAR(20) NOT NULL,
        CREATED_DATE datetime NOT NULL,
        VALID INT NOT NULL
    )
    END
GO


---$ Create table SCH_CENTRA_ID.USER_PROFILE_TRANSACTIONAL_HISTORY
IF OBJECT_ID(N'SCH_CENTRA_ID.USER_PROFILE_TRANSACTIONAL_HISTORY') IS NULL
BEGIN
    PRINT 'Create table SCH_CENTRA_ID.USER_PROFILE_TRANSACTIONAL_HISTORY'
    CREATE TABLE SCH_CENTRA_ID.USER_PROFILE_TRANSACTIONAL_HISTORY
    (
        [ID] BIGINT IDENTITY(1,1) NOT NULL,
        TRANSACTIONAL_IDENTITY_ID BIGINT NOT NULL,
        GLOBAL_PROFILE_ID BIGINT NOT NULL,
        USERDATA_ID BIGINT NOT NULL,
        CREATED_DATE datetime NOT NULL,
        PROFILE_START_DATE datetime NOT NULL,
        PROFILE_END_DATE datetime NOT NULL,
        START_DATE datetime NOT NULL,
        END_DATE datetime NOT NULL,
        MODIFY_DATA INT NOT NULL,
        PROFILE_RECALCULATION INT NOT NULL,
        [STATUS] NVARCHAR(20) NOT NULL,
        VALID INT NOT NULL
    )
    END
GO


---$ Create Constraint: FIELDS_TYPE_UK, Table: SCH_CENTRA_ID.FIELDS
IF OBJECT_ID(N'SCH_CENTRA_ID.FIELDS_TYPE_UK') IS NULL
BEGIN
    PRINT 'Add Check Constraint : FIELDS_TYPE_UK'
    ALTER TABLE SCH_CENTRA_ID.FIELDS ADD CONSTRAINT FIELDS_TYPE_UK CHECK ([TYPE]='FECHA' OR [TYPE]='NUMERICO' OR [TYPE]='TEXTO')
END
GO

---$ Create Constraint: global_profiles_status_uk, Table: SCH_CENTRA_ID.GLOBAL_PROFILES
IF OBJECT_ID(N'SCH_CENTRA_ID.global_profiles_status_uk') IS NULL
BEGIN
    PRINT 'Add Check Constraint : global_profiles_status_uk'
    ALTER TABLE SCH_CENTRA_ID.GLOBAL_PROFILES ADD CONSTRAINT global_profiles_status_uk CHECK ([status]='APROBADO' OR [status]='RECHAZADO' OR [status]='INACTIVO' OR [status]='ELIMINADO' OR [status]='ACTIVO' OR [status]='REGISTRADO')
END
GO

---$ Create Index/PK: GLOBAL_PROFILES_CODE_UK, Table : sch_centra_id.GLOBAL_PROFILES
IF OBJECT_ID(N'sch_centra_id.GLOBAL_PROFILES_CODE_UK') IS NULL
BEGIN
    PRINT 'Add index : sch_centra_id.GLOBAL_PROFILES.GLOBAL_PROFILES_CODE_UK'
    ALTER TABLE sch_centra_id.GLOBAL_PROFILES
        ADD CONSTRAINT GLOBAL_PROFILES_CODE_UK UNIQUE NONCLUSTERED(CODE)
END
GO

---$ Create Index/PK: GLOBAL_PROFILES_NAME_UK, Table : sch_centra_id.GLOBAL_PROFILES
IF OBJECT_ID(N'sch_centra_id.GLOBAL_PROFILES_NAME_UK') IS NULL
BEGIN
    PRINT 'Add index : sch_centra_id.GLOBAL_PROFILES.GLOBAL_PROFILES_NAME_UK'
    ALTER TABLE sch_centra_id.GLOBAL_PROFILES
        ADD CONSTRAINT GLOBAL_PROFILES_NAME_UK UNIQUE NONCLUSTERED(NAME)
END
GO

---$ Create Index/PK: USER_ACTION_PROFILE_TRANSACTIONAL_PK, Table : SCH_CENTRA_ID.USER_ACTION_PROFILE_TRANSACTIONAL
IF OBJECT_ID(N'SCH_CENTRA_ID.USER_ACTION_PROFILE_TRANSACTIONAL_PK') IS NULL
BEGIN
    PRINT 'Add PK constraint : USER_ACTION_PROFILE_TRANSACTIONAL_PK'
    ALTER TABLE SCH_CENTRA_ID.USER_ACTION_PROFILE_TRANSACTIONAL
        ADD CONSTRAINT USER_ACTION_PROFILE_TRANSACTIONAL_PK PRIMARY KEY CLUSTERED(ID)
END
GO

---$ Create Index/PK: USER_PROFILE_TRANSACTIONAL_HISTORY_PK, Table : SCH_CENTRA_ID.USER_PROFILE_TRANSACTIONAL_HISTORY
IF OBJECT_ID(N'SCH_CENTRA_ID.USER_PROFILE_TRANSACTIONAL_HISTORY_PK') IS NULL
BEGIN
    PRINT 'Add PK constraint : USER_PROFILE_TRANSACTIONAL_HISTORY_PK'
    ALTER TABLE SCH_CENTRA_ID.USER_PROFILE_TRANSACTIONAL_HISTORY
        ADD CONSTRAINT USER_PROFILE_TRANSACTIONAL_HISTORY_PK PRIMARY KEY CLUSTERED(ID)
END
GO

