USE [CENTRA_ID]
GO

IF NOT EXISTS(SELECT * FROM SYS.COLUMNS WHERE OBJECT_ID = OBJECT_ID(N'sch_centra_id.TAKS_PROVISIONING') AND NAME = 'DATA_INPUT_QUEUE')
BEGIN
   ALTER TABLE  "SCH_CENTRA_ID"."TAKS_PROVISIONING" ADD DATA_INPUT_QUEUE text
END 
GO
IF NOT EXISTS(SELECT * FROM SYS.COLUMNS WHERE OBJECT_ID = OBJECT_ID(N'sch_centra_id.TAKS_PROVISIONING') AND NAME = 'DATA_INPUT_PROVISIONING')
BEGIN
   ALTER TABLE  "SCH_CENTRA_ID"."TAKS_PROVISIONING" ADD DATA_INPUT_PROVISIONING text
END
GO

DROP VIEW SCH_CENTRA_ID.TRANSACTIONAL_PROFILES_VW
GO
CREATE VIEW SCH_CENTRA_ID.TRANSACTIONAL_PROFILES_VW (GLOBAL_PROFILE_ID, GLOBAL_PROFILE_CODE, GLOBAL_PROFILE_NAME, GLOBAL_PROFILE_IS_BIRTH, ID, TRANSACTIONAL_PROFILE_CODE, TRANSACTIONAL_PROFILE_NAME, TRANSACTIONAL_PROFILE_COMMENTS, TRANSACTIONAL_PROFILE_CATALOG_RISK_LEVEL_ID, TRANSACTIONAL_PROFILE_APPLICATION_ID, APPLICATION_CODE, APPLICATION_NAME, APPLICATION_AUTOMATIC_PROVISION, VALID, FILTER, APPLICATION_ID, APPLICATION_GROUP_ID, APPLICATION_GROUP_CODE, APPLICATION_GROUP_NAME) AS 
 select
gp.id GLOBAL_PROFILE_ID,
gp.code GLOBAL_PROFILE_CODE,
gp.name GLOBAL_PROFILE_NAME,
gp.is_birth GLOBAL_PROFILE_IS_BIRTH,
tp.id ID,
tp.code TRANSACTIONAL_PROFILE_CODE,
tp.name TRANSACTIONAL_PROFILE_NAME,
tp.comments TRANSACTIONAL_PROFILE_COMMENTS,
tp.catalog_risk_level_id TRANSACTIONAL_PROFILE_CATALOG_RISK_LEVEL_ID,
tp.application_id TRANSACTIONAL_PROFILE_APPLICATION_ID,
a.code APPLICATION_CODE,
a.name APPLICATION_NAME,
a.automatic_provision APPLICATION_AUTOMATIC_PROVISION,
gtp.valid VALID,
tp.filter FILTER,
a.ID APPLICATION_ID,
ag.ID APPLICATION_GROUP_ID,
ag.CODE APPLICATION_GROUP_CODE,
ag.NAME APPLICATION_GROUP_NAME
from sch_centra_id.TRANSACTIONAL_PROFILES tp
left join sch_centra_id.GLOBAL_TRANSACTIONAL_PROFILES gtp on gtp.TRANSACTIONAL_PROFILE_ID=tp.id
left join sch_centra_id.GLOBAL_PROFILES gp on gtp.GLOBAL_PROFILE_ID=gp.id
left join sch_centra_id.APPLICATIONS a on a.id=tp.application_id
left join SCH_CENTRA_ID.APPLICATIONS_GROUP ag on a.APPLICATION_GROUP_ID=ag.ID
GO

ALTER TABLE "SCH_CENTRA_ID"."TRANSACTIONAL_IDENTITY" ALTER COLUMN "ORIGEN" nvarchar(100) NULL
GO


DROP VIEW SCH_CENTRA_ID.USERDATA_REPORT_VW
GO
CREATE VIEW SCH_CENTRA_ID.USERDATA_REPORT_VW (ID, VALID, USERDATA_USERNAME, USERDATA_IDENTIFICATION, USERDATA_NAME, USERDATA_EMPLOYEE_CODE, USERDATA_TYPE_USER, USERDATA_SUBTYPE_USER, USERDATA_MOBILE, USERDATA_MAIL, USERDATA_STATUS, USERDATA_DATE_CREATION, USERDATA_DATE_DELETION, USERDATA_DATE_START, USERDATE_DATE_END, GLOBAL_PROFILE_CODE, GLOBAL_PROFILE_NAME, COMPANY_NAME, DIVISION_NAME, AREA_NAME, DEPARTMENT_NAME, POSITION_NAME, COST_CENTER_CODE, COST_CENTER_NAME, SUPERVISOR_IDENTIFICACION, SUPERVISOR_NAME) AS 
SELECT 
UD.ID ID,
1 VALID,
UD.USERNAME USERDATA_USERNAME,
UD.IDENTIFICATION USERDATA_IDENTIFICATION,
UD.EMPLOYEE_COMPLETE_NAME USERDATA_NAME,
UD.EMPLOYEE_CODE USERDATA_EMPLOYEE_CODE,
TU.NAME USERDATA_TYPE_USER,
STU.NAME USERDATA_SUBTYPE_USER,
UD.MOBILE USERDATA_MOBILE,
UD.MAIL USERDATA_MAIL,
UD.EMPLOYEE_STATUS USERDATA_STATUS,
UD.EFFECTIVE_DATE USERDATA_DATE_CREATION,
UD.ENDING_WORK_DATE USERDATA_DATE_DELETION,
UD.EMPLOYEE_INCOME_DATE USERDATA_DATE_START,
UD.EMPLOYEE_DEPARTURE_DATE USERDATE_DATE_END,
GP.CODE GLOBAL_PROFILE_CODE,
GP.NAME GLOBAL_PROFILE_NAME,
C.BUSINESS_NAME COMPANY_NAME,
DIVISION.NAME DIVISION_NAME,
AREA.NAME AREA_NAME,
DEPARTMENT.NAME DEPARTMENT_NAME,
POSITION.NAME POSITION_NAME,
CC.CODE COST_CENTER_CODE,
CC.NAME COST_CENTER_NAME,
SUPER.IDENTIFICATION SUPERVISOR_IDENTIFICACION,
SUPER.EMPLOYEE_COMPLETE_NAME SUPERVISOR_NAME
FROM SCH_CENTRA_ID.USERDATA UD
LEFT JOIN SCH_CENTRA_ID.GLOBAL_PROFILES GP ON UD.GLOBAL_PROFILE_ID = GP.ID
LEFT JOIN SCH_CENTRA_ID.TYPE_USERS TU ON TU.ID =UD.TYPE_USER_ID
LEFT JOIN SCH_CENTRA_ID.TYPE_USERS STU ON STU.ID =UD.SUBTYPE_USER_ID
LEFT JOIN SCH_CENTRA_ID.COMPANIES C ON C.ID = UD.COMPANY_ID
LEFT JOIN SCH_CENTRA_ID.CATALOGS DIVISION ON DIVISION.ID =UD.CATALOG_DIVISION_ID
LEFT JOIN SCH_CENTRA_ID.CATALOGS AREA ON AREA.ID =UD.CATALOG_AREA_ID
LEFT JOIN SCH_CENTRA_ID.CATALOGS DEPARTMENT ON DEPARTMENT.ID =UD.CATALOG_DEPARTMENT_ID
LEFT JOIN SCH_CENTRA_ID.CATALOGS POSITION ON POSITION.ID =UD.CATALOG_POSITION_ID
LEFT JOIN SCH_CENTRA_ID.COSTS_CENTERS CC ON CC.ID = UD.COST_CENTER_ID
LEFT JOIN SCH_CENTRA_ID.USERDATA SUPER ON UD.USERDATA_SUPERVISOR_ID = SUPER.ID
GO



DROP VIEW SCH_CENTRA_ID.TRANSACTIONAL_PROFILES_REPORT_VW
GO
CREATE VIEW SCH_CENTRA_ID.TRANSACTIONAL_PROFILES_REPORT_VW (ID, VALID, TRANSACTIONAL_PROFILE_CODE, TRANSACTIONAL_PROFILE_NAME, APPLICATION_CODE, APPLICATION_NAME, APPLICATION_AUTOMATIC, RISK_LEVEL, COMMENTS, FIELD_NAME, FIELD_VALUE, STATUS) AS 
SELECT 
TP.ID ID,
1 VALID,
TP.CODE TRANSACTIONAL_PROFILE_CODE, 
TP.NAME TRANSACTIONAL_PROFILE_NAME,
A.CODE APPLICATION_CODE,
A.NAME APPLICATION_NAME,
A.AUTOMATIC_PROVISION APPLICATION_AUTOMATIC,
C_NIVREGI.NAME RISK_LEVEL,
TP.COMMENTS COMMENTS,
F.NAME FIELD_NAME,
TR.FIELD_VALUE FIELD_VALUE,
CASE TP.VALID WHEN 1 THEN 'ACTIVO' ELSE 'ELIMINADO'END STATUS
FROM SCH_CENTRA_ID.TRANSACTIONAL_PROFILES TP 
LEFT JOIN SCH_CENTRA_ID.APPLICATIONS A ON TP.APPLICATION_ID = A.ID
LEFT JOIN SCH_CENTRA_ID.APPLICATIONS_GROUP AG ON A.APPLICATION_GROUP_ID=AG.ID
LEFT JOIN SCH_CENTRA_ID.TEMPLATE_PROFILES TR ON TR.TRANSACTIONAL_PROFILE_ID = TP.ID
LEFT JOIN SCH_CENTRA_ID.FIELDS F ON F.ID = TR.FIELD_ID
LEFT JOIN SCH_CENTRA_ID.CATALOGS C_NIVREGI ON TP.CATALOG_RISK_LEVEL_ID=C_NIVREGI.ID
GO

DROP VIEW SCH_CENTRA_ID.GLOBAL_PROFILES_REPORT_VW
GO
CREATE VIEW SCH_CENTRA_ID.GLOBAL_PROFILES_REPORT_VW (ID, VALID, GLOBAL_PROFILE_CODE, GLOBAL_PROFILE_NAME, GLOBAL_PROFILE_IS_BIRTH, GLOBAL_PROFILE_TICKET_NUMBER, GLOBAL_PROFILE_USER_CREATION, GLOBAL_PROFILE_DATE_CREATION, GLOBAL_PROFILE_USER_APPROVAL, GLOBAL_PROFILE_DATE_APPROVAL, GLOBAL_PROFILE_OBSERVATION, GLOBAL_PROFILE_STATUS, GLOBAL_PROFILE_SCOPE_RULES_WHO, GLOBAL_PROFILE_SCOPE_RULES_THAT) AS 
SELECT 
GP.ID AS ID,
1 VALID,
GP.CODE GLOBAL_PROFILE_CODE,
GP.NAME GLOBAL_PROFILE_NAME,
GP.IS_BIRTH GLOBAL_PROFILE_IS_BIRTH,
GP.ASSOCIATED_TICKET_NUMBER GLOBAL_PROFILE_TICKET_NUMBER,
GP.EMPLOYEE_CODE_OWNER GLOBAL_PROFILE_USER_CREATION,
GP.CREATED_DATE GLOBAL_PROFILE_DATE_CREATION,
GP.EMPLOYEE_CODE_APPROVAL GLOBAL_PROFILE_USER_APPROVAL,
GP.APPROVAL_DATE GLOBAL_PROFILE_DATE_APPROVAL,
GP.OBSERVATION AS GLOBAL_PROFILE_OBSERVATION,
CASE GP.VALID WHEN  1 THEN GP.STATUS ELSE 'ELIMINADO' END  GLOBAL_PROFILE_STATUS,
GP.SCOPE_RULES_WHO  GLOBAL_PROFILE_SCOPE_RULES_WHO,
GP.SCOPE_RULES_THAT GLOBAL_PROFILE_SCOPE_RULES_THAT
FROM SCH_CENTRA_ID.GLOBAL_PROFILES GP
GO



DROP VIEW SCH_CENTRA_ID.DEFAULT_PROFILES_REPORT_VW
GO
CREATE VIEW SCH_CENTRA_ID.DEFAULT_PROFILES_REPORT_VW (ID, VALID, GLOBAL_PROFILE_CODE, GLOBAL_PROFILE_NAME, DEFAULT_PROFILE_COMPANY_CODE, DEFAULT_PROFILE_DIVISION_CODE, DEFAULT_PROFILE_AREA_CODE, DEFAULT_PROFILE_DEPARTMENT_CODE, DEFAULT_PROFILE_POSITION_NAME, GLOBAL_PROFILE_STATUS,DEFAULT_PROFILE_COMPANY_NAME, DEFAULT_PROFILE_DIVISION_NAME, DEFAULT_PROFILE_AREA_NAME, DEFAULT_PROFILE_DEPARTMENT_NAME) AS 
SELECT 
DF.ID ID,
1 VALID,
GP.CODE GLOBAL_PROFILE_CODE,
GP.NAME GLOBAL_PROFILE_NAME,
DF.CODE_COMPANY DEFAULT_PROFILE_COMPANY_CODE,
DF.CODE_DIVISION DEFAULT_PROFILE_DIVISION_CODE,
DF.CODE_AREA DEFAULT_PROFILE_AREA_CODE,
DF.CODE_DEPARTMENT DEFAULT_PROFILE_DEPARTMENT_CODE,
POSITION.NAME DEFAULT_PROFILE_POSITION_NAME,
CASE GP.VALID WHEN  1 THEN GP.STATUS ELSE 'ELIMINADO' END  GLOBAL_PROFILE_STATUS,
DF.NAME_COMPANY DEFAULT_PROFILE_COMPANY_NAME,
DF.NAME_DIVISION DEFAULT_PROFILE_DIVISION_NAME,
DF.NAME_AREA DEFAULT_PROFILE_AREA_NAME,
DF.NAME_DEPARTMENT DEFAULT_PROFILE_DEPARTMENT_NAME
FROM SCH_CENTRA_ID.DEFAULT_PROFILES DF
JOIN SCH_CENTRA_ID.GLOBAL_PROFILES GP ON DF.GLOBAL_PROFILE_ID=GP.ID
LEFT JOIN SCH_CENTRA_ID.CATALOGS POSITION ON POSITION.CODE = DF.CODE_POSITION
WHERE 
DF.VALID=1 
GO

---------------

DROP VIEW SCH_CENTRA_ID.GLOBAL_TRANSACTIONAL_PROFILES_REPORT_VW
GO
CREATE VIEW SCH_CENTRA_ID.GLOBAL_TRANSACTIONAL_PROFILES_REPORT_VW (ID, VALID, TRANSACTIONAL_PROFILE_CODE, TRANSACTIONAL_PROFILE_NAME, GLOBAL_PROFILE_CODE, GLOBAL_PROFILE_NAME, APPLICATION_CODE, APPLICATION_NAME, TRANSACTIONAL_PROFILE_RISK_LEVEL, GLOBAL_PROFILE_STATUS) AS 
SELECT 
TP.ID ID ,
1 VALID,
TP.CODE TRANSACTIONAL_PROFILE_CODE ,
TP.NAME TRANSACTIONAL_PROFILE_NAME,
GP.CODE GLOBAL_PROFILE_CODE,
GP.NAME GLOBAL_PROFILE_NAME,
A.CODE APPLICATION_CODE,
A.NAME APPLICATION_NAME,
C_NIVREGI.NAME TRANSACTIONAL_PROFILE_RISK_LEVEL,
CASE GP.VALID WHEN  1 THEN GP.STATUS ELSE 'ELIMINADO' END  GLOBAL_PROFILE_STATUS
FROM SCH_CENTRA_ID.GLOBAL_PROFILES GP
LEFT JOIN SCH_CENTRA_ID.GLOBAL_TRANSACTIONAL_PROFILES GTP ON GTP.GLOBAL_PROFILE_ID=GP.ID
LEFT JOIN SCH_CENTRA_ID.TRANSACTIONAL_PROFILES TP ON TP.ID = GTP.TRANSACTIONAL_PROFILE_ID
LEFT JOIN SCH_CENTRA_ID.APPLICATIONS A ON TP.APPLICATION_ID = A.ID
LEFT JOIN SCH_CENTRA_ID.APPLICATIONS_GROUP AG ON A.APPLICATION_GROUP_ID=AG.ID
LEFT JOIN SCH_CENTRA_ID.CATALOGS C_NIVREGI ON TP.CATALOG_RISK_LEVEL_ID=C_NIVREGI.ID
WHERE 
GTP.VALID=1 AND
TP.VALID=1 
GO

ALTER TABLE "SCH_CENTRA_ID"."GLOBAL_PROFILES" ALTER COLUMN "EMPLOYEE_CODE_OWNER" nvarchar(50) NULL
GO


DROP VIEW SCH_CENTRA_ID.GLOBAL_PROFILES_REPORT_VW
GO
CREATE VIEW SCH_CENTRA_ID.GLOBAL_PROFILES_REPORT_VW (ID, VALID, GLOBAL_PROFILE_CODE, GLOBAL_PROFILE_NAME, GLOBAL_PROFILE_IS_BIRTH, GLOBAL_PROFILE_TICKET_NUMBER, GLOBAL_PROFILE_USER_CREATION, GLOBAL_PROFILE_DATE_CREATION, GLOBAL_PROFILE_USER_APPROVAL, GLOBAL_PROFILE_DATE_APPROVAL, GLOBAL_PROFILE_OBSERVATION, GLOBAL_PROFILE_STATUS, GLOBAL_PROFILE_SCOPE_RULES_WHO, GLOBAL_PROFILE_SCOPE_RULES_THAT,GLOBAL_PROFILE_POSITION_NAME_OWNER) AS 
SELECT 
GP.ID AS ID,
1 VALID,
GP.CODE GLOBAL_PROFILE_CODE,
GP.NAME GLOBAL_PROFILE_NAME,
GP.IS_BIRTH GLOBAL_PROFILE_IS_BIRTH,
GP.ASSOCIATED_TICKET_NUMBER GLOBAL_PROFILE_TICKET_NUMBER,
GP.EMPLOYEE_CODE_OWNER GLOBAL_PROFILE_USER_CREATION,
GP.CREATED_DATE GLOBAL_PROFILE_DATE_CREATION,
GP.EMPLOYEE_CODE_APPROVAL GLOBAL_PROFILE_USER_APPROVAL,
GP.APPROVAL_DATE GLOBAL_PROFILE_DATE_APPROVAL,
GP.OBSERVATION AS GLOBAL_PROFILE_OBSERVATION,
CASE GP.VALID WHEN  1 THEN GP.STATUS ELSE 'ELIMINADO' END  GLOBAL_PROFILE_STATUS,
GP.SCOPE_RULES_WHO  GLOBAL_PROFILE_SCOPE_RULES_WHO,
GP.SCOPE_RULES_THAT GLOBAL_PROFILE_SCOPE_RULES_THAT,
C.NAME GLOBAL_PROFILE_POSITION_NAME_OWNER
FROM SCH_CENTRA_ID.GLOBAL_PROFILES GP
LEFT JOIN SCH_CENTRA_ID.CATALOGS C ON GP.CATALOG_POSITION_OWNER_ID=C.ID
GO

ALTER TABLE "SCH_CENTRA_ID"."TEMPLATE_PROFILES_AD" ALTER COLUMN "TERMINAL_SERVICES_PROFILE" nvarchar(1000) NULL
GO
ALTER TABLE "SCH_CENTRA_ID"."TEMPLATE_PROFILES_AD" ALTER COLUMN "CONNECT_FOLLOWING_DRIVE" nvarchar(1000) NULL
GO
ALTER TABLE "SCH_CENTRA_ID"."TEMPLATE_PROFILES_AD" ALTER COLUMN "TERMINAL_SERVICES_HOME_DIRECTORY" nvarchar(1000) NULL
GO




--------------------------------------------------------------



IF NOT EXISTS (SELECT 'X'
                   FROM   INFORMATION_SCHEMA.TABLES
                   WHERE  TABLE_NAME = 'RECORD_FILES'
                          AND TABLE_SCHEMA = 'SCH_CENTRA_ID')
BEGIN
	CREATE TABLE SCH_CENTRA_ID.RECORD_FILES
	    (
		ID BIGINT NOT NULL IDENTITY,
		NAME NVARCHAR(200) NOT NULL,
		DATE_CREATED DATETIME NOT NULL,
		USER_CREATED NVARCHAR(100) NULL,
		DATE_FINISH DATETIME NULL,
		DATE_PLANNED DATETIME NULL,
		STATUS NVARCHAR(100) NOT NULL,
		MESSAGES TEXT NULL,
		TYPE NVARCHAR(10) NOT NULL,
		CONTENT TEXT NOT NULL,
		VALID INT NOT NULL
		CONSTRAINT RECORD_FILES_PK PRIMARY KEY (ID)
	    )
END
GO

