USE [CENTRA_ID]
GO
DELETE FROM sch_centra_id.TEMPLATE_PROFILES 
GO
DELETE FROM sch_centra_id.TEMPLATE_PROFILES_MATRICES_DETAIL 
GO
DELETE FROM sch_centra_id.TEMPLATE_PROFILES_MATRICES_GROUP 
GO
DELETE FROM sch_centra_id.TEMPLATE_PROFILES_MATRICES 
GO
delete from SCH_CENTRA_ID.FIELDS where FIELDS.APPLICATION_GROUP_ID 
in (select id from SCH_CENTRA_ID.APPLICATIONS_GROUP where code='RHDS')
GO
delete from SCH_CENTRA_ID.MATRICES_DETAIL where CODE='perfilUsuario' 
and MATRIX_ID in (SELECT id FROM sch_centra_id.MATRICES where APPLICATION_GROUP_ID in (select id from SCH_CENTRA_ID.APPLICATIONS_GROUP where code='RHDS'))
GO
INSERT INTO SCH_CENTRA_ID.FIELDS (CODE, NAME, PREDETERMINED, LENGTH, REQUIRED, TYPE, APPLICATION_GROUP_ID, VALID) 
VALUES ('perfil_usuario', 'PERFIL USUARIO', '', 30, 1, 'STRING', (select id from SCH_CENTRA_ID.APPLICATIONS_GROUP where code='RHDS'), 1)
GO
UPDATE "SCH_CENTRA_ID"."FIELDS" SET "REQUIRED" = 0 WHERE "CODE" = 'casualApprovallim'
GO
UPDATE SCH_CENTRA_ID.TRANSACTIONAL_PROFILES SET CONFIGURED=1
GO
DELETE FROM SCH_CENTRA_ID.FIELDS WHERE CODE IN ('codigoRol','codigoAgenciaDefault')
AND APPLICATION_GROUP_ID IN (SELECT ID FROM SCH_CENTRA_ID.APPLICATIONS_GROUP WHERE CODE='LOGICIEL')
GO
INSERT INTO SCH_CENTRA_ID.FIELDS (CODE, NAME, PREDETERMINED, LENGTH, REQUIRED, TYPE, APPLICATION_GROUP_ID, VALID) 
VALUES ('roles', 'PERFIL ROLES', '', 200, 1, 'STRING', (select id from SCH_CENTRA_ID.APPLICATIONS_GROUP where code='RHDS'), 1)
GO
DELETE FROM SCH_CENTRA_ID.MATRICES_DETAIL WHERE CODE='roles'
GO

