USE [CENTRA_ID]
GO
ALTER TABLE "sch_centra_id"."TRANSACTIONAL_IDENTITY" ADD TYPE_ACTION nvarchar(1)
GO
ALTER TABLE "sch_centra_id"."USERDATA" ADD SUPERVISOR_IDENTIFICACION nvarchar(20)
GO
ALTER TABLE "sch_centra_id"."USERDATA" ADD SUPERVISOR_NAME nvarchar(100)
GO
ALTER TABLE "sch_centra_id"."COMPANIES_STRUCTURES" ADD CONSTRAINT
    COMPANIES_STRUCTURES_UK UNIQUE ("COMPANY_ID", "CATALOG_ORGANIZATIONAL_STRUCTURE_ID","PARENT_ID")
GO
ALTER TABLE "sch_centra_id"."CATALOGS" DROP CONSTRAINT "CATALOGS_UX"
GO
ALTER TABLE "sch_centra_id"."CATALOGS" ADD CONSTRAINT CATALOGS_UK UNIQUE ("CODE","CATALOG_TYPE_ID")
GO
ALTER TABLE "sch_centra_id"."COMPANIES_STRUCTURES" ADD COMPANY_CODE VARCHAR(20)
GO
ALTER TABLE "sch_centra_id"."COMPANIES_STRUCTURES" ADD CATALOG_CODE VARCHAR(20)
GO
ALTER TABLE "sch_centra_id"."COMPANIES_STRUCTURES" ADD CATALOG_TYPE_CODE VARCHAR(20)
GO



