USE [CENTRA_ID]
GO
ALTER TABLE "sch_centra_id"."TRANSACTIONAL_IDENTITY" DROP COLUMN "TYPE_ACTION"
GO
ALTER TABLE "sch_centra_id"."USERDATA" DROP COLUMN "SUPERVISOR_IDENTIFICACION"
GO
ALTER TABLE "sch_centra_id"."USERDATA" DROP COLUMN "SUPERVISOR_NAME"
GO
ALTER TABLE "sch_centra_id"."COMPANIES_STRUCTURES" DROP CONSTRAINT "COMPANIES_STRUCTURES_UK"
GO
ALTER TABLE "sch_centra_id"."CATALOGS" DROP CONSTRAINT "CATALOGS_UK"
GO

ALTER TABLE "sch_centra_id"."COMPANIES_STRUCTURES" DROP COLUMN "COMPANY_CODE"
GO
ALTER TABLE "sch_centra_id"."COMPANIES_STRUCTURES" DROP COLUMN "CATALOG_CODE"
GO
ALTER TABLE "sch_centra_id"."COMPANIES_STRUCTURES" DROP COLUMN "CATALOG_TYPE_CODE"
GO



