USE [CENTRA_ID]
GO

--TRANSACTIONAL_IDENTITY

CREATE TABLE SCH_CENTRA_ID.TRANSACTIONAL_IDENTITY
    (
        ID BIGINT NOT NULL IDENTITY,
        UUID NVARCHAR(50)  NOT NULL,
        GUID NVARCHAR(50)  NOT NULL,
        USERNAME NVARCHAR(50) ,
        WORKER_CODE NVARCHAR(50) ,
        EMPLOYEE_LASTNAME NVARCHAR(200) ,
        EMPLOYEE_FIRTSNAME NVARCHAR(200) ,
        IDENTIFICATION NVARCHAR(50) ,
        IDENTIFICATION_SUPERVISOR NVARCHAR(50) ,
        NAMES_SUPERVISOR NVARCHAR(200) ,
        COMPANY_CODE NVARCHAR(50) ,
        COMPANY_NAME NVARCHAR(200) ,
        GROUP_CODE NVARCHAR(50) ,
        GROUP_NAME NVARCHAR(200) ,
        DIVISION_CODE NVARCHAR(50) ,
        DIVISION_NAME NVARCHAR(200) ,
        DEPARTMENT_CODE NVARCHAR(50) ,
        DEPARTMENT_NAME NVARCHAR(200) ,
        AREA_CODE NVARCHAR(50) ,
        AREA_NAME NVARCHAR(200) ,
        SUBSIDIARY_CODE NVARCHAR(50) ,
        SUBSIDIARY_NAME NVARCHAR(200) ,
        COST_CENTER_CODE NVARCHAR(50) ,
        COST_CENTER_NAME NVARCHAR(200) ,
        LOCATION_CODE NVARCHAR(200) ,
        POSITION_NAME NVARCHAR(200) ,
        HIERARCHICAL_LEVEL_CODE NVARCHAR(50) ,
        HIERARCHICAL_LEVEL_NAME NVARCHAR(200) ,
        DEPOSIT_ACCOUNT_NUMBER NVARCHAR(50) ,
        EMPLOYEE_START_DATE NVARCHAR(20) ,
        EMPLOYEE_END_DATE NVARCHAR(20) ,
        EMPLOYED_STATUS NVARCHAR(50) ,
        EMPLOYED_CODE NVARCHAR(50) ,
        USER_TYPE NVARCHAR(50) ,
        USER_SUBTYPE NVARCHAR(50) ,
        MOBILE NVARCHAR(20) ,
        ORIGEN NVARCHAR(20) ,
        STATUS NVARCHAR(20)  NOT NULL,
        VALID INT NOT NULL,
        CREATED_DATE DATETIME NOT NULL,
        PLANNED_EXECUTION_DATE DATETIME NOT NULL,
        MODIFY_DATA INT NOT NULL,
        PROFILE_RECALCULATION INT NOT NULL,
        CONSTRAINT TRANSACTIONAL_IDENTITY_PK PRIMARY KEY (ID)
    )
GO



-- USER_PROFILE_TRANSACTIONAL_HISTORY
CREATE TABLE SCH_CENTRA_ID.USER_PROFILE_TRANSACTIONAL_HISTORY (
	ID BIGINT NOT NULL IDENTITY(1,1),
	TRANSACTIONAL_IDENTITY_ID bigint NOT NULL,
	GLOBAL_PROFILE_ID bigint NOT NULL,
	USERDATA_ID bigint NOT NULL,
        CREATED_DATE DATETIME NOT NULL,
	PROFILE_START_DATE  DATETIME NOT NULL,
	PROFILE_END_DATE   DATETIME NOT NULL,
	START_DATE  DATETIME NOT NULL,
	END_DATE  DATETIME NOT NULL,
        MODIFY_DATA INT NOT NULL,
        PROFILE_RECALCULATION INT NOT NULL,
        STATUS NVARCHAR(20)  NOT NULL,
        VALID INT NOT NULL,
CONSTRAINT USER_PROFILE_TRANSACTIONAL_HISTORY_PK PRIMARY KEY (ID))
GO

ALTER TABLE "sch_centra_id"."USER_PROFILE_TRANSACTIONAL_HISTORY" 
   ADD CONSTRAINT USER_PROFILE_TRANSACTIONAL_HISTORY_TRANSACTIONAL_IDENTITY_FK FOREIGN KEY ("TRANSACTIONAL_IDENTITY_ID") REFERENCES "sch_centra_id"."TRANSACTIONAL_IDENTITY" ("ID")
GO

ALTER TABLE "sch_centra_id"."USER_PROFILE_TRANSACTIONAL_HISTORY" 
   ADD CONSTRAINT USER_PROFILE_TRANSACTIONAL_HISTORY_GLOBAL_PROFILES_FK FOREIGN KEY ("GLOBAL_PROFILE_ID") REFERENCES "sch_centra_id"."GLOBAL_PROFILES" ("ID")
GO

ALTER TABLE "sch_centra_id"."USER_PROFILE_TRANSACTIONAL_HISTORY" 
   ADD CONSTRAINT USER_PROFILE_TRANSACTIONAL_HISTORY_USERDATA_FK FOREIGN KEY ("USERDATA_ID") REFERENCES "sch_centra_id"."USERDATA" ("ID")
GO
-- USER_ACTION_PROFILE_TRANSACTIONAL
CREATE TABLE SCH_CENTRA_ID.USER_ACTION_PROFILE_TRANSACTIONAL (
	ID BIGINT NOT NULL IDENTITY(1,1),
	USER_PROFILE_TRANSACTIONAL_HISTORY_ID bigint NOT NULL,
	TRANSACTIONAL_PROFILE_ID bigint NOT NULL,
	APPLICATION_ID bigint NOT NULL,
	PROVISIONING_DATE DATETIME NOT NULL,	
	PROVISIONING_STATUS NVARCHAR(20)  NOT NULL,
	PROVISIONING_COMMENTS NVARCHAR(400)  NOT NULL,	
        STATUS NVARCHAR(20)  NOT NULL,
	ACTION NVARCHAR(20)  NOT NULL,
        CREATED_DATE DATETIME NOT NULL,
        VALID INT NOT NULL,
CONSTRAINT USER_ACTION_PROFILE_TRANSACTIONAL_PK PRIMARY KEY (ID))
GO

ALTER TABLE "sch_centra_id"."USER_ACTION_PROFILE_TRANSACTIONAL" 
   ADD CONSTRAINT USER_ACTION_PROFILE_TRANSACTIONAL_USER_PROFILE_TRANSACTIONAL_HISTORY_FK FOREIGN KEY ("USER_PROFILE_TRANSACTIONAL_HISTORY_ID") REFERENCES "sch_centra_id"."USER_PROFILE_TRANSACTIONAL_HISTORY" ("ID")
GO

ALTER TABLE "sch_centra_id"."USER_ACTION_PROFILE_TRANSACTIONAL" 
   ADD CONSTRAINT USER_ACTION_PROFILE_TRANSACTIONAL_TRANSACTIONAL_PROFILES_FK FOREIGN KEY ("TRANSACTIONAL_PROFILE_ID") REFERENCES "sch_centra_id"."TRANSACTIONAL_PROFILES" ("ID")
GO

ALTER TABLE "sch_centra_id"."USER_ACTION_PROFILE_TRANSACTIONAL" 
   ADD CONSTRAINT USER_ACTION_PROFILE_TRANSACTIONAL_APPLICATIONS_FK FOREIGN KEY ("APPLICATION_ID") REFERENCES "sch_centra_id"."APPLICATIONS" ("ID")
GO

ALTER TABLE "sch_centra_id"."TEMPLATE_PROFILES_MATRICES_DETAIL" ALTER COLUMN "VALUE" nvarchar(100)  NULL
GO

EXEC sp_rename [sch_centra_id.TYPES_USERS], TYPE_USERS
GO

EXEC sp_rename [sch_centra_id.TYPE_USERS.type_user_id], parent_id, 'COLUMN'
GO
ALTER TABLE "sch_centra_id"."TRANSACTIONAL_PROFILES" ALTER COLUMN "comments" nvarchar(100)
    COLLATE SQL_Latin1_General_CP1_CI_AS NULL
GO
ALTER TABLE "sch_centra_id"."USERDATA" ADD WORKER_CODE nvarchar(20)
GO
ALTER TABLE "sch_centra_id"."USERDATA" ADD SUPERVISOR_IDENTIFICATION nvarchar(20)
GO
ALTER TABLE "sch_centra_id"."USERDATA" ADD SUPERVISOR_NAME nvarchar(60)
GO
ALTER TABLE "sch_centra_id"."USERDATA" ALTER COLUMN "EMPLOYEE_INCOME_DATE" DATETIME NOT NULL
GO
ALTER TABLE "sch_centra_id"."USERDATA" ALTER COLUMN "EMPLOYEE_DEPARTURE_DATE" DATETIME NULL
GO
ALTER TABLE "sch_centra_id"."USERDATA" ALTER COLUMN "DATA_DATE" DATETIME NULL
GO
ALTER TABLE "sch_centra_id"."USERDATA" ALTER COLUMN "SUSPENSION_START_DATE" DATETIME NULL
GO
ALTER TABLE "sch_centra_id"."USERDATA" ALTER COLUMN "SUSPENSION_END_DATE" DATETIME NULL
GO
ALTER TABLE "sch_centra_id"."USERDATA" ALTER COLUMN "VALIDATION_START_DATE" DATETIME NULL
GO
ALTER TABLE "sch_centra_id"."USERDATA" ALTER COLUMN "VALIDATION_END_DATE" DATETIME NULL
GO
ALTER TABLE "sch_centra_id"."USERDATA" ALTER COLUMN "ENDING_WORK_DATE" DATETIME NULL
GO
ALTER TABLE "sch_centra_id"."USERDATA" ALTER COLUMN "EFFECTIVE_DATE" DATETIME NULL
GO
ALTER TABLE "sch_centra_id"."USERDATA" DROP COLUMN "SUPERVISOR_IDENTIFICATION"
GO
ALTER TABLE "sch_centra_id"."USERDATA" DROP COLUMN "SUPERVISOR_NAME"
GO







