ALTER TABLE "dbo"."MGI_REPROCESO" ALTER COLUMN "MENSAJE_PETICION" text
GO
ALTER TABLE "dbo"."MGI_REPROCESO" ALTER COLUMN "MENSAJE_RESPUESTA" text 
GO
ALTER TABLE "dbo"."MGI_REPROCESO" ALTER COLUMN "MENSAJE_PETICION_VALORES" text 
GO
ALTER TABLE "dbo"."MGI_REPROCESO" ALTER COLUMN "MENSAJE_RESPUESTA_VALORES" text
GO


