USE [CENTRA_ID]
GO
EXEC sp_rename [sch_centra_id.TRANSACTIONAL_IDENTITY.EMPLOYEE_FIRTSNAME], EMPLOYEE_FIRSTNAME,'COLUMN'
GO
ALTER TABLE "sch_centra_id"."TRANSACTIONAL_IDENTITY" ADD LOCATION_NAME nvarchar(200)
GO
EXEC sp_rename [sch_centra_id.TRANSACTIONAL_IDENTITY.EMPLOYED_STATUS], EMPLOYEE_STATUS, 'COLUMN'
GO
EXEC sp_rename [sch_centra_id.TRANSACTIONAL_IDENTITY.EMPLOYED_CODE], EMPLOYEE_CODE, 'COLUMN'
GO
ALTER TABLE "sch_centra_id"."MASSIVE_PROCESS" ADD GLOBAL_PROFILE_ID bigint
GO
ALTER TABLE "sch_centra_id"."MASSIVE_PROCESS" ADD GLOBAL_PROFILE_CODE nvarchar(20)
GO
ALTER TABLE "sch_centra_id"."MASSIVE_PROCESS" ADD GLOBAL_PROFILE_NAME nvarchar(100)
GO
ALTER TABLE "sch_centra_id"."COSTS_CENTERS" ALTER COLUMN "status" nvarchar(20) NOT NULL
GO
ALTER TABLE "sch_centra_id"."MASSIVE_PROCESS" ADD GLOBAL_PROFILE_DUPLICATE nvarchar(100)
GO
ALTER TABLE "sch_centra_id"."MASSIVE_PROCESS" ADD GLOBAL_PROFILE_ERROR nvarchar(1)
GO

