USE [CENTRA_ID]
GO
/****** Object:  Schema [SCH_CENTRA_ID]    Script Date: 07/04/2020 11:56:53 ******/
CREATE SCHEMA [SCH_CENTRA_ID]
GO
/****** Object:  Schema [SCH_CENTRA_ID_AUDIT]    Script Date: 07/04/2020 11:56:53 ******/
CREATE SCHEMA [SCH_CENTRA_ID_AUDIT]
GO
/****** Object:  Table [SCH_CENTRA_ID].[CATALOGS]    Script Date: 07/04/2020 11:56:53 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [SCH_CENTRA_ID].[CATALOGS](
	[ID] [bigint] IDENTITY(1,1) NOT NULL,
	[CODE] [nvarchar](20) NOT NULL,
	[NAME] [nvarchar](100) NOT NULL,
	[PREDETERMINED] [int] NOT NULL,
	[ORDINAL] [int] NULL,
	[VALUE_TEXT] [nvarchar](20) NULL,
	[VALUE_NUMBER] [numeric](10, 2) NULL,
	[VALUE_DATE] [datetime] NULL,
	[VALUE_BOOLEAN] [int] NULL,
	[catalog_type_id] [bigint] NOT NULL,
	[VALID] [int] NOT NULL,
	[FILTER] [text] NULL,
 CONSTRAINT [CATALOGS_PK] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 85) ON [PRIMARY],
 CONSTRAINT [CATALOGS_UK] UNIQUE NONCLUSTERED 
(
	[CODE] ASC,
	[catalog_type_id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 85) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [SCH_CENTRA_ID].[DEFAULT_PROFILES]    Script Date: 07/04/2020 11:56:54 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [SCH_CENTRA_ID].[DEFAULT_PROFILES](
	[ID] [bigint] IDENTITY(1,1) NOT NULL,
	[GLOBAL_PROFILE_ID] [bigint] NOT NULL,
	[CODE_COMPANY] [nvarchar](20) NOT NULL,
	[CODE_DIVISION] [nvarchar](20) NOT NULL,
	[CODE_AREA] [nvarchar](20) NOT NULL,
	[CODE_DEPARTMENT] [nvarchar](20) NOT NULL,
	[CODE_POSITION] [nvarchar](20) NOT NULL,
	[VALID] [int] NOT NULL,
 CONSTRAINT [DEFAULT_PROFILES_PK] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 85) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [SCH_CENTRA_ID].[GLOBAL_PROFILES]    Script Date: 07/04/2020 11:56:54 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [SCH_CENTRA_ID].[GLOBAL_PROFILES](
	[ID] [bigint] IDENTITY(1,1) NOT NULL,
	[CODE] [nvarchar](20) NOT NULL,
	[NAME] [nvarchar](100) NOT NULL,
	[IS_BIRTH] [int] NOT NULL,
	[VALID] [int] NOT NULL,
	[EMPLOYEE_CODE_OWNER] [nvarchar](50) NOT NULL,
	[CATALOG_POSITION_OWNER_ID] [bigint] NULL,
	[ASSOCIATED_TICKET_NUMBER] [nvarchar](50) NOT NULL,
	[STATUS] [nvarchar](20) NOT NULL,
	[CREATED_DATE] [datetime] NULL,
	[APPROVAL_DATE] [datetime] NULL,
	[EMPLOYEE_CODE_APPROVAL] [nvarchar](50) NULL,
	[OBSERVATION] [nvarchar](100) NULL,
	[SCOPE_RULES_WHO] [nvarchar](max) NULL,
	[SCOPE_RULES_THAT] [nvarchar](max) NULL,
	[FILTER] [text] NULL,
 CONSTRAINT [GLOBAL_PROFILES_PK] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 85) ON [PRIMARY],
 CONSTRAINT [GLOBAL_PROFILES_UK] UNIQUE NONCLUSTERED 
(
	[CODE] ASC,
	[NAME] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 85) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  View [SCH_CENTRA_ID].[DEFAULT_PROFILES_REPORT_VW]    Script Date: 07/04/2020 11:56:54 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE VIEW [SCH_CENTRA_ID].[DEFAULT_PROFILES_REPORT_VW] AS
SELECT 
DF.ID ID,
DF.VALID VALID,
GP.CODE GLOBAL_PROFILE_CODE,
GP.NAME GLOBAL_PROFILE_NAME,
DF.CODE_COMPANY DEFAULT_PROFILE_COMPANY_CODE,
DF.CODE_DIVISION DEFAULT_PROFILE_DIVISION_CODE,
DF.CODE_AREA DEFAULT_PROFILE_AREA_CODE,
DF.CODE_DEPARTMENT DEFAULT_PROFILE_DEPARTMENT_CODE,
POSITION.NAME DEFAULT_PROFILE_POSITION_NAME,
GP.STATUS GLOBAL_PROFILE_STATUS
FROM SCH_CENTRA_ID.DEFAULT_PROFILES DF
JOIN SCH_CENTRA_ID.GLOBAL_PROFILES GP ON DF.GLOBAL_PROFILE_ID=GP.ID
LEFT JOIN SCH_CENTRA_ID.CATALOGS POSITION ON POSITION.CODE = DF.CODE_POSITION
WHERE 
DF.VALID=1 AND
GP.VALID=1
GO
/****** Object:  View [SCH_CENTRA_ID].[GLOBAL_PROFILES_REPORT_VW]    Script Date: 07/04/2020 11:56:54 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE VIEW [SCH_CENTRA_ID].[GLOBAL_PROFILES_REPORT_VW] AS
SELECT 
GP.ID AS ID,
GP.VALID VALID,
GP.CODE GLOBAL_PROFILE_CODE,
GP.NAME GLOBAL_PROFILE_NAME,
GP.IS_BIRTH GLOBAL_PROFILE_IS_BIRTH,
GP.ASSOCIATED_TICKET_NUMBER GLOBAL_PROFILE_TICKET_NUMBER,
GP.EMPLOYEE_CODE_OWNER GLOBAL_PROFILE_USER_CREATION,
GP.CREATED_DATE GLOBAL_PROFILE_DATE_CREATION,
GP.EMPLOYEE_CODE_APPROVAL GLOBAL_PROFILE_USER_APPROVAL,
GP.APPROVAL_DATE GLOBAL_PROFILE_DATE_APPROVAL,
GP.OBSERVATION AS GLOBAL_PROFILE_OBSERVATION,
GP.STATUS GLOBAL_PROFILE_STATUS,
GP.SCOPE_RULES_WHO  GLOBAL_PROFILE_SCOPE_RULES_WHO,
GP.SCOPE_RULES_THAT GLOBAL_PROFILE_SCOPE_RULES_THAT
FROM SCH_CENTRA_ID.GLOBAL_PROFILES GP
WHERE GP.VALID=1
GO
/****** Object:  Table [SCH_CENTRA_ID].[APPLICATIONS]    Script Date: 07/04/2020 11:56:54 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [SCH_CENTRA_ID].[APPLICATIONS](
	[ID] [bigint] IDENTITY(1,1) NOT NULL,
	[CODE] [nvarchar](50) NOT NULL,
	[NAME] [nvarchar](100) NOT NULL,
	[automatic_provision] [int] NOT NULL,
	[VALID] [int] NOT NULL,
	[APPLICATION_GROUP_ID] [bigint] NOT NULL,
	[STATUS] [nvarchar](20) NOT NULL,
	[PARENT_ID] [bigint] NULL,
 CONSTRAINT [APPLICATIONS_PK] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 85) ON [PRIMARY],
 CONSTRAINT [APPLICATIONS_CODE_UK] UNIQUE NONCLUSTERED 
(
	[CODE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 85) ON [PRIMARY],
 CONSTRAINT [APPLICATIONS_NAME_UK] UNIQUE NONCLUSTERED 
(
	[NAME] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 85) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [SCH_CENTRA_ID].[APPLICATIONS_GROUP]    Script Date: 07/04/2020 11:56:54 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [SCH_CENTRA_ID].[APPLICATIONS_GROUP](
	[ID] [bigint] IDENTITY(1,1) NOT NULL,
	[CODE] [nvarchar](50) NOT NULL,
	[NAME] [nvarchar](100) NOT NULL,
	[ENDPOINT_TYPE] [nvarchar](50) NOT NULL,
	[ORDINAL] [int] NOT NULL,
	[VALID] [int] NOT NULL,
	[NUMBER_RETRIES] [int] NULL,
	[TIME_BETWEEN_RETRIES] [int] NULL,
	[ERRORS_NOT_REQUIRE_TICKET] [nvarchar](100) NULL,
 CONSTRAINT [APPLICATIONS_GROUP_PK] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 85) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [SCH_CENTRA_ID].[GLOBAL_TRANSACTIONAL_PROFILES]    Script Date: 07/04/2020 11:56:54 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [SCH_CENTRA_ID].[GLOBAL_TRANSACTIONAL_PROFILES](
	[ID] [bigint] IDENTITY(1,1) NOT NULL,
	[GLOBAL_PROFILE_ID] [bigint] NOT NULL,
	[TRANSACTIONAL_PROFILE_ID] [bigint] NOT NULL,
	[DATE_CREATED] [date] NOT NULL,
	[DATE_DELETED] [date] NULL,
	[USER_CREATED] [nvarchar](20) NOT NULL,
	[USER_DELETED] [nvarchar](20) NULL,
	[VALID] [int] NOT NULL,
	[SYNCHRONIZATION_DATE] [datetime] NULL,
	[SYNCHRONIZATION_STATUS] [nvarchar](1) NULL,
 CONSTRAINT [GLOBAL_TRANSACTIONAL_PROFILES_PK] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 85) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [SCH_CENTRA_ID].[TRANSACTIONAL_PROFILES]    Script Date: 07/04/2020 11:56:54 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [SCH_CENTRA_ID].[TRANSACTIONAL_PROFILES](
	[ID] [bigint] IDENTITY(1,1) NOT NULL,
	[CODE] [nvarchar](50) NOT NULL,
	[NAME] [nvarchar](200) NOT NULL,
	[COMMENTS] [nvarchar](100) NULL,
	[CATALOG_RISK_LEVEL_ID] [bigint] NOT NULL,
	[VALID] [int] NOT NULL,
	[application_id] [bigint] NOT NULL,
	[DATE_CREATED] [datetime] NOT NULL,
	[USER_CREATED] [nvarchar](20) NOT NULL,
	[DATE_DELETED] [datetime] NULL,
	[USER_DELETED] [nvarchar](20) NULL,
	[CONFIGURED] [int] NOT NULL,
	[FILTER] [text] NULL,
	[SYNCHRONIZATION_DATE] [datetime] NULL,
	[SYNCHRONIZATION_STATUS] [nvarchar](1) NULL,
 CONSTRAINT [TRANSACTIONAL_PROFILES_PK] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 85) ON [PRIMARY],
 CONSTRAINT [TRANSACTIONAL_PROFILES_CODE_UK] UNIQUE NONCLUSTERED 
(
	[CODE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 85) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  View [SCH_CENTRA_ID].[GLOBAL_TRANSACTIONAL_PROFILES_REPORT_VW]    Script Date: 07/04/2020 11:56:54 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE VIEW [SCH_CENTRA_ID].[GLOBAL_TRANSACTIONAL_PROFILES_REPORT_VW] AS
SELECT 
TP.ID ID ,
TP.VALID VALID,
TP.CODE TRANSACTIONAL_PROFILE_CODE ,
TP.NAME TRANSACTIONAL_PROFILE_NAME,
GP.CODE GLOBAL_PROFILE_CODE,
GP.NAME GLOBAL_PROFILE_NAME,
A.CODE APPLICATION_CODE,
A.NAME APPLICATION_NAME,
C_NIVREGI.NAME TRANSACTIONAL_PROFILE_RISK_LEVEL,
GP.STATUS GLOBAL_PROFILE_STATUS
FROM SCH_CENTRA_ID.GLOBAL_PROFILES GP
JOIN SCH_CENTRA_ID.GLOBAL_TRANSACTIONAL_PROFILES GTP ON GTP.GLOBAL_PROFILE_ID=GP.ID
JOIN SCH_CENTRA_ID.TRANSACTIONAL_PROFILES TP ON TP.ID = GTP.TRANSACTIONAL_PROFILE_ID
JOIN SCH_CENTRA_ID.APPLICATIONS A ON TP.APPLICATION_ID = A.ID
JOIN SCH_CENTRA_ID.APPLICATIONS_GROUP AG ON A.APPLICATION_GROUP_ID=AG.ID
LEFT JOIN SCH_CENTRA_ID.CATALOGS C_NIVREGI ON TP.CATALOG_RISK_LEVEL_ID=C_NIVREGI.ID
WHERE 
GP.VALID=1 AND 
GTP.VALID=1 AND
TP.VALID=1 AND 
A.VALID=1 AND 
AG.VALID=1
GO
/****** Object:  Table [SCH_CENTRA_ID].[FIELDS]    Script Date: 07/04/2020 11:56:54 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [SCH_CENTRA_ID].[FIELDS](
	[ID] [bigint] IDENTITY(1,1) NOT NULL,
	[CODE] [nvarchar](50) NOT NULL,
	[NAME] [nvarchar](100) NOT NULL,
	[PREDETERMINED] [nvarchar](100) NULL,
	[LENGTH] [int] NOT NULL,
	[REQUIRED] [int] NOT NULL,
	[TYPE] [nvarchar](10) NOT NULL,
	[APPLICATION_GROUP_ID] [bigint] NOT NULL,
	[VALID] [int] NOT NULL,
 CONSTRAINT [FIELDS_PK] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 85) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [SCH_CENTRA_ID].[TEMPLATE_PROFILES]    Script Date: 07/04/2020 11:56:54 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [SCH_CENTRA_ID].[TEMPLATE_PROFILES](
	[ID] [bigint] IDENTITY(1,1) NOT NULL,
	[TRANSACTIONAL_PROFILE_ID] [bigint] NOT NULL,
	[FIELD_ID] [bigint] NULL,
	[FIELD_VALUE] [nvarchar](100) NULL,
	[VALID] [int] NOT NULL,
 CONSTRAINT [PROFILE_TEMPLATE_PK] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 85) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  View [SCH_CENTRA_ID].[TRANSACTIONAL_PROFILES_REPORT_VW]    Script Date: 07/04/2020 11:56:54 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE VIEW [SCH_CENTRA_ID].[TRANSACTIONAL_PROFILES_REPORT_VW] AS
SELECT 
TP.ID ID,
TP.VALID VALID,
TP.CODE TRANSACTIONAL_PROFILE_CODE, 
TP.NAME TRANSACTIONAL_PROFILE_NAME,
A.CODE APPLICATION_CODE,
A.NAME APPLICATION_NAME,
A.AUTOMATIC_PROVISION APPLICATION_AUTOMATIC,
C_NIVREGI.NAME RISK_LEVEL,
TP.COMMENTS COMMENTS,
F.NAME FIELD_NAME,
TR.FIELD_VALUE FIELD_VALUE
FROM SCH_CENTRA_ID.GLOBAL_PROFILES GP
JOIN SCH_CENTRA_ID.GLOBAL_TRANSACTIONAL_PROFILES GTP ON GTP.GLOBAL_PROFILE_ID=GP.ID
JOIN SCH_CENTRA_ID.TRANSACTIONAL_PROFILES TP ON TP.ID = GTP.TRANSACTIONAL_PROFILE_ID
JOIN SCH_CENTRA_ID.APPLICATIONS A ON TP.APPLICATION_ID = A.ID
JOIN SCH_CENTRA_ID.APPLICATIONS_GROUP AG ON A.APPLICATION_GROUP_ID=AG.ID
LEFT JOIN SCH_CENTRA_ID.TEMPLATE_PROFILES TR ON TR.TRANSACTIONAL_PROFILE_ID = TP.ID
LEFT JOIN SCH_CENTRA_ID.FIELDS F ON F.ID = TR.FIELD_ID
LEFT JOIN SCH_CENTRA_ID.CATALOGS C_NIVREGI ON TP.CATALOG_RISK_LEVEL_ID=C_NIVREGI.ID
WHERE GP.VALID=1 AND 
GTP.VALID=1 AND
TP.VALID=1 AND 
A.VALID=1 AND 
AG.VALID=1 AND
TR.VALID=1 AND
F.VALID=1
GO
/****** Object:  Table [SCH_CENTRA_ID].[COMPANIES]    Script Date: 07/04/2020 11:56:54 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [SCH_CENTRA_ID].[COMPANIES](
	[ID] [bigint] IDENTITY(1,1) NOT NULL,
	[IDENTIFIER] [nvarchar](20) NOT NULL,
	[BUSINESS_NAME] [nvarchar](100) NOT NULL,
	[VALID] [int] NOT NULL,
	[CATALOG_COMPANY_TYPE_ID] [bigint] NOT NULL,
	[CODE] [nvarchar](20) NOT NULL,
	[DOMAIN_NAME] [nvarchar](50) NOT NULL,
	[STATUS] [nvarchar](20) NOT NULL,
	[LOGON] [nvarchar](100) NULL,
 CONSTRAINT [COMPANIES_PK] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 85) ON [PRIMARY],
 CONSTRAINT [COMPANIES_CODE_UK] UNIQUE NONCLUSTERED 
(
	[IDENTIFIER] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 85) ON [PRIMARY],
 CONSTRAINT [COMPANIES_IDENTIFIER_UK] UNIQUE NONCLUSTERED 
(
	[IDENTIFIER] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 85) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [SCH_CENTRA_ID].[COSTS_CENTERS]    Script Date: 07/04/2020 11:56:54 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [SCH_CENTRA_ID].[COSTS_CENTERS](
	[ID] [bigint] IDENTITY(1,1) NOT NULL,
	[CODE] [nvarchar](20) NOT NULL,
	[NAME] [nvarchar](100) NOT NULL,
	[COMPANY_ID] [bigint] NOT NULL,
	[parent_id] [bigint] NULL,
	[VALID] [int] NOT NULL,
	[status] [nvarchar](20) NULL,
	[FILTER] [text] NULL,
 CONSTRAINT [COSTS_CENTERS_PK] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 85) ON [PRIMARY],
 CONSTRAINT [COSTS_CENTERS_CODE_UK] UNIQUE NONCLUSTERED 
(
	[CODE] ASC,
	[NAME] ASC,
	[COMPANY_ID] ASC,
	[parent_id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 85) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [SCH_CENTRA_ID].[TYPE_USERS]    Script Date: 07/04/2020 11:56:54 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [SCH_CENTRA_ID].[TYPE_USERS](
	[ID] [bigint] IDENTITY(1,1) NOT NULL,
	[CODE] [nvarchar](20) NOT NULL,
	[NAME] [nvarchar](100) NOT NULL,
	[TYPE] [nvarchar](1) NOT NULL,
	[parent_id] [bigint] NULL,
	[VALID] [int] NOT NULL,
 CONSTRAINT [TYPES_USERS_PK] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 85) ON [PRIMARY],
 CONSTRAINT [TYPES_USERS_CODE_UK] UNIQUE NONCLUSTERED 
(
	[CODE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 85) ON [PRIMARY],
 CONSTRAINT [TYPES_USERS_NAME_UK] UNIQUE NONCLUSTERED 
(
	[NAME] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 85) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [SCH_CENTRA_ID].[USERDATA]    Script Date: 07/04/2020 11:56:54 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [SCH_CENTRA_ID].[USERDATA](
	[ID] [bigint] IDENTITY(1,1) NOT NULL,
	[USERNAME] [nvarchar](20) NOT NULL,
	[IDENTIFICATION] [nvarchar](60) NOT NULL,
	[CATALOG_IDENTIFICATION_TYPE_ID] [bigint] NOT NULL,
	[EMPLOYEE_FIRST_SURNAME] [nvarchar](30) NOT NULL,
	[EMPLOYEE_SECOND_SURNAME] [nvarchar](30) NULL,
	[EMPLOYEE_FIRST_NAME] [nvarchar](30) NOT NULL,
	[EMPLOYEE_SECOND_NAME] [nvarchar](30) NULL,
	[EMPLOYEE_COMPLETE_NAME] [nvarchar](120) NOT NULL,
	[COMPANY_ID] [bigint] NOT NULL,
	[CATALOG_DIVISION_ID] [bigint] NOT NULL,
	[CATALOG_AREA_ID] [bigint] NULL,
	[CATALOG_DEPARTMENT_ID] [bigint] NULL,
	[CATALOG_POSITION_ID] [bigint] NOT NULL,
	[USERDATA_SUPERVISOR_ID] [bigint] NULL,
	[USERDATA_BANK_COUNTERPART_ID] [bigint] NULL,
	[USERDATA_RESPONSIBLE_USER_ID] [bigint] NULL,
	[GROUPING_CODE] [nvarchar](50) NULL,
	[SUBSIDIARY_CODE] [nvarchar](60) NULL,
	[SUBSIDIARY_NAME] [nvarchar](100) NULL,
	[LOCATION_NAME] [nvarchar](200) NULL,
	[HIERARCHICAL_LEVEL] [nvarchar](50) NOT NULL,
	[DEPOSIT_ACCOUNT_NUMBER] [nvarchar](50) NULL,
	[EMPLOYEE_INCOME_DATE] [datetime] NOT NULL,
	[EMPLOYEE_DEPARTURE_DATE] [datetime] NULL,
	[EMPLOYEE_STATUS] [nvarchar](20) NOT NULL,
	[EMPLOYEE_CODE] [nvarchar](20) NULL,
	[TYPE_USER_ID] [bigint] NOT NULL,
	[SUBTYPE_USER_ID] [bigint] NOT NULL,
	[REGISTRATION_DATE] [datetime] NOT NULL,
	[TYPE_EVENT] [nvarchar](10) NOT NULL,
	[DATA_DATE] [datetime] NULL,
	[PROVISION_DATE] [datetime] NULL,
	[MOBILE] [nvarchar](50) NULL,
	[SUSPENSION_START_DATE] [datetime] NULL,
	[SUSPENSION_END_DATE] [datetime] NULL,
	[SUSPENSION_REASON] [nvarchar](200) NULL,
	[SUSPENSION_TYPE] [nvarchar](50) NULL,
	[VALIDATION_START_DATE] [datetime] NULL,
	[VALIDATION_END_DATE] [datetime] NULL,
	[ENDING_WORK_DATE] [datetime] NULL,
	[MAIL] [nvarchar](100) NOT NULL,
	[EFFECTIVE_DATE] [datetime] NULL,
	[USERNAME_VIEW] [nvarchar](60) NULL,
	[GUID] [nvarchar](50) NOT NULL,
	[UUID] [nvarchar](50) NOT NULL,
	[COST_CENTER_ID] [bigint] NOT NULL,
	[GLOBAL_PROFILE_ID] [bigint] NULL,
	[VALID] [int] NOT NULL,
	[WORKER_CODE] [nvarchar](20) NULL,
	[SUPERVISOR_IDENTIFICACION] [nvarchar](20) NULL,
	[SUPERVISOR_NAME] [nvarchar](100) NULL,
	[FILTER] [text] NULL,
	[JUSTIFICATION_ELIMINATION] [text] NULL,
	[JUSTIFICATION_CHANGE_COST_CENTER] [text] NULL,
	[JUSTIFICATION_CHANGE_GLOBAL_PROFILE] [text] NULL,
	[TYPE_ROTARY] [nvarchar](10) NULL,
	[COUNTER_GENERIC_ROTARY] [int] NULL,
	[COUNTER_GENERIC_MAIL] [int] NULL,
 CONSTRAINT [USER_DATA_PK] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 85) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  View [SCH_CENTRA_ID].[USERDATA_REPORT_VW]    Script Date: 07/04/2020 11:56:54 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE VIEW [SCH_CENTRA_ID].[USERDATA_REPORT_VW] AS
SELECT 
UD.ID ID,
UD.VALID VALID,
UD.USERNAME USERDATA_USERNAME,
UD.IDENTIFICATION USERDATA_IDENTIFICATION,
UD.EMPLOYEE_COMPLETE_NAME USERDATA_NAME,
UD.EMPLOYEE_CODE USERDATA_EMPLOYEE_CODE,
TU.NAME USERDATA_TYPE_USER,
STU.NAME USERDATA_SUBTYPE_USER,
UD.MOBILE USERDATA_MOBILE,
UD.MAIL USERDATA_MAIL,
UD.EMPLOYEE_STATUS USERDATA_STATUS,
UD.EFFECTIVE_DATE USERDATA_DATE_CREATION,
UD.ENDING_WORK_DATE USERDATA_DATE_DELETION,
UD.EMPLOYEE_INCOME_DATE USERDATA_DATE_START,
UD.EMPLOYEE_DEPARTURE_DATE USERDATE_DATE_END,
GP.CODE GLOBAL_PROFILE_CODE,
GP.NAME GLOBAL_PROFILE_NAME,
C.BUSINESS_NAME COMPANY_NAME,
DIVISION.NAME DIVISION_NAME,
AREA.NAME AREA_NAME,
DEPARTMENT.NAME DEPARTMENT_NAME,
POSITION.NAME POSITION_NAME,
CC.CODE COST_CENTER_CODE,
CC.NAME COST_CENTER_NAME,
SUPER.IDENTIFICATION SUPERVISOR_IDENTIFICACION,
SUPER.EMPLOYEE_COMPLETE_NAME SUPERVISOR_NAME
FROM SCH_CENTRA_ID.USERDATA UD
JOIN SCH_CENTRA_ID.GLOBAL_PROFILES GP ON UD.GLOBAL_PROFILE_ID = GP.ID
JOIN SCH_CENTRA_ID.TYPE_USERS TU ON TU.ID =UD.TYPE_USER_ID
JOIN SCH_CENTRA_ID.TYPE_USERS STU ON STU.ID =UD.SUBTYPE_USER_ID
JOIN SCH_CENTRA_ID.COMPANIES C ON C.ID = UD.COMPANY_ID
LEFT JOIN SCH_CENTRA_ID.CATALOGS DIVISION ON DIVISION.ID =UD.CATALOG_DIVISION_ID
LEFT JOIN SCH_CENTRA_ID.CATALOGS AREA ON AREA.ID =UD.CATALOG_AREA_ID
LEFT JOIN SCH_CENTRA_ID.CATALOGS DEPARTMENT ON DEPARTMENT.ID =UD.CATALOG_DEPARTMENT_ID
LEFT JOIN SCH_CENTRA_ID.CATALOGS POSITION ON POSITION.ID =UD.CATALOG_POSITION_ID
LEFT JOIN SCH_CENTRA_ID.COSTS_CENTERS CC ON CC.ID = UD.COST_CENTER_ID
LEFT JOIN SCH_CENTRA_ID.USERDATA SUPER ON UD.USERDATA_SUPERVISOR_ID = SUPER.ID
WHERE UD.VALID=1
GO
/****** Object:  View [SCH_CENTRA_ID].[TRANSACTIONAL_PROFILES_VW]    Script Date: 07/04/2020 11:56:54 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE VIEW [SCH_CENTRA_ID].[TRANSACTIONAL_PROFILES_VW] (GLOBAL_PROFILE_ID, GLOBAL_PROFILE_CODE, GLOBAL_PROFILE_NAME, GLOBAL_PROFILE_IS_BIRTH, ID, TRANSACTIONAL_PROFILE_CODE, TRANSACTIONAL_PROFILE_NAME, TRANSACTIONAL_PROFILE_COMMENTS, TRANSACTIONAL_PROFILE_CATALOG_RISK_LEVEL_ID, TRANSACTIONAL_PROFILE_APPLICATION_ID, APPLICATION_CODE, APPLICATION_NAME, APPLICATION_AUTOMATIC_PROVISION, VALID,FILTER) AS 
 select 
gp.id GLOBAL_PROFILE_ID,
gp.code GLOBAL_PROFILE_CODE,
gp.name GLOBAL_PROFILE_NAME,
gp.is_birth GLOBAL_PROFILE_IS_BIRTH,
tp.id ID,
tp.code TRANSACTIONAL_PROFILE_CODE,
tp.name TRANSACTIONAL_PROFILE_NAME,
tp.comments TRANSACTIONAL_PROFILE_COMMENTS,
tp.catalog_risk_level_id TRANSACTIONAL_PROFILE_CATALOG_RISK_LEVEL_ID,
tp.application_id TRANSACTIONAL_PROFILE_APPLICATION_ID,
a.code APPLICATION_CODE,
a.name APPLICATION_NAME,
a.automatic_provision APPLICATION_AUTOMATIC_PROVISION,
tp.valid VALID,
tp.filter FILTER
from sch_centra_id.GLOBAL_PROFILES gp
join sch_centra_id.GLOBAL_TRANSACTIONAL_PROFILES gtp on gtp.GLOBAL_PROFILE_ID=gp.id
join sch_centra_id.TRANSACTIONAL_PROFILES tp on gtp.TRANSACTIONAL_PROFILE_ID=tp.id
join sch_centra_id.APPLICATIONS a on a.id=tp.application_id
where gp.valid=1 and gtp.VALID=1 and tp.valid=1
GO
/****** Object:  View [SCH_CENTRA_ID].[USERDATA_VW]    Script Date: 07/04/2020 11:56:54 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE VIEW [SCH_CENTRA_ID].[USERDATA_VW] (ID, USERNAME, CODIGO_EMPLEADO, CODIGO_TRABAJADOR, IDENTIFICACION, APELLIDOS_EMPLEADO, NOMBRES_EMPLEADO, CELULAR, NUMERO_CUENTA_DEPOSITO, FECHA_INGRESO, FECHA_SALIDA, IDENTIFICACION_SUPERVISOR, NOMBRE_SUPERVISOR, CODIGO_COMPANIA, NOMBRE_COMPANIA, CODIGO_DIVISION, NOMBRE_DIVISION, CODIGO_AREA, NOMBRE_AREA, CODIGO_DEPARTAMENTO, NOMBRE_DEPARTAMENTO, CODIGO_CARGO, NOMBRE_CARGO, CODIGO_CENTRO_COSTO, NOMBRE_CENTRO_COSTO, CODIGO_AGRUPACION, CODIGO_NIVEL_JERARQUICO, TIPOUSUARIO, SUBTIPO, ESTADO_EMPLEADO, NOMBRELOCALIDAD, CORREO_ELECTRONICO, ID_PERFIL_GLOBAL, CODIGO_PERFIL_GLOBAL, NOMBRE_PERFIL_GLOBAL, ID_USUARIO, VALID, NOMBRES_COMPLETOS, CORREO_ELECTRONICO_PERSONAL, UUID, GUID, TIPO_IDENTIFICACION, TIPO_ROTATIVO, ID_SUPERVISOR, IDENTIFICACION_CONTRAPARTE, NOMBRE_CONTRAPARTE, ID_CONTRAPARTE, IDENTIFICACION_RESPONSABLE, NOMBRE_RESPONSABLE, ID_RESPONSABLE, COUNTER_GENERIC_ROTARY,COUNTER_GENERIC_MAIL) AS 
select 
ud.ID,
ud.USERNAME USERNAME,
ud.EMPLOYEE_CODE CODIGO_EMPLEADO,
ud.WORKER_CODE CODIGO_TRABAJADOR,
ud.IDENTIFICATION IDENTIFICACION,
ud.EMPLOYEE_FIRST_SURNAME+' ' +ISNULL(ud.EMPLOYEE_SECOND_SURNAME,'') APELLIDOS_EMPLEADO,
ud.EMPLOYEE_FIRST_NAME+' ' +ISNULL(ud.EMPLOYEE_SECOND_NAME,'') NOMBRES_EMPLEADO,
ud.MOBILE CELULAR,
ud.DEPOSIT_ACCOUNT_NUMBER NUMERO_CUENTA_DEPOSITO,
ud.EMPLOYEE_INCOME_DATE FECHA_INGRESO,
ud.EMPLOYEE_DEPARTURE_DATE FECHA_SALIDA,
su.IDENTIFICATION IDENTIFICACION_SUPERVISOR,
su.EMPLOYEE_COMPLETE_NAME  NOMBRE_SUPERVISOR,
c.CODE CODIGO_COMPANIA,
c.BUSINESS_NAME NOMBRE_COMPANIA,
div.CODE CODIGO_DIVISION,
div.NAME NOMBRE_DIVISION,
are.CODE CODIGO_AREA,
are.NAME NOMBRE_AREA,
dto.CODE CODIGO_DEPARTAMENTO,
dto.NAME NOMBRE_DEPARTAMENTO,
car.CODE CODIGO_CARGO,
car.NAME NOMBRE_CARGO,
cc.CODE CODIGO_CENTRO_COSTO,
cc.NAME NOMBRE_CENTRO_COSTO,
ud.GROUPING_CODE CODIGO_AGRUPACION,
ud.HIERARCHICAL_LEVEL CODIGO_NIVEL_JERARQUICO,
tu.CODE TIPOUSUARIO,
stu.CODE SUBTIPO,
ud.EMPLOYEE_STATUS ESTADO_EMPLEADO,
ud.LOCATION_NAME NOMBRELOCALIDAD,
ud.MAIL CORREO_ELECTRONICO,
gp.ID ID_PERFIL_GLOBAL,
gp.CODE CODIGO_PERFIL_GLOBAL,
gp.NAME NOMBRE_PERFIL_GLOBAL,
ud.id ID_USUARIO,
ud.VALID,
ud.EMPLOYEE_FIRST_SURNAME+' ' +ISNULL(ud.EMPLOYEE_SECOND_SURNAME,'')+' '+ ud.EMPLOYEE_FIRST_NAME+' ' +ISNULL(ud.EMPLOYEE_SECOND_NAME,'') NOMBRES_COMPLETOS,
ud.USERNAME_VIEW CORREO_ELECTRONICO_PERSONAL,
ud.UUID UUID,
ud.GUID GUID,
ti.NAME TIPO_IDENTIFICACION,
ud.TYPE_ROTARY TIPO_ROTATIVO,
su.ID ID_SUPERVISOR,
con.IDENTIFICATION IDENTIFICACION_CONTRAPARTE,
con.EMPLOYEE_COMPLETE_NAME  NOMBRE_CONTRAPARTE,
con.ID ID_CONTRAPARTE,
res.IDENTIFICATION IDENTIFICACION_RESPONSABLE,
res.EMPLOYEE_COMPLETE_NAME NOMBRE_RESPONSABLE,
res.ID ID_RESPONSABLE,
ud.COUNTER_GENERIC_ROTARY COUNTER_GENERIC_ROTARY,
ud.COUNTER_GENERIC_MAIL COUNTER_GENERIC_MAIL
from SCH_CENTRA_ID.USERDATA ud
left join SCH_CENTRA_ID.USERDATA su on ud.USERDATA_SUPERVISOR_ID=su.id
left join SCH_CENTRA_ID.USERDATA con on ud.USERDATA_BANK_COUNTERPART_ID=con.ID
left join SCH_CENTRA_ID.USERDATA res on ud.USERDATA_RESPONSIBLE_USER_ID=res.ID
left join SCH_CENTRA_ID.COMPANIES c on ud.COMPANY_ID=c.id
left join SCH_CENTRA_ID.CATALOGS div on ud.CATALOG_DIVISION_ID=div.id
left join SCH_CENTRA_ID.CATALOGS are on ud.CATALOG_AREA_ID=are.id
left join SCH_CENTRA_ID.CATALOGS dto on ud.CATALOG_DEPARTMENT_ID=dto.id
left join SCH_CENTRA_ID.CATALOGS car on ud.CATALOG_POSITION_ID=car.id
left join SCH_CENTRA_ID.CATALOGS ti on ud.CATALOG_IDENTIFICATION_TYPE_ID=ti.id
left join SCH_CENTRA_ID.COSTS_CENTERS cc on ud.COST_CENTER_ID=cc.id
left join SCH_CENTRA_ID.TYPE_USERS tu on ud.TYPE_USER_ID=tu.ID
left join SCH_CENTRA_ID.TYPE_USERS stu on ud.SUBTYPE_USER_ID=stu.ID
left join SCH_CENTRA_ID.GLOBAL_PROFILES gp on ud.GLOBAL_PROFILE_ID=gp.ID
where ud.EMPLOYEE_STATUS='ACTIVO' and
ud.VALID=1
GO
/****** Object:  Table [SCH_CENTRA_ID].[MATRICES]    Script Date: 07/04/2020 11:56:54 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [SCH_CENTRA_ID].[MATRICES](
	[ID] [bigint] IDENTITY(1,1) NOT NULL,
	[CODE] [nvarchar](20) NOT NULL,
	[NAME] [nvarchar](100) NOT NULL,
	[APPLICATION_GROUP_ID] [bigint] NOT NULL,
	[VALID] [int] NOT NULL,
	[QUANTITY] [int] NOT NULL,
 CONSTRAINT [MATRICES_PK] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 85) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [SCH_CENTRA_ID].[MATRICES_DETAIL]    Script Date: 07/04/2020 11:56:54 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [SCH_CENTRA_ID].[MATRICES_DETAIL](
	[ID] [bigint] IDENTITY(1,1) NOT NULL,
	[CODE] [nvarchar](20) NOT NULL,
	[NAME] [nvarchar](100) NOT NULL,
	[MATRIX_ID] [bigint] NOT NULL,
	[VALID] [int] NOT NULL,
 CONSTRAINT [MATRICES_DETAIL_PK] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 85) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [SCH_CENTRA_ID].[TEMPLATE_PROFILES_MATRICES]    Script Date: 07/04/2020 11:56:54 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [SCH_CENTRA_ID].[TEMPLATE_PROFILES_MATRICES](
	[ID] [bigint] IDENTITY(1,1) NOT NULL,
	[MATRIX_ID] [bigint] NOT NULL,
	[VALID] [int] NOT NULL,
	[TRANSACTIONAL_PROFILE_ID] [bigint] NOT NULL,
 CONSTRAINT [TEMPLATE_PROFILES_MATRICES_PK] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 85) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [SCH_CENTRA_ID].[TEMPLATE_PROFILES_MATRICES_DETAIL]    Script Date: 07/04/2020 11:56:54 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [SCH_CENTRA_ID].[TEMPLATE_PROFILES_MATRICES_DETAIL](
	[ID] [bigint] IDENTITY(1,1) NOT NULL,
	[TEMPLATE_PROFILE_MATRIX_GROUP_ID] [bigint] NOT NULL,
	[MATRIX_DETAIL_ID] [bigint] NOT NULL,
	[VALUE] [nvarchar](100) NULL,
	[VALID] [int] NOT NULL,
 CONSTRAINT [TEMPLATE_PROFILES_MATRICES_DETAIL_PK] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 85) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [SCH_CENTRA_ID].[TEMPLATE_PROFILES_MATRICES_GROUP]    Script Date: 07/04/2020 11:56:54 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [SCH_CENTRA_ID].[TEMPLATE_PROFILES_MATRICES_GROUP](
	[ID] [bigint] IDENTITY(1,1) NOT NULL,
	[TEMPLATE_PROFILE_MATRIX_ID] [bigint] NOT NULL,
	[VALID] [int] NOT NULL,
 CONSTRAINT [TEMPLATE_PROFILES_MATRICES_GROUP_PK] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 85) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  View [SCH_CENTRA_ID].[TEMPLATE_PROFILES_MATRIX_VW]    Script Date: 07/04/2020 11:56:54 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE VIEW [SCH_CENTRA_ID].[TEMPLATE_PROFILES_MATRIX_VW] (ID, TRANSACTIONAL_PROFILE_ID, FIELD_CODE, FIELD_NAME, FIELD_DETAIL_CODE, FIELD_DETAIL_NAME, FIELD_DETAIL_VALUE, APPLICATION_CODE, VALID,GROUPER) AS select 
tpmd.ID,
tpm.TRANSACTIONAL_PROFILE_ID,
m.CODE FIELD_CODE,
m.NAME FIELD_NAME,
md.CODE FIELD_DETAIL_CODE,
md.NAME FIELD_DETAIL_NAME,
tpmd.VALUE FIELD_DETAIL_VALUE,
apg.CODE APPLICATION_CODE,
tpmd.VALID,
tpmg.ID GROUPER
from SCH_CENTRA_ID.TEMPLATE_PROFILES_MATRICES tpm
join SCH_CENTRA_ID.TEMPLATE_PROFILES_MATRICES_GROUP tpmg on tpmg.TEMPLATE_PROFILE_MATRIX_ID=tpm.ID
join SCH_CENTRA_ID.TEMPLATE_PROFILES_MATRICES_DETAIL tpmd on tpmd.TEMPLATE_PROFILE_MATRIX_GROUP_ID=tpmg.ID
join SCH_CENTRA_ID.MATRICES_DETAIL md on tpmd.MATRIX_DETAIL_ID=md.ID
join SCH_CENTRA_ID.MATRICES m on tpm.MATRIX_ID=m.ID
join SCH_CENTRA_ID.TRANSACTIONAL_PROFILES tr on  tr.ID=tpm.TRANSACTIONAL_PROFILE_ID
join SCH_CENTRA_ID.APPLICATIONS ap on ap.id=tr.application_id
join SCH_CENTRA_ID.APPLICATIONS_GROUP apg on apg.id=ap.APPLICATION_GROUP_ID
WHERE TPM.VALID=1 AND tpmg.VALID=1 AND tpmd.VALID=1
GO
/****** Object:  View [SCH_CENTRA_ID].[TEMPLATE_PROFILES_VW]    Script Date: 07/04/2020 11:56:54 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE VIEW [SCH_CENTRA_ID].[TEMPLATE_PROFILES_VW] (ID, FIELD_CODE, FIELD_NAME, FIELD_VALUE, TRANSACTIONAL_PROFILE_ID, APPLICATION_CODE, VALID) AS 
SELECT 
tp.ID,
f.CODE FIELD_CODE,
f.NAME FIELD_NAME,
tp.FIELD_VALUE FIELD_VALUE,
tp.TRANSACTIONAL_PROFILE_ID,
apg.CODE APPLICATION_CODE,
tp.VALID
FROM SCH_CENTRA_ID.TEMPLATE_PROFILES tp
left join SCH_CENTRA_ID.FIELDS f on tp.FIELD_ID=f.ID
left join SCH_CENTRA_ID.TRANSACTIONAL_PROFILES tr on  tr.ID=tp.TRANSACTIONAL_PROFILE_ID
left join SCH_CENTRA_ID.APPLICATIONS ap on ap.id=tr.application_id
left join SCH_CENTRA_ID.APPLICATIONS_GROUP apg on apg.id=ap.APPLICATION_GROUP_ID
GO
/****** Object:  Table [SCH_CENTRA_ID].[CATALOGS_HIERARCHIES]    Script Date: 07/04/2020 11:56:54 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [SCH_CENTRA_ID].[CATALOGS_HIERARCHIES](
	[ID] [bigint] IDENTITY(1,1) NOT NULL,
	[CATALOG_TYPE_ID] [bigint] NOT NULL,
	[CATALOG_COMPANY_TYPE_ID] [bigint] NOT NULL,
	[PARENT_ID] [bigint] NULL,
	[VALID] [int] NOT NULL,
 CONSTRAINT [HIERARCHIES_PK] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 85) ON [PRIMARY],
 CONSTRAINT [HIERARCHIES_UX] UNIQUE NONCLUSTERED 
(
	[CATALOG_TYPE_ID] ASC,
	[CATALOG_COMPANY_TYPE_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 85) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [SCH_CENTRA_ID].[CATALOGS_TYPES]    Script Date: 07/04/2020 11:56:54 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [SCH_CENTRA_ID].[CATALOGS_TYPES](
	[ID] [bigint] IDENTITY(1,1) NOT NULL,
	[CODE] [nvarchar](20) NOT NULL,
	[NAME] [nvarchar](100) NOT NULL,
	[SORT_TYPE] [nvarchar](1) NOT NULL,
	[EDITABLE] [int] NOT NULL,
	[VALID] [int] NOT NULL,
	[description] [nvarchar](400) NULL,
 CONSTRAINT [TYPES_CATALOGS_PK] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 85) ON [PRIMARY],
 CONSTRAINT [TYPES_CATALOGS_UX] UNIQUE NONCLUSTERED 
(
	[CODE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 85) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [SCH_CENTRA_ID].[CHALLENGE_QUESTIONS]    Script Date: 07/04/2020 11:56:55 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [SCH_CENTRA_ID].[CHALLENGE_QUESTIONS](
	[ID] [bigint] IDENTITY(1,1) NOT NULL,
	[USERNAME] [nvarchar](60) NOT NULL,
	[ANSWER1] [nvarchar](60) NOT NULL,
	[ANSWER2] [nvarchar](60) NOT NULL,
	[ANSWER3] [nvarchar](60) NOT NULL,
	[ANSWER4] [nvarchar](60) NOT NULL,
	[CREATED_DATE] [datetime] NOT NULL,
	[ATTENTION_DATE] [datetime] NULL,
	[STATUS] [nvarchar](3) NOT NULL,
	[VALID] [int] NOT NULL,
	[CODE1] [nvarchar](10) NULL,
	[CODE2] [nvarchar](10) NULL,
	[CODE3] [nvarchar](10) NULL,
	[CODE4] [nvarchar](10) NULL,
 CONSTRAINT [CHALLENGE_QUESTIONS_PK] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 85) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [SCH_CENTRA_ID].[COMPANIES_STRUCTURES]    Script Date: 07/04/2020 11:56:55 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [SCH_CENTRA_ID].[COMPANIES_STRUCTURES](
	[ID] [bigint] IDENTITY(1,1) NOT NULL,
	[COMPANY_ID] [bigint] NOT NULL,
	[CATALOG_ORGANIZATIONAL_STRUCTURE_ID] [bigint] NOT NULL,
	[parent_id] [bigint] NULL,
	[VALID] [int] NOT NULL,
	[COMPANY_CODE] [varchar](20) NULL,
	[CATALOG_CODE] [varchar](20) NULL,
	[CATALOG_TYPE_CODE] [varchar](20) NULL,
 CONSTRAINT [ORGANIZATIONS_STRUCTURES_PK] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 85) ON [PRIMARY],
 CONSTRAINT [COMPANIES_STRUCTURES_UK] UNIQUE NONCLUSTERED 
(
	[COMPANY_ID] ASC,
	[CATALOG_ORGANIZATIONAL_STRUCTURE_ID] ASC,
	[parent_id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 85) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [SCH_CENTRA_ID].[DISTRIBUTION_LIST]    Script Date: 07/04/2020 11:56:55 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [SCH_CENTRA_ID].[DISTRIBUTION_LIST](
	[ID] [bigint] IDENTITY(1,1) NOT NULL,
	[CODE] [nvarchar](20) NOT NULL,
	[NAME] [nvarchar](100) NOT NULL,
	[VALID] [int] NOT NULL,
 CONSTRAINT [DISTRIBUTION_LIST_PK] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 85) ON [PRIMARY],
 CONSTRAINT [DISTRIBUTION_LIST_UK] UNIQUE NONCLUSTERED 
(
	[CODE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 85) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [SCH_CENTRA_ID].[DISTRIBUTION_LIST_DETAIL]    Script Date: 07/04/2020 11:56:55 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [SCH_CENTRA_ID].[DISTRIBUTION_LIST_DETAIL](
	[ID] [bigint] IDENTITY(1,1) NOT NULL,
	[MAIL] [nvarchar](100) NOT NULL,
	[DISTRIBUTION_LIST_ID] [bigint] NOT NULL,
	[VALID] [int] NOT NULL,
 CONSTRAINT [DISTRIBUTION_LIST_DETAIL_PK] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 85) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [SCH_CENTRA_ID].[GLOBAL_PARAMETERS]    Script Date: 07/04/2020 11:56:55 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [SCH_CENTRA_ID].[GLOBAL_PARAMETERS](
	[ID] [bigint] IDENTITY(1,1) NOT NULL,
	[CODE] [nvarchar](20) NOT NULL,
	[NAME] [nvarchar](100) NOT NULL,
	[DESCRIPTION] [nvarchar](500) NOT NULL,
	[TYPE] [nvarchar](1) NOT NULL,
	[VALUE_TEXT] [nvarchar](500) NULL,
	[VALUE_NUMBER] [numeric](10, 2) NULL,
	[VALUE_DATE] [datetime] NULL,
	[VALUE_BOOLEAN] [int] NULL,
	[VALID] [int] NOT NULL,
	[FILTER] [text] NULL,
 CONSTRAINT [GLOBAL_PARAMETERS_PK] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 85) ON [PRIMARY],
 CONSTRAINT [GLOBAL_PARAMETERS_NAME_UK] UNIQUE NONCLUSTERED 
(
	[NAME] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 85) ON [PRIMARY],
 CONSTRAINT [GLOBAL_PARAMETERS_UX] UNIQUE NONCLUSTERED 
(
	[CODE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 85) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [SCH_CENTRA_ID].[GUIDS]    Script Date: 07/04/2020 11:56:55 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [SCH_CENTRA_ID].[GUIDS](
	[ID] [bigint] IDENTITY(1,1) NOT NULL,
	[GUID] [nvarchar](50) NOT NULL,
	[CREATED] [datetime] NOT NULL,
	[EVENT] [nvarchar](100) NOT NULL,
 CONSTRAINT [GUIDS_PK] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 85) ON [PRIMARY],
 CONSTRAINT [GUIDS_UK] UNIQUE NONCLUSTERED 
(
	[GUID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 85) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [SCH_CENTRA_ID].[HISTORY_SCOPE_RULES]    Script Date: 07/04/2020 11:56:55 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [SCH_CENTRA_ID].[HISTORY_SCOPE_RULES](
	[ID] [bigint] IDENTITY(1,1) NOT NULL,
	[GLOBAL_PROFILE_ID] [bigint] NOT NULL,
	[SCOPE_RULES_WHO] [nvarchar](400) NOT NULL,
	[SCOPE_RULES_THAT] [nvarchar](400) NOT NULL,
	[DATE_CREATED] [date] NOT NULL,
	[DATE_DELETED] [date] NULL,
	[VALID] [int] NOT NULL,
	[USER_CREATED] [nvarchar](20) NOT NULL,
	[USER_DELETED] [nvarchar](20) NULL,
 CONSTRAINT [HISTORY_SCOPE_RULES_PK] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 85) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [SCH_CENTRA_ID].[MASSIVE_PROCESS]    Script Date: 07/04/2020 11:56:55 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [SCH_CENTRA_ID].[MASSIVE_PROCESS](
	[ID] [bigint] IDENTITY(1,1) NOT NULL,
	[JSON] [text] NOT NULL,
	[STATE] [nvarchar](1) NOT NULL,
	[RESULT] [nvarchar](1) NOT NULL,
	[OBSERVATIONS] [text] NULL,
	[TYPE_ACTION] [nvarchar](1) NOT NULL,
	[VALID] [int] NOT NULL,
	[USERNAME] [nvarchar](50) NULL,
	[CODIGO_TRABAJADOR] [nvarchar](50) NULL,
	[APELLIDOS_EMPLEADO] [nvarchar](200) NULL,
	[NOMBRES_EMPLEADO] [nvarchar](200) NULL,
	[IDENTIFICACION] [nvarchar](50) NULL,
	[IDENTIFICACION_SUPERVISOR] [nvarchar](50) NULL,
	[NOMBRE_SUPERVISOR] [nvarchar](200) NULL,
	[CODIGO_COMPANIA] [nvarchar](50) NULL,
	[NOMBRE_COMPANIA] [nvarchar](200) NULL,
	[CODIGO_AGRUPACION] [nvarchar](50) NULL,
	[NOMBRE_AGRUPACION] [nvarchar](200) NULL,
	[CODIGO_DIVISION] [nvarchar](50) NULL,
	[NOMBRE_DIVISION] [nvarchar](200) NULL,
	[CODIGO_DEPARTAMENTO] [nvarchar](50) NULL,
	[NOMBRE_DEPARTAMENTO] [nvarchar](200) NULL,
	[CODIGO_AREA] [nvarchar](50) NULL,
	[NOMBRE_AREA] [nvarchar](200) NULL,
	[CODIGO_SUCURSAL] [nvarchar](50) NULL,
	[NOMBRE_SUCURSAL] [nvarchar](200) NULL,
	[CODIGO_CENTRO_COSTO] [nvarchar](50) NULL,
	[NOMBRE_CENTRO_COSTO] [nvarchar](200) NULL,
	[NOMBRE_LOCALIDAD] [nvarchar](200) NULL,
	[NOMBRE_CARGO] [nvarchar](200) NULL,
	[CODIGO_NIVEL_JERARQUICO] [nvarchar](50) NULL,
	[NOMBRE_NIVEL_JERARQUICO] [nvarchar](200) NULL,
	[NUMERO_CUENTA_DEPOSITO] [nvarchar](50) NULL,
	[FECHA_INGRESO_EMPLEADO] [nvarchar](30) NULL,
	[FECHA_SALIDA_EMPLEADO] [nvarchar](30) NULL,
	[ESTADO_EMPLEADO] [nvarchar](50) NULL,
	[CODIGO_EMPLEADO] [nvarchar](50) NULL,
	[TIPO_USUARIO] [nvarchar](50) NULL,
	[SUB_TIPO] [nvarchar](50) NULL,
	[FECHA_REGISTRO] [datetime] NOT NULL,
	[GUID] [nvarchar](50) NOT NULL,
	[TYPE_EVENT] [nvarchar](1) NOT NULL,
	[FECHA_DATOS] [datetime] NOT NULL,
	[UUID] [nvarchar](50) NOT NULL,
	[MODIFICA_DATOS] [int] NOT NULL,
	[RECALCULO_PERFIL] [int] NOT NULL,
	[FECHA_PROVISIONAMIENTO] [datetime] NULL,
	[CELULAR] [nvarchar](20) NULL,
	[GLOBAL_PROFILE_ID] [bigint] NULL,
	[GLOBAL_PROFILE_CODE] [nvarchar](20) NULL,
	[GLOBAL_PROFILE_NAME] [nvarchar](100) NULL,
	[GLOBAL_PROFILE_DUPLICATE] [nvarchar](100) NULL,
	[GLOBAL_PROFILE_ERROR] [nvarchar](1) NULL,
 CONSTRAINT [MASSIVE_PROCESS_PK] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 85) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [SCH_CENTRA_ID].[MASSIVE_PROCESS_PROBLEMS]    Script Date: 07/04/2020 11:56:55 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [SCH_CENTRA_ID].[MASSIVE_PROCESS_PROBLEMS](
	[ID] [bigint] IDENTITY(1,1) NOT NULL,
	[JSON] [text] NOT NULL,
	[OBSERVATIONS] [text] NOT NULL,
	[FECHA] [datetime] NOT NULL,
	[GUID] [nvarchar](50) NULL,
 CONSTRAINT [MASSIVE_PROCESS_PROBLEMS_PK] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 85) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [SCH_CENTRA_ID].[MENUS]    Script Date: 07/04/2020 11:56:55 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [SCH_CENTRA_ID].[MENUS](
	[ID] [bigint] IDENTITY(1,1) NOT NULL,
	[TITLE] [nvarchar](100) NOT NULL,
	[TRANSLATE] [nvarchar](100) NOT NULL,
	[TYPE] [nvarchar](10) NOT NULL,
	[ICON] [nvarchar](20) NOT NULL,
	[URL] [nvarchar](200) NOT NULL,
	[APP] [nvarchar](20) NOT NULL,
	[PERMISSION] [nvarchar](100) NOT NULL,
	[VALID] [int] NOT NULL,
 CONSTRAINT [MENUS_PK] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 85) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [SCH_CENTRA_ID].[MGI_REPROCESO]    Script Date: 07/04/2020 11:56:55 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [SCH_CENTRA_ID].[MGI_REPROCESO](
	[GUID] [varchar](50) NOT NULL,
	[FECHA_INGRESO] [datetime] NOT NULL,
	[ID_MENSAJE] [varchar](50) NOT NULL,
	[ESTADO] [varchar](16) NULL,
	[USER_STORE] [varchar](16) NOT NULL,
	[MENSAJE_PETICION] [text] NOT NULL,
	[MENSAJE_RESPUESTA] [text] NULL,
	[PRIORIDAD] [tinyint] NOT NULL,
	[REINTENTO] [tinyint] NOT NULL,
	[SOAP_ACTION] [text] NULL,
	[STATUS_COD_RESP] [varchar](10) NULL,
	[MENSAJE_PETICION_VALORES] [text] NULL,
	[MENSAJE_RESPUESTA_VALORES] [text] NULL,
	[ULTIMA_FECHA_REINTENTO] [datetime] NULL,
	[HP_TICKET_NUMERO] [varchar](50) NULL,
	[HP_TICKET_CONTENIDO] [text] NULL,
	[HP_TICKET_FECHA_RESPUESTA] [datetime] NULL,
	[HP_TICKET_ESTADO] [varchar](20) NULL,
	[HP_TICKET_LOGS] [text] NULL,
	[UUID_GI] [varchar](50) NULL,
	[ID] [bigint] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 85) ON [PRIMARY],
 CONSTRAINT [MGIREPROCESO_GUID] UNIQUE NONCLUSTERED 
(
	[GUID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 85) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [SCH_CENTRA_ID].[OPERATIONS_PROVISIONING]    Script Date: 07/04/2020 11:56:55 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [SCH_CENTRA_ID].[OPERATIONS_PROVISIONING](
	[ID] [bigint] IDENTITY(1,1) NOT NULL,
	[TRANSACTIONAL_IDENTITY_ID] [bigint] NOT NULL,
	[GLOBAL_PROFILE_ID] [bigint] NOT NULL,
	[USER_DATA_ID] [bigint] NOT NULL,
	[CREATED_DATE] [datetime] NOT NULL,
	[PROFILE_START_DATE] [datetime] NOT NULL,
	[PROFILE_END_DATE] [datetime] NULL,
	[START_DATE] [datetime] NOT NULL,
	[END_DATE] [datetime] NULL,
	[MODIFY_DATA] [int] NOT NULL,
	[PROFILE_RECALCULATION] [int] NOT NULL,
	[STATUS] [nvarchar](20) NOT NULL,
	[VALID] [int] NOT NULL,
 CONSTRAINT [USER_PROFILE_TRANSACTIONAL_HISTORY_PK] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 85) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [SCH_CENTRA_ID].[PROCESS]    Script Date: 07/04/2020 11:56:55 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [SCH_CENTRA_ID].[PROCESS](
	[ID] [bigint] IDENTITY(1,1) NOT NULL,
	[CODE] [nvarchar](20) NOT NULL,
	[NAME] [nvarchar](100) NOT NULL,
	[DESCRIPTION] [nvarchar](500) NOT NULL,
	[VALID] [int] NOT NULL,
 CONSTRAINT [PROCESS_PK] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 85) ON [PRIMARY],
 CONSTRAINT [PROCESS_UK] UNIQUE NONCLUSTERED 
(
	[CODE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 85) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [SCH_CENTRA_ID].[PROCESS_DISTRIBUTION_LIST]    Script Date: 07/04/2020 11:56:55 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [SCH_CENTRA_ID].[PROCESS_DISTRIBUTION_LIST](
	[ID] [bigint] IDENTITY(1,1) NOT NULL,
	[DISTRIBUTION_LIST_ID] [bigint] NOT NULL,
	[PROCESS_ID] [bigint] NOT NULL,
	[VALID] [int] NOT NULL,
 CONSTRAINT [PROCESS_DISTRIBUTION_LIST_PK] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 85) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [SCH_CENTRA_ID].[REST_USER_STORE_SCIM]    Script Date: 07/04/2020 11:56:55 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [SCH_CENTRA_ID].[REST_USER_STORE_SCIM](
	[ID] [bigint] IDENTITY(1,1) NOT NULL,
	[USERNAME] [nvarchar](25) NOT NULL,
	[SCIM] [nvarchar](255) NOT NULL,
	[DOMAIN] [nvarchar](255) NOT NULL,
	[VALID] [int] NOT NULL,
	[TELLER_NUMBER] [nvarchar](50) NULL,
	[TELLER_NAME] [nvarchar](50) NULL,
 CONSTRAINT [REST_USER_STORE_SCIM_PK] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 85) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [SCH_CENTRA_ID].[TAKS_PROVISIONING]    Script Date: 07/04/2020 11:56:55 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [SCH_CENTRA_ID].[TAKS_PROVISIONING](
	[ID] [bigint] IDENTITY(1,1) NOT NULL,
	[OPERATION_PROVISIONING_ID] [bigint] NOT NULL,
	[TRANSACTIONAL_PROFILE_ID] [bigint] NOT NULL,
	[APPLICATION_ID] [bigint] NOT NULL,
	[PROVISIONING_DATE] [datetime] NULL,
	[PROVISIONING_STATUS] [nvarchar](20) NOT NULL,
	[PROVISIONING_COMMENTS] [nvarchar](400) NULL,
	[STATUS] [nvarchar](20) NOT NULL,
	[ACTION] [nvarchar](20) NOT NULL,
	[CREATION_DATE] [datetime] NOT NULL,
	[VALID] [int] NOT NULL,
	[UUID] [nvarchar](100) NULL,
	[UUID_PARENT] [nvarchar](100) NULL,
	[TICKET_NUMBER] [nvarchar](20) NULL,
	[TICKET_CONTENT] [text] NULL,
	[TICKET_ERROR] [text] NULL,
	[RETRY_NUMBER] [int] NULL,
	[RETRY_LAST_DATE] [datetime] NULL,
	[TYPE] [nvarchar](3) NULL,
	[TICKET_DATE] [datetime] NULL,
 CONSTRAINT [USER_ACTION_PROFILE_TRANSACTIONAL_PK] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 85) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [SCH_CENTRA_ID].[TAKS_PROVISIONING_HISTORY]    Script Date: 07/04/2020 11:56:55 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [SCH_CENTRA_ID].[TAKS_PROVISIONING_HISTORY](
	[ID] [bigint] IDENTITY(1,1) NOT NULL,
	[TASK_PROVISIONING_ID] [bigint] NOT NULL,
	[STATUS] [nvarchar](100) NOT NULL,
	[CREATION_DATE] [datetime] NOT NULL,
	[VALID] [int] NOT NULL,
	[RETRY_NUMBER] [int] NULL,
	[RETRY_DATE] [datetime] NULL,
 CONSTRAINT [TAKS_PROVISIONING_HISTORY_PK] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 85) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [SCH_CENTRA_ID].[TRANSACTIONAL_IDENTITY]    Script Date: 07/04/2020 11:56:55 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [SCH_CENTRA_ID].[TRANSACTIONAL_IDENTITY](
	[ID] [bigint] IDENTITY(1,1) NOT NULL,
	[UUID] [nvarchar](50) NOT NULL,
	[GUID] [nvarchar](50) NOT NULL,
	[USERNAME] [nvarchar](50) NULL,
	[WORKER_CODE] [nvarchar](50) NULL,
	[EMPLOYEE_LASTNAME] [nvarchar](200) NULL,
	[EMPLOYEE_FIRSTNAME] [nvarchar](200) NULL,
	[IDENTIFICATION] [nvarchar](60) NULL,
	[IDENTIFICATION_SUPERVISOR] [nvarchar](60) NULL,
	[NAMES_SUPERVISOR] [nvarchar](200) NULL,
	[COMPANY_CODE] [nvarchar](50) NULL,
	[COMPANY_NAME] [nvarchar](200) NULL,
	[GROUP_CODE] [nvarchar](50) NULL,
	[GROUP_NAME] [nvarchar](200) NULL,
	[DIVISION_CODE] [nvarchar](50) NULL,
	[DIVISION_NAME] [nvarchar](200) NULL,
	[DEPARTMENT_CODE] [nvarchar](50) NULL,
	[DEPARTMENT_NAME] [nvarchar](200) NULL,
	[AREA_CODE] [nvarchar](50) NULL,
	[AREA_NAME] [nvarchar](200) NULL,
	[SUBSIDIARY_CODE] [nvarchar](50) NULL,
	[SUBSIDIARY_NAME] [nvarchar](200) NULL,
	[COST_CENTER_CODE] [nvarchar](50) NULL,
	[COST_CENTER_NAME] [nvarchar](200) NULL,
	[LOCATION_CODE] [nvarchar](200) NULL,
	[POSITION_NAME] [nvarchar](200) NULL,
	[HIERARCHICAL_LEVEL_CODE] [nvarchar](50) NULL,
	[HIERARCHICAL_LEVEL_NAME] [nvarchar](200) NULL,
	[DEPOSIT_ACCOUNT_NUMBER] [nvarchar](50) NULL,
	[EMPLOYEE_START_DATE] [nvarchar](50) NULL,
	[EMPLOYEE_END_DATE] [nvarchar](50) NULL,
	[EMPLOYEE_STATUS] [nvarchar](50) NULL,
	[EMPLOYEE_CODE] [nvarchar](50) NULL,
	[USER_TYPE] [nvarchar](50) NULL,
	[USER_SUBTYPE] [nvarchar](50) NULL,
	[MOBILE] [nvarchar](50) NULL,
	[ORIGEN] [nvarchar](20) NULL,
	[STATUS] [nvarchar](20) NOT NULL,
	[VALID] [int] NOT NULL,
	[CREATED_DATE] [datetime] NOT NULL,
	[PLANNED_EXECUTION_DATE] [datetime] NOT NULL,
	[MODIFY_DATA] [int] NOT NULL,
	[PROFILE_RECALCULATION] [int] NOT NULL,
	[LOCATION_NAME] [nvarchar](200) NULL,
	[TYPE_ACTION] [nvarchar](1) NULL,
	[GLOBAL_PROFILE_ID] [bigint] NULL,
	[USER_DATA_ID] [bigint] NULL,
	[MAIL] [nvarchar](100) NULL,
	[PASSWORD] [nvarchar](100) NULL,
	[IDENTIFICATION_TYPE] [nvarchar](20) NULL,
 CONSTRAINT [TRANSACTIONAL_IDENTITY_PK] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 85) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [SCH_CENTRA_ID].[USER_MIGRATION_ERRORS]    Script Date: 07/04/2020 11:56:55 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [SCH_CENTRA_ID].[USER_MIGRATION_ERRORS](
	[ID] [bigint] IDENTITY(1,1) NOT NULL,
	[USERNAME] [nvarchar](60) NOT NULL,
	[ERROR] [text] NOT NULL,
	[CREATED_DATE] [datetime] NOT NULL,
	[VALID] [int] NOT NULL,
 CONSTRAINT [USER_MIGRATION_ERRORS_PK] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 85) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [SCH_CENTRA_ID].[USER_MIGRATION_ERRORS2]    Script Date: 07/04/2020 11:56:55 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [SCH_CENTRA_ID].[USER_MIGRATION_ERRORS2](
	[ID] [bigint] IDENTITY(1,1) NOT NULL,
	[USERNAME] [nvarchar](60) NOT NULL,
	[ERROR] [text] NOT NULL,
	[CREATED_DATE] [datetime] NOT NULL,
	[VALID] [int] NOT NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [SCH_CENTRA_ID_AUDIT].[LOG_EXCEPTIONS]    Script Date: 07/04/2020 11:56:55 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [SCH_CENTRA_ID_AUDIT].[LOG_EXCEPTIONS](
	[ID] [bigint] IDENTITY(1,1) NOT NULL,
	[GUID] [nvarchar](50) NOT NULL,
	[CREATED_DATE] [datetime] NOT NULL,
	[APP_CALLED] [nvarchar](50) NOT NULL,
	[ACTION_CALLED] [nvarchar](500) NOT NULL,
	[JSON_INPUT] [text] NOT NULL,
	[EXCEPTION] [text] NOT NULL,
 CONSTRAINT [LOG_EXCEPTIONS_PK] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 85) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [SCH_CENTRA_ID_AUDIT].[LOG_PERFORMANCE]    Script Date: 07/04/2020 11:56:55 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [SCH_CENTRA_ID_AUDIT].[LOG_PERFORMANCE](
	[ID] [bigint] IDENTITY(1,1) NOT NULL,
	[GUID] [nvarchar](50) NOT NULL,
	[REQUEST_DATE] [datetime] NOT NULL,
	[RESPONSE_DATE] [datetime] NULL,
	[APP_CALLED] [nvarchar](50) NOT NULL,
	[ACTION_CALLED] [nvarchar](500) NOT NULL,
 CONSTRAINT [LOG_PERFORMANCE_PK] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 85) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [SCH_CENTRA_ID_AUDIT].[LOG_TRANSACTIONAL]    Script Date: 07/04/2020 11:56:55 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [SCH_CENTRA_ID_AUDIT].[LOG_TRANSACTIONAL](
	[ID] [bigint] IDENTITY(1,1) NOT NULL,
	[GUID] [nvarchar](50) NOT NULL,
	[TYPE] [nvarchar](1) NOT NULL,
	[APP_CALLED] [nvarchar](50) NOT NULL,
	[ACTION_CALLED] [nvarchar](500) NOT NULL,
	[DATE_CALLED] [datetime] NULL,
	[JSON_INPUT] [text] NOT NULL,
	[JSON_RESPONSE] [text] NOT NULL,
	[USERNAME] [nvarchar](50) NOT NULL,
	[STATUS] [nvarchar](50) NULL,
 CONSTRAINT [LOG_TRANSACTIONAL_PK] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 85) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Index [APPLICATIONS_ID_IDX]    Script Date: 07/04/2020 11:56:56 ******/
CREATE NONCLUSTERED INDEX [APPLICATIONS_ID_IDX] ON [SCH_CENTRA_ID].[APPLICATIONS]
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 85) ON [PRIMARY]
GO
/****** Object:  Index [APPLICATIONS_GROUP_ID_IDX]    Script Date: 07/04/2020 11:56:56 ******/
CREATE NONCLUSTERED INDEX [APPLICATIONS_GROUP_ID_IDX] ON [SCH_CENTRA_ID].[APPLICATIONS_GROUP]
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 85) ON [PRIMARY]
GO
SET ANSI_PADDING ON
GO
/****** Object:  Index [CATALOGS_CODE_IDX]    Script Date: 07/04/2020 11:56:56 ******/
CREATE NONCLUSTERED INDEX [CATALOGS_CODE_IDX] ON [SCH_CENTRA_ID].[CATALOGS]
(
	[CODE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 85) ON [PRIMARY]
GO
/****** Object:  Index [CATALOGS_ID_IDX]    Script Date: 07/04/2020 11:56:56 ******/
CREATE NONCLUSTERED INDEX [CATALOGS_ID_IDX] ON [SCH_CENTRA_ID].[CATALOGS]
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 85) ON [PRIMARY]
GO
/****** Object:  Index [CATALOGS_HIERARCHIES_ID_IDX]    Script Date: 07/04/2020 11:56:56 ******/
CREATE NONCLUSTERED INDEX [CATALOGS_HIERARCHIES_ID_IDX] ON [SCH_CENTRA_ID].[CATALOGS_HIERARCHIES]
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 85) ON [PRIMARY]
GO
/****** Object:  Index [CATALOGS_TYPES_ID_IDX]    Script Date: 07/04/2020 11:56:56 ******/
CREATE NONCLUSTERED INDEX [CATALOGS_TYPES_ID_IDX] ON [SCH_CENTRA_ID].[CATALOGS_TYPES]
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 85) ON [PRIMARY]
GO
SET ANSI_PADDING ON
GO
/****** Object:  Index [COMPANIES_CODE_IDX]    Script Date: 07/04/2020 11:56:56 ******/
CREATE NONCLUSTERED INDEX [COMPANIES_CODE_IDX] ON [SCH_CENTRA_ID].[COMPANIES]
(
	[CODE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 85) ON [PRIMARY]
GO
/****** Object:  Index [COMPANIES_ID_IDX]    Script Date: 07/04/2020 11:56:56 ******/
CREATE NONCLUSTERED INDEX [COMPANIES_ID_IDX] ON [SCH_CENTRA_ID].[COMPANIES]
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 85) ON [PRIMARY]
GO
/****** Object:  Index [COMPANIES_STRUCTURES_ID_IDX]    Script Date: 07/04/2020 11:56:56 ******/
CREATE NONCLUSTERED INDEX [COMPANIES_STRUCTURES_ID_IDX] ON [SCH_CENTRA_ID].[COMPANIES_STRUCTURES]
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 85) ON [PRIMARY]
GO
SET ANSI_PADDING ON
GO
/****** Object:  Index [COSTS_CENTERS_CODE_IDX]    Script Date: 07/04/2020 11:56:56 ******/
CREATE NONCLUSTERED INDEX [COSTS_CENTERS_CODE_IDX] ON [SCH_CENTRA_ID].[COSTS_CENTERS]
(
	[CODE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 85) ON [PRIMARY]
GO
/****** Object:  Index [COSTS_CENTERS_ID_IDX]    Script Date: 07/04/2020 11:56:56 ******/
CREATE NONCLUSTERED INDEX [COSTS_CENTERS_ID_IDX] ON [SCH_CENTRA_ID].[COSTS_CENTERS]
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 85) ON [PRIMARY]
GO
/****** Object:  Index [DEFAULT_PROFILES_ID_IDX]    Script Date: 07/04/2020 11:56:56 ******/
CREATE NONCLUSTERED INDEX [DEFAULT_PROFILES_ID_IDX] ON [SCH_CENTRA_ID].[DEFAULT_PROFILES]
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 85) ON [PRIMARY]
GO
/****** Object:  Index [DISTRIBUTION_LIST_ID_IDX]    Script Date: 07/04/2020 11:56:56 ******/
CREATE NONCLUSTERED INDEX [DISTRIBUTION_LIST_ID_IDX] ON [SCH_CENTRA_ID].[DISTRIBUTION_LIST]
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 85) ON [PRIMARY]
GO
/****** Object:  Index [DISTRIBUTION_LIST_DETAIL_ID_IDX]    Script Date: 07/04/2020 11:56:56 ******/
CREATE NONCLUSTERED INDEX [DISTRIBUTION_LIST_DETAIL_ID_IDX] ON [SCH_CENTRA_ID].[DISTRIBUTION_LIST_DETAIL]
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 85) ON [PRIMARY]
GO
/****** Object:  Index [FIELDS_ID_IDX]    Script Date: 07/04/2020 11:56:56 ******/
CREATE NONCLUSTERED INDEX [FIELDS_ID_IDX] ON [SCH_CENTRA_ID].[FIELDS]
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 85) ON [PRIMARY]
GO
/****** Object:  Index [GLOBAL_PARAMETERS_ID_IDX]    Script Date: 07/04/2020 11:56:56 ******/
CREATE NONCLUSTERED INDEX [GLOBAL_PARAMETERS_ID_IDX] ON [SCH_CENTRA_ID].[GLOBAL_PARAMETERS]
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 85) ON [PRIMARY]
GO
/****** Object:  Index [GLOBAL_PROFILES_ID_IDX]    Script Date: 07/04/2020 11:56:56 ******/
CREATE NONCLUSTERED INDEX [GLOBAL_PROFILES_ID_IDX] ON [SCH_CENTRA_ID].[GLOBAL_PROFILES]
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 85) ON [PRIMARY]
GO
/****** Object:  Index [GLOBAL_TRANSACTIONAL_PROFILES_ID_IDX]    Script Date: 07/04/2020 11:56:56 ******/
CREATE NONCLUSTERED INDEX [GLOBAL_TRANSACTIONAL_PROFILES_ID_IDX] ON [SCH_CENTRA_ID].[GLOBAL_TRANSACTIONAL_PROFILES]
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 85) ON [PRIMARY]
GO
/****** Object:  Index [GUIDS_ID_IDX]    Script Date: 07/04/2020 11:56:56 ******/
CREATE NONCLUSTERED INDEX [GUIDS_ID_IDX] ON [SCH_CENTRA_ID].[GUIDS]
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 85) ON [PRIMARY]
GO
/****** Object:  Index [HISTORY_SCOPE_RULES_ID_IDX]    Script Date: 07/04/2020 11:56:56 ******/
CREATE NONCLUSTERED INDEX [HISTORY_SCOPE_RULES_ID_IDX] ON [SCH_CENTRA_ID].[HISTORY_SCOPE_RULES]
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 85) ON [PRIMARY]
GO
/****** Object:  Index [MASSIVE_PROCESS_ID_IDX]    Script Date: 07/04/2020 11:56:56 ******/
CREATE NONCLUSTERED INDEX [MASSIVE_PROCESS_ID_IDX] ON [SCH_CENTRA_ID].[MASSIVE_PROCESS]
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 85) ON [PRIMARY]
GO
/****** Object:  Index [MASSIVE_PROCESS_PROBLEMS_ID_IDX]    Script Date: 07/04/2020 11:56:56 ******/
CREATE NONCLUSTERED INDEX [MASSIVE_PROCESS_PROBLEMS_ID_IDX] ON [SCH_CENTRA_ID].[MASSIVE_PROCESS_PROBLEMS]
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 85) ON [PRIMARY]
GO
/****** Object:  Index [MATRICES_ID_IDX]    Script Date: 07/04/2020 11:56:56 ******/
CREATE NONCLUSTERED INDEX [MATRICES_ID_IDX] ON [SCH_CENTRA_ID].[MATRICES]
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 85) ON [PRIMARY]
GO
/****** Object:  Index [MATRICES_DETAIL_ID_IDX]    Script Date: 07/04/2020 11:56:56 ******/
CREATE NONCLUSTERED INDEX [MATRICES_DETAIL_ID_IDX] ON [SCH_CENTRA_ID].[MATRICES_DETAIL]
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 85) ON [PRIMARY]
GO
/****** Object:  Index [MENUS_ID_IDX]    Script Date: 07/04/2020 11:56:56 ******/
CREATE NONCLUSTERED INDEX [MENUS_ID_IDX] ON [SCH_CENTRA_ID].[MENUS]
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 85) ON [PRIMARY]
GO
/****** Object:  Index [MGI_REPROCESO_ID_IDX]    Script Date: 07/04/2020 11:56:56 ******/
CREATE NONCLUSTERED INDEX [MGI_REPROCESO_ID_IDX] ON [SCH_CENTRA_ID].[MGI_REPROCESO]
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 85) ON [PRIMARY]
GO
/****** Object:  Index [OPERATIONS_PROVISIONING_ID_IDX]    Script Date: 07/04/2020 11:56:56 ******/
CREATE NONCLUSTERED INDEX [OPERATIONS_PROVISIONING_ID_IDX] ON [SCH_CENTRA_ID].[OPERATIONS_PROVISIONING]
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 85) ON [PRIMARY]
GO
/****** Object:  Index [PROCESS_ID_IDX]    Script Date: 07/04/2020 11:56:56 ******/
CREATE NONCLUSTERED INDEX [PROCESS_ID_IDX] ON [SCH_CENTRA_ID].[PROCESS]
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 85) ON [PRIMARY]
GO
/****** Object:  Index [PROCESS_DISTRIBUTION_LIST_ID_IDX]    Script Date: 07/04/2020 11:56:56 ******/
CREATE NONCLUSTERED INDEX [PROCESS_DISTRIBUTION_LIST_ID_IDX] ON [SCH_CENTRA_ID].[PROCESS_DISTRIBUTION_LIST]
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 85) ON [PRIMARY]
GO
/****** Object:  Index [REST_USER_STORE_SCIM_ID_IDX]    Script Date: 07/04/2020 11:56:56 ******/
CREATE NONCLUSTERED INDEX [REST_USER_STORE_SCIM_ID_IDX] ON [SCH_CENTRA_ID].[REST_USER_STORE_SCIM]
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 85) ON [PRIMARY]
GO
/****** Object:  Index [TAKS_PROVISIONING_ID_IDX]    Script Date: 07/04/2020 11:56:56 ******/
CREATE NONCLUSTERED INDEX [TAKS_PROVISIONING_ID_IDX] ON [SCH_CENTRA_ID].[TAKS_PROVISIONING]
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 85) ON [PRIMARY]
GO
/****** Object:  Index [TAKS_PROVISIONING_HISTORY_ID_IDX]    Script Date: 07/04/2020 11:56:56 ******/
CREATE NONCLUSTERED INDEX [TAKS_PROVISIONING_HISTORY_ID_IDX] ON [SCH_CENTRA_ID].[TAKS_PROVISIONING_HISTORY]
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 85) ON [PRIMARY]
GO
/****** Object:  Index [TEMPLATE_PROFILES_ID_IDX]    Script Date: 07/04/2020 11:56:56 ******/
CREATE NONCLUSTERED INDEX [TEMPLATE_PROFILES_ID_IDX] ON [SCH_CENTRA_ID].[TEMPLATE_PROFILES]
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 85) ON [PRIMARY]
GO
/****** Object:  Index [TEMPLATE_PROFILES_MATRICES_ID_IDX]    Script Date: 07/04/2020 11:56:56 ******/
CREATE NONCLUSTERED INDEX [TEMPLATE_PROFILES_MATRICES_ID_IDX] ON [SCH_CENTRA_ID].[TEMPLATE_PROFILES_MATRICES]
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 85) ON [PRIMARY]
GO
/****** Object:  Index [TEMPLATE_PROFILES_MATRICES_DETAIL_ID_IDX]    Script Date: 07/04/2020 11:56:56 ******/
CREATE NONCLUSTERED INDEX [TEMPLATE_PROFILES_MATRICES_DETAIL_ID_IDX] ON [SCH_CENTRA_ID].[TEMPLATE_PROFILES_MATRICES_DETAIL]
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 85) ON [PRIMARY]
GO
/****** Object:  Index [TEMPLATE_PROFILES_MATRICES_GROUP_ID_IDX]    Script Date: 07/04/2020 11:56:56 ******/
CREATE NONCLUSTERED INDEX [TEMPLATE_PROFILES_MATRICES_GROUP_ID_IDX] ON [SCH_CENTRA_ID].[TEMPLATE_PROFILES_MATRICES_GROUP]
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 85) ON [PRIMARY]
GO
/****** Object:  Index [TRANSACTIONAL_IDENTITY_ID_IDX]    Script Date: 07/04/2020 11:56:56 ******/
CREATE NONCLUSTERED INDEX [TRANSACTIONAL_IDENTITY_ID_IDX] ON [SCH_CENTRA_ID].[TRANSACTIONAL_IDENTITY]
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 85) ON [PRIMARY]
GO
/****** Object:  Index [TRANSACTIONAL_PROFILES_ID_IDX]    Script Date: 07/04/2020 11:56:56 ******/
CREATE NONCLUSTERED INDEX [TRANSACTIONAL_PROFILES_ID_IDX] ON [SCH_CENTRA_ID].[TRANSACTIONAL_PROFILES]
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 85) ON [PRIMARY]
GO
SET ANSI_PADDING ON
GO
/****** Object:  Index [TYPE_USERS_CODE_IDX]    Script Date: 07/04/2020 11:56:56 ******/
CREATE NONCLUSTERED INDEX [TYPE_USERS_CODE_IDX] ON [SCH_CENTRA_ID].[TYPE_USERS]
(
	[CODE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 85) ON [PRIMARY]
GO
/****** Object:  Index [TYPE_USERS_ID_IDX]    Script Date: 07/04/2020 11:56:56 ******/
CREATE NONCLUSTERED INDEX [TYPE_USERS_ID_IDX] ON [SCH_CENTRA_ID].[TYPE_USERS]
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 85) ON [PRIMARY]
GO
/****** Object:  Index [USERDATA_ID_IDX]    Script Date: 07/04/2020 11:56:56 ******/
CREATE NONCLUSTERED INDEX [USERDATA_ID_IDX] ON [SCH_CENTRA_ID].[USERDATA]
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 85) ON [PRIMARY]
GO
SET ANSI_PADDING ON
GO
/****** Object:  Index [USERDATA_IDENTIFICATION_IDX]    Script Date: 07/04/2020 11:56:56 ******/
CREATE NONCLUSTERED INDEX [USERDATA_IDENTIFICATION_IDX] ON [SCH_CENTRA_ID].[USERDATA]
(
	[IDENTIFICATION] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 85) ON [PRIMARY]
GO
SET ANSI_PADDING ON
GO
/****** Object:  Index [USERDATA_USERNAME_IDX]    Script Date: 07/04/2020 11:56:56 ******/
CREATE NONCLUSTERED INDEX [USERDATA_USERNAME_IDX] ON [SCH_CENTRA_ID].[USERDATA]
(
	[USERNAME] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 85) ON [PRIMARY]
GO
ALTER TABLE [SCH_CENTRA_ID].[DEFAULT_PROFILES] ADD  DEFAULT ('*') FOR [CODE_COMPANY]
GO
ALTER TABLE [SCH_CENTRA_ID].[DEFAULT_PROFILES] ADD  DEFAULT ('*') FOR [CODE_DIVISION]
GO
ALTER TABLE [SCH_CENTRA_ID].[DEFAULT_PROFILES] ADD  DEFAULT ('*') FOR [CODE_AREA]
GO
ALTER TABLE [SCH_CENTRA_ID].[DEFAULT_PROFILES] ADD  DEFAULT ('*') FOR [CODE_DEPARTMENT]
GO
ALTER TABLE [SCH_CENTRA_ID].[DEFAULT_PROFILES] ADD  DEFAULT ('*') FOR [CODE_POSITION]
GO
ALTER TABLE [SCH_CENTRA_ID].[TRANSACTIONAL_PROFILES] ADD  CONSTRAINT [CONFIGURED_Default_ForNotNullCol]  DEFAULT ((0)) FOR [CONFIGURED]
GO
ALTER TABLE [SCH_CENTRA_ID].[APPLICATIONS]  WITH CHECK ADD  CONSTRAINT [APPLICATIONS_APPLICATIONS_GROUP_FK] FOREIGN KEY([APPLICATION_GROUP_ID])
REFERENCES [SCH_CENTRA_ID].[APPLICATIONS_GROUP] ([ID])
GO
ALTER TABLE [SCH_CENTRA_ID].[APPLICATIONS] CHECK CONSTRAINT [APPLICATIONS_APPLICATIONS_GROUP_FK]
GO
ALTER TABLE [SCH_CENTRA_ID].[CATALOGS]  WITH CHECK ADD  CONSTRAINT [CATALOGS_TYPESCATALOGS_FK] FOREIGN KEY([catalog_type_id])
REFERENCES [SCH_CENTRA_ID].[CATALOGS_TYPES] ([ID])
GO
ALTER TABLE [SCH_CENTRA_ID].[CATALOGS] CHECK CONSTRAINT [CATALOGS_TYPESCATALOGS_FK]
GO
ALTER TABLE [SCH_CENTRA_ID].[CATALOGS_HIERARCHIES]  WITH CHECK ADD  CONSTRAINT [HIERARCHIES_CATALOGS_COMPANY_TYPE_FK] FOREIGN KEY([CATALOG_COMPANY_TYPE_ID])
REFERENCES [SCH_CENTRA_ID].[CATALOGS] ([ID])
GO
ALTER TABLE [SCH_CENTRA_ID].[CATALOGS_HIERARCHIES] CHECK CONSTRAINT [HIERARCHIES_CATALOGS_COMPANY_TYPE_FK]
GO
ALTER TABLE [SCH_CENTRA_ID].[CATALOGS_HIERARCHIES]  WITH CHECK ADD  CONSTRAINT [HIERARCHIES_HIERARCHIES_FK] FOREIGN KEY([PARENT_ID])
REFERENCES [SCH_CENTRA_ID].[CATALOGS_HIERARCHIES] ([ID])
GO
ALTER TABLE [SCH_CENTRA_ID].[CATALOGS_HIERARCHIES] CHECK CONSTRAINT [HIERARCHIES_HIERARCHIES_FK]
GO
ALTER TABLE [SCH_CENTRA_ID].[CATALOGS_HIERARCHIES]  WITH CHECK ADD  CONSTRAINT [HIERARCHIES_TYPES_CATALOGS_FK] FOREIGN KEY([CATALOG_TYPE_ID])
REFERENCES [SCH_CENTRA_ID].[CATALOGS_TYPES] ([ID])
GO
ALTER TABLE [SCH_CENTRA_ID].[CATALOGS_HIERARCHIES] CHECK CONSTRAINT [HIERARCHIES_TYPES_CATALOGS_FK]
GO
ALTER TABLE [SCH_CENTRA_ID].[COMPANIES]  WITH CHECK ADD  CONSTRAINT [COMPANIES_CATALOGS_COMPANY_TYPE_FK] FOREIGN KEY([CATALOG_COMPANY_TYPE_ID])
REFERENCES [SCH_CENTRA_ID].[CATALOGS] ([ID])
GO
ALTER TABLE [SCH_CENTRA_ID].[COMPANIES] CHECK CONSTRAINT [COMPANIES_CATALOGS_COMPANY_TYPE_FK]
GO
ALTER TABLE [SCH_CENTRA_ID].[COMPANIES_STRUCTURES]  WITH CHECK ADD  CONSTRAINT [ORGANIZATIONSSTRUCTURES_CATALOGSORGANIZATIONALSTRUCTURE_FK] FOREIGN KEY([CATALOG_ORGANIZATIONAL_STRUCTURE_ID])
REFERENCES [SCH_CENTRA_ID].[CATALOGS] ([ID])
GO
ALTER TABLE [SCH_CENTRA_ID].[COMPANIES_STRUCTURES] CHECK CONSTRAINT [ORGANIZATIONSSTRUCTURES_CATALOGSORGANIZATIONALSTRUCTURE_FK]
GO
ALTER TABLE [SCH_CENTRA_ID].[COMPANIES_STRUCTURES]  WITH CHECK ADD  CONSTRAINT [ORGANIZATIONSSTRUCTURES_COMPANIES_FK] FOREIGN KEY([COMPANY_ID])
REFERENCES [SCH_CENTRA_ID].[COMPANIES] ([ID])
GO
ALTER TABLE [SCH_CENTRA_ID].[COMPANIES_STRUCTURES] CHECK CONSTRAINT [ORGANIZATIONSSTRUCTURES_COMPANIES_FK]
GO
ALTER TABLE [SCH_CENTRA_ID].[COMPANIES_STRUCTURES]  WITH CHECK ADD  CONSTRAINT [ORGANIZATIONSSTRUCTURES_ORGANIZATIONSSTRUCTURES_FK] FOREIGN KEY([parent_id])
REFERENCES [SCH_CENTRA_ID].[COMPANIES_STRUCTURES] ([ID])
GO
ALTER TABLE [SCH_CENTRA_ID].[COMPANIES_STRUCTURES] CHECK CONSTRAINT [ORGANIZATIONSSTRUCTURES_ORGANIZATIONSSTRUCTURES_FK]
GO
ALTER TABLE [SCH_CENTRA_ID].[COSTS_CENTERS]  WITH CHECK ADD  CONSTRAINT [COSTSCENTERS_COMPANIES_FK] FOREIGN KEY([COMPANY_ID])
REFERENCES [SCH_CENTRA_ID].[COMPANIES] ([ID])
GO
ALTER TABLE [SCH_CENTRA_ID].[COSTS_CENTERS] CHECK CONSTRAINT [COSTSCENTERS_COMPANIES_FK]
GO
ALTER TABLE [SCH_CENTRA_ID].[COSTS_CENTERS]  WITH CHECK ADD  CONSTRAINT [COSTSCENTERS_COSTSCENTERS_FK] FOREIGN KEY([parent_id])
REFERENCES [SCH_CENTRA_ID].[COSTS_CENTERS] ([ID])
GO
ALTER TABLE [SCH_CENTRA_ID].[COSTS_CENTERS] CHECK CONSTRAINT [COSTSCENTERS_COSTSCENTERS_FK]
GO
ALTER TABLE [SCH_CENTRA_ID].[DEFAULT_PROFILES]  WITH CHECK ADD  CONSTRAINT [DEFAULT_PROFILES_GLOBAL_PROFILES_FK] FOREIGN KEY([GLOBAL_PROFILE_ID])
REFERENCES [SCH_CENTRA_ID].[GLOBAL_PROFILES] ([ID])
GO
ALTER TABLE [SCH_CENTRA_ID].[DEFAULT_PROFILES] CHECK CONSTRAINT [DEFAULT_PROFILES_GLOBAL_PROFILES_FK]
GO
ALTER TABLE [SCH_CENTRA_ID].[DISTRIBUTION_LIST_DETAIL]  WITH CHECK ADD  CONSTRAINT [DISTRIBUTIONLISTDETAIL_DISTRIBUTIONLIST_FK] FOREIGN KEY([DISTRIBUTION_LIST_ID])
REFERENCES [SCH_CENTRA_ID].[DISTRIBUTION_LIST] ([ID])
GO
ALTER TABLE [SCH_CENTRA_ID].[DISTRIBUTION_LIST_DETAIL] CHECK CONSTRAINT [DISTRIBUTIONLISTDETAIL_DISTRIBUTIONLIST_FK]
GO
ALTER TABLE [SCH_CENTRA_ID].[FIELDS]  WITH CHECK ADD  CONSTRAINT [FIELDS_APPLICATIONS_GROUP_FK] FOREIGN KEY([APPLICATION_GROUP_ID])
REFERENCES [SCH_CENTRA_ID].[APPLICATIONS_GROUP] ([ID])
GO
ALTER TABLE [SCH_CENTRA_ID].[FIELDS] CHECK CONSTRAINT [FIELDS_APPLICATIONS_GROUP_FK]
GO
ALTER TABLE [SCH_CENTRA_ID].[GLOBAL_PROFILES]  WITH CHECK ADD  CONSTRAINT [GLOBALPROFILES_CATALOGS_POSITION_OWNER_FK] FOREIGN KEY([CATALOG_POSITION_OWNER_ID])
REFERENCES [SCH_CENTRA_ID].[CATALOGS] ([ID])
GO
ALTER TABLE [SCH_CENTRA_ID].[GLOBAL_PROFILES] CHECK CONSTRAINT [GLOBALPROFILES_CATALOGS_POSITION_OWNER_FK]
GO
ALTER TABLE [SCH_CENTRA_ID].[GLOBAL_TRANSACTIONAL_PROFILES]  WITH CHECK ADD  CONSTRAINT [GLOBAL_TRANSACTIONAL_PROFILES_GLOBAL_PROFILES_FK] FOREIGN KEY([GLOBAL_PROFILE_ID])
REFERENCES [SCH_CENTRA_ID].[GLOBAL_PROFILES] ([ID])
GO
ALTER TABLE [SCH_CENTRA_ID].[GLOBAL_TRANSACTIONAL_PROFILES] CHECK CONSTRAINT [GLOBAL_TRANSACTIONAL_PROFILES_GLOBAL_PROFILES_FK]
GO
ALTER TABLE [SCH_CENTRA_ID].[GLOBAL_TRANSACTIONAL_PROFILES]  WITH CHECK ADD  CONSTRAINT [GLOBAL_TRANSACTIONAL_PROFILES_TRANSACTIONAL_PROFILES_FK] FOREIGN KEY([TRANSACTIONAL_PROFILE_ID])
REFERENCES [SCH_CENTRA_ID].[TRANSACTIONAL_PROFILES] ([ID])
GO
ALTER TABLE [SCH_CENTRA_ID].[GLOBAL_TRANSACTIONAL_PROFILES] CHECK CONSTRAINT [GLOBAL_TRANSACTIONAL_PROFILES_TRANSACTIONAL_PROFILES_FK]
GO
ALTER TABLE [SCH_CENTRA_ID].[HISTORY_SCOPE_RULES]  WITH CHECK ADD  CONSTRAINT [HISTORY_SCOPE_RULES_GLOBAL_PROFILES_FK] FOREIGN KEY([GLOBAL_PROFILE_ID])
REFERENCES [SCH_CENTRA_ID].[GLOBAL_PROFILES] ([ID])
GO
ALTER TABLE [SCH_CENTRA_ID].[HISTORY_SCOPE_RULES] CHECK CONSTRAINT [HISTORY_SCOPE_RULES_GLOBAL_PROFILES_FK]
GO
ALTER TABLE [SCH_CENTRA_ID].[MATRICES]  WITH CHECK ADD  CONSTRAINT [MATRICES_APPLICATIONS_GROUP_FK] FOREIGN KEY([APPLICATION_GROUP_ID])
REFERENCES [SCH_CENTRA_ID].[APPLICATIONS_GROUP] ([ID])
GO
ALTER TABLE [SCH_CENTRA_ID].[MATRICES] CHECK CONSTRAINT [MATRICES_APPLICATIONS_GROUP_FK]
GO
ALTER TABLE [SCH_CENTRA_ID].[MATRICES_DETAIL]  WITH CHECK ADD  CONSTRAINT [MATRICES_DETAIL_MATRICES_FK] FOREIGN KEY([MATRIX_ID])
REFERENCES [SCH_CENTRA_ID].[MATRICES] ([ID])
GO
ALTER TABLE [SCH_CENTRA_ID].[MATRICES_DETAIL] CHECK CONSTRAINT [MATRICES_DETAIL_MATRICES_FK]
GO
ALTER TABLE [SCH_CENTRA_ID].[OPERATIONS_PROVISIONING]  WITH CHECK ADD  CONSTRAINT [USER_PROFILE_TRANSACTIONAL_HISTORY_GLOBAL_PROFILES_FK] FOREIGN KEY([GLOBAL_PROFILE_ID])
REFERENCES [SCH_CENTRA_ID].[GLOBAL_PROFILES] ([ID])
GO
ALTER TABLE [SCH_CENTRA_ID].[OPERATIONS_PROVISIONING] CHECK CONSTRAINT [USER_PROFILE_TRANSACTIONAL_HISTORY_GLOBAL_PROFILES_FK]
GO
ALTER TABLE [SCH_CENTRA_ID].[OPERATIONS_PROVISIONING]  WITH CHECK ADD  CONSTRAINT [USER_PROFILE_TRANSACTIONAL_HISTORY_TRANSACTIONAL_IDENTITY_FK] FOREIGN KEY([TRANSACTIONAL_IDENTITY_ID])
REFERENCES [SCH_CENTRA_ID].[TRANSACTIONAL_IDENTITY] ([ID])
GO
ALTER TABLE [SCH_CENTRA_ID].[OPERATIONS_PROVISIONING] CHECK CONSTRAINT [USER_PROFILE_TRANSACTIONAL_HISTORY_TRANSACTIONAL_IDENTITY_FK]
GO
ALTER TABLE [SCH_CENTRA_ID].[OPERATIONS_PROVISIONING]  WITH CHECK ADD  CONSTRAINT [USER_PROFILE_TRANSACTIONAL_HISTORY_USERDATA_FK] FOREIGN KEY([USER_DATA_ID])
REFERENCES [SCH_CENTRA_ID].[USERDATA] ([ID])
GO
ALTER TABLE [SCH_CENTRA_ID].[OPERATIONS_PROVISIONING] CHECK CONSTRAINT [USER_PROFILE_TRANSACTIONAL_HISTORY_USERDATA_FK]
GO
ALTER TABLE [SCH_CENTRA_ID].[PROCESS_DISTRIBUTION_LIST]  WITH CHECK ADD  CONSTRAINT [PROCESSDISTRIBUTIONLIST_DISTRIBUTIONLIST_FK] FOREIGN KEY([DISTRIBUTION_LIST_ID])
REFERENCES [SCH_CENTRA_ID].[DISTRIBUTION_LIST] ([ID])
GO
ALTER TABLE [SCH_CENTRA_ID].[PROCESS_DISTRIBUTION_LIST] CHECK CONSTRAINT [PROCESSDISTRIBUTIONLIST_DISTRIBUTIONLIST_FK]
GO
ALTER TABLE [SCH_CENTRA_ID].[PROCESS_DISTRIBUTION_LIST]  WITH CHECK ADD  CONSTRAINT [PROCESSDISTRIBUTIONLIST_PROCESS_FK] FOREIGN KEY([PROCESS_ID])
REFERENCES [SCH_CENTRA_ID].[PROCESS] ([ID])
GO
ALTER TABLE [SCH_CENTRA_ID].[PROCESS_DISTRIBUTION_LIST] CHECK CONSTRAINT [PROCESSDISTRIBUTIONLIST_PROCESS_FK]
GO
ALTER TABLE [SCH_CENTRA_ID].[TAKS_PROVISIONING]  WITH CHECK ADD  CONSTRAINT [USER_ACTION_PROFILE_TRANSACTIONAL_APPLICATIONS_FK] FOREIGN KEY([APPLICATION_ID])
REFERENCES [SCH_CENTRA_ID].[APPLICATIONS] ([ID])
GO
ALTER TABLE [SCH_CENTRA_ID].[TAKS_PROVISIONING] CHECK CONSTRAINT [USER_ACTION_PROFILE_TRANSACTIONAL_APPLICATIONS_FK]
GO
ALTER TABLE [SCH_CENTRA_ID].[TAKS_PROVISIONING]  WITH CHECK ADD  CONSTRAINT [USER_ACTION_PROFILE_TRANSACTIONAL_TRANSACTIONAL_PROFILES_FK] FOREIGN KEY([TRANSACTIONAL_PROFILE_ID])
REFERENCES [SCH_CENTRA_ID].[TRANSACTIONAL_PROFILES] ([ID])
GO
ALTER TABLE [SCH_CENTRA_ID].[TAKS_PROVISIONING] CHECK CONSTRAINT [USER_ACTION_PROFILE_TRANSACTIONAL_TRANSACTIONAL_PROFILES_FK]
GO
ALTER TABLE [SCH_CENTRA_ID].[TAKS_PROVISIONING]  WITH CHECK ADD  CONSTRAINT [USER_ACTION_PROFILE_TRANSACTIONAL_USER_PROFILE_TRANSACTIONAL_HISTORY_FK] FOREIGN KEY([OPERATION_PROVISIONING_ID])
REFERENCES [SCH_CENTRA_ID].[OPERATIONS_PROVISIONING] ([ID])
GO
ALTER TABLE [SCH_CENTRA_ID].[TAKS_PROVISIONING] CHECK CONSTRAINT [USER_ACTION_PROFILE_TRANSACTIONAL_USER_PROFILE_TRANSACTIONAL_HISTORY_FK]
GO
ALTER TABLE [SCH_CENTRA_ID].[TAKS_PROVISIONING_HISTORY]  WITH CHECK ADD  CONSTRAINT [TAKS_PROVISIONING_HISTORY_TAKS_PROVISIONING_FK] FOREIGN KEY([TASK_PROVISIONING_ID])
REFERENCES [SCH_CENTRA_ID].[TAKS_PROVISIONING] ([ID])
GO
ALTER TABLE [SCH_CENTRA_ID].[TAKS_PROVISIONING_HISTORY] CHECK CONSTRAINT [TAKS_PROVISIONING_HISTORY_TAKS_PROVISIONING_FK]
GO
ALTER TABLE [SCH_CENTRA_ID].[TEMPLATE_PROFILES]  WITH CHECK ADD  CONSTRAINT [TEMPLATE_PROFILES_FIELDS_FK] FOREIGN KEY([FIELD_ID])
REFERENCES [SCH_CENTRA_ID].[FIELDS] ([ID])
GO
ALTER TABLE [SCH_CENTRA_ID].[TEMPLATE_PROFILES] CHECK CONSTRAINT [TEMPLATE_PROFILES_FIELDS_FK]
GO
ALTER TABLE [SCH_CENTRA_ID].[TEMPLATE_PROFILES]  WITH CHECK ADD  CONSTRAINT [TEMPLATE_PROFILES_TRANSACTIONAL_PROFILES_FK] FOREIGN KEY([TRANSACTIONAL_PROFILE_ID])
REFERENCES [SCH_CENTRA_ID].[TRANSACTIONAL_PROFILES] ([ID])
GO
ALTER TABLE [SCH_CENTRA_ID].[TEMPLATE_PROFILES] CHECK CONSTRAINT [TEMPLATE_PROFILES_TRANSACTIONAL_PROFILES_FK]
GO
ALTER TABLE [SCH_CENTRA_ID].[TEMPLATE_PROFILES_MATRICES]  WITH CHECK ADD  CONSTRAINT [TEMPLATE_PROFILES_MATRICES_MATRICES_FK] FOREIGN KEY([MATRIX_ID])
REFERENCES [SCH_CENTRA_ID].[MATRICES] ([ID])
GO
ALTER TABLE [SCH_CENTRA_ID].[TEMPLATE_PROFILES_MATRICES] CHECK CONSTRAINT [TEMPLATE_PROFILES_MATRICES_MATRICES_FK]
GO
ALTER TABLE [SCH_CENTRA_ID].[TEMPLATE_PROFILES_MATRICES]  WITH CHECK ADD  CONSTRAINT [TEMPLATE_PROFILES_MATRICES_TRANSACTIONAL_PROFILES_FK] FOREIGN KEY([TRANSACTIONAL_PROFILE_ID])
REFERENCES [SCH_CENTRA_ID].[TRANSACTIONAL_PROFILES] ([ID])
GO
ALTER TABLE [SCH_CENTRA_ID].[TEMPLATE_PROFILES_MATRICES] CHECK CONSTRAINT [TEMPLATE_PROFILES_MATRICES_TRANSACTIONAL_PROFILES_FK]
GO
ALTER TABLE [SCH_CENTRA_ID].[TEMPLATE_PROFILES_MATRICES_DETAIL]  WITH CHECK ADD  CONSTRAINT [TEMPLATE_PROFILES_MATRICES_DETAIL_MATRICES_DETAIL_FK] FOREIGN KEY([MATRIX_DETAIL_ID])
REFERENCES [SCH_CENTRA_ID].[MATRICES_DETAIL] ([ID])
GO
ALTER TABLE [SCH_CENTRA_ID].[TEMPLATE_PROFILES_MATRICES_DETAIL] CHECK CONSTRAINT [TEMPLATE_PROFILES_MATRICES_DETAIL_MATRICES_DETAIL_FK]
GO
ALTER TABLE [SCH_CENTRA_ID].[TEMPLATE_PROFILES_MATRICES_DETAIL]  WITH CHECK ADD  CONSTRAINT [TEMPLATE_PROFILES_MATRICES_DETAIL_TEMPLATE_PROFILES_MATRICES_GROUP_FK] FOREIGN KEY([TEMPLATE_PROFILE_MATRIX_GROUP_ID])
REFERENCES [SCH_CENTRA_ID].[TEMPLATE_PROFILES_MATRICES_GROUP] ([ID])
GO
ALTER TABLE [SCH_CENTRA_ID].[TEMPLATE_PROFILES_MATRICES_DETAIL] CHECK CONSTRAINT [TEMPLATE_PROFILES_MATRICES_DETAIL_TEMPLATE_PROFILES_MATRICES_GROUP_FK]
GO
ALTER TABLE [SCH_CENTRA_ID].[TEMPLATE_PROFILES_MATRICES_GROUP]  WITH CHECK ADD  CONSTRAINT [TEMPLATE_PROFILES_MATRICES_GROUP_TEMPLATE_PROFILES_MATRICES_FK] FOREIGN KEY([TEMPLATE_PROFILE_MATRIX_ID])
REFERENCES [SCH_CENTRA_ID].[TEMPLATE_PROFILES_MATRICES] ([ID])
GO
ALTER TABLE [SCH_CENTRA_ID].[TEMPLATE_PROFILES_MATRICES_GROUP] CHECK CONSTRAINT [TEMPLATE_PROFILES_MATRICES_GROUP_TEMPLATE_PROFILES_MATRICES_FK]
GO
ALTER TABLE [SCH_CENTRA_ID].[TRANSACTIONAL_IDENTITY]  WITH CHECK ADD  CONSTRAINT [TRANSACTIONALIDENTITY_GLOBALPROFILE_FK] FOREIGN KEY([GLOBAL_PROFILE_ID])
REFERENCES [SCH_CENTRA_ID].[GLOBAL_PROFILES] ([ID])
GO
ALTER TABLE [SCH_CENTRA_ID].[TRANSACTIONAL_IDENTITY] CHECK CONSTRAINT [TRANSACTIONALIDENTITY_GLOBALPROFILE_FK]
GO
ALTER TABLE [SCH_CENTRA_ID].[TRANSACTIONAL_IDENTITY]  WITH CHECK ADD  CONSTRAINT [TRANSACTIONALIDENTITY_USERDATA_FK] FOREIGN KEY([USER_DATA_ID])
REFERENCES [SCH_CENTRA_ID].[USERDATA] ([ID])
GO
ALTER TABLE [SCH_CENTRA_ID].[TRANSACTIONAL_IDENTITY] CHECK CONSTRAINT [TRANSACTIONALIDENTITY_USERDATA_FK]
GO
ALTER TABLE [SCH_CENTRA_ID].[TRANSACTIONAL_PROFILES]  WITH CHECK ADD  CONSTRAINT [transactional_profiles_applications_FK] FOREIGN KEY([application_id])
REFERENCES [SCH_CENTRA_ID].[APPLICATIONS] ([ID])
GO
ALTER TABLE [SCH_CENTRA_ID].[TRANSACTIONAL_PROFILES] CHECK CONSTRAINT [transactional_profiles_applications_FK]
GO
ALTER TABLE [SCH_CENTRA_ID].[TRANSACTIONAL_PROFILES]  WITH CHECK ADD  CONSTRAINT [TRANSACTIONALPROFILES_CATALOGS_FK] FOREIGN KEY([CATALOG_RISK_LEVEL_ID])
REFERENCES [SCH_CENTRA_ID].[CATALOGS] ([ID])
GO
ALTER TABLE [SCH_CENTRA_ID].[TRANSACTIONAL_PROFILES] CHECK CONSTRAINT [TRANSACTIONALPROFILES_CATALOGS_FK]
GO
ALTER TABLE [SCH_CENTRA_ID].[TYPE_USERS]  WITH CHECK ADD  CONSTRAINT [TYPESUSERS_TYPESUSERS_FK] FOREIGN KEY([parent_id])
REFERENCES [SCH_CENTRA_ID].[TYPE_USERS] ([ID])
GO
ALTER TABLE [SCH_CENTRA_ID].[TYPE_USERS] CHECK CONSTRAINT [TYPESUSERS_TYPESUSERS_FK]
GO
ALTER TABLE [SCH_CENTRA_ID].[USERDATA]  WITH CHECK ADD  CONSTRAINT [USERDATA_CATALOGS_AREA_FK] FOREIGN KEY([CATALOG_AREA_ID])
REFERENCES [SCH_CENTRA_ID].[CATALOGS] ([ID])
GO
ALTER TABLE [SCH_CENTRA_ID].[USERDATA] CHECK CONSTRAINT [USERDATA_CATALOGS_AREA_FK]
GO
ALTER TABLE [SCH_CENTRA_ID].[USERDATA]  WITH CHECK ADD  CONSTRAINT [USERDATA_CATALOGS_DEPARTMENT_FK] FOREIGN KEY([CATALOG_DEPARTMENT_ID])
REFERENCES [SCH_CENTRA_ID].[CATALOGS] ([ID])
GO
ALTER TABLE [SCH_CENTRA_ID].[USERDATA] CHECK CONSTRAINT [USERDATA_CATALOGS_DEPARTMENT_FK]
GO
ALTER TABLE [SCH_CENTRA_ID].[USERDATA]  WITH CHECK ADD  CONSTRAINT [USERDATA_CATALOGS_DIVISION_FK] FOREIGN KEY([CATALOG_DIVISION_ID])
REFERENCES [SCH_CENTRA_ID].[CATALOGS] ([ID])
GO
ALTER TABLE [SCH_CENTRA_ID].[USERDATA] CHECK CONSTRAINT [USERDATA_CATALOGS_DIVISION_FK]
GO
ALTER TABLE [SCH_CENTRA_ID].[USERDATA]  WITH CHECK ADD  CONSTRAINT [USERDATA_CATALOGS_IDENTIFICATION_TYPE_FK] FOREIGN KEY([CATALOG_IDENTIFICATION_TYPE_ID])
REFERENCES [SCH_CENTRA_ID].[CATALOGS] ([ID])
GO
ALTER TABLE [SCH_CENTRA_ID].[USERDATA] CHECK CONSTRAINT [USERDATA_CATALOGS_IDENTIFICATION_TYPE_FK]
GO
ALTER TABLE [SCH_CENTRA_ID].[USERDATA]  WITH CHECK ADD  CONSTRAINT [USERDATA_CATALOGS_POSITION_FK] FOREIGN KEY([CATALOG_POSITION_ID])
REFERENCES [SCH_CENTRA_ID].[CATALOGS] ([ID])
GO
ALTER TABLE [SCH_CENTRA_ID].[USERDATA] CHECK CONSTRAINT [USERDATA_CATALOGS_POSITION_FK]
GO
ALTER TABLE [SCH_CENTRA_ID].[USERDATA]  WITH CHECK ADD  CONSTRAINT [USERDATA_COMPANIES_FK] FOREIGN KEY([COMPANY_ID])
REFERENCES [SCH_CENTRA_ID].[COMPANIES] ([ID])
GO
ALTER TABLE [SCH_CENTRA_ID].[USERDATA] CHECK CONSTRAINT [USERDATA_COMPANIES_FK]
GO
ALTER TABLE [SCH_CENTRA_ID].[USERDATA]  WITH CHECK ADD  CONSTRAINT [USERDATA_COSTS_CENTERS_FK] FOREIGN KEY([COST_CENTER_ID])
REFERENCES [SCH_CENTRA_ID].[COSTS_CENTERS] ([ID])
GO
ALTER TABLE [SCH_CENTRA_ID].[USERDATA] CHECK CONSTRAINT [USERDATA_COSTS_CENTERS_FK]
GO
ALTER TABLE [SCH_CENTRA_ID].[USERDATA]  WITH CHECK ADD  CONSTRAINT [USERDATA_GLOBAL_PROFILES_FK] FOREIGN KEY([GLOBAL_PROFILE_ID])
REFERENCES [SCH_CENTRA_ID].[GLOBAL_PROFILES] ([ID])
GO
ALTER TABLE [SCH_CENTRA_ID].[USERDATA] CHECK CONSTRAINT [USERDATA_GLOBAL_PROFILES_FK]
GO
ALTER TABLE [SCH_CENTRA_ID].[USERDATA]  WITH CHECK ADD  CONSTRAINT [USERDATA_SUBTYPE_USER_ID_FK] FOREIGN KEY([SUBTYPE_USER_ID])
REFERENCES [SCH_CENTRA_ID].[TYPE_USERS] ([ID])
GO
ALTER TABLE [SCH_CENTRA_ID].[USERDATA] CHECK CONSTRAINT [USERDATA_SUBTYPE_USER_ID_FK]
GO
ALTER TABLE [SCH_CENTRA_ID].[USERDATA]  WITH CHECK ADD  CONSTRAINT [USERDATA_TYPES_USERS_FK] FOREIGN KEY([TYPE_USER_ID])
REFERENCES [SCH_CENTRA_ID].[TYPE_USERS] ([ID])
GO
ALTER TABLE [SCH_CENTRA_ID].[USERDATA] CHECK CONSTRAINT [USERDATA_TYPES_USERS_FK]
GO
ALTER TABLE [SCH_CENTRA_ID].[USERDATA]  WITH CHECK ADD  CONSTRAINT [USERDATA_USERDATA_BANK_COUNTERPART_FK] FOREIGN KEY([USERDATA_BANK_COUNTERPART_ID])
REFERENCES [SCH_CENTRA_ID].[USERDATA] ([ID])
GO
ALTER TABLE [SCH_CENTRA_ID].[USERDATA] CHECK CONSTRAINT [USERDATA_USERDATA_BANK_COUNTERPART_FK]
GO
ALTER TABLE [SCH_CENTRA_ID].[USERDATA]  WITH CHECK ADD  CONSTRAINT [USERDATA_USERDATA_RESPONSIBLE_USER_FK] FOREIGN KEY([USERDATA_RESPONSIBLE_USER_ID])
REFERENCES [SCH_CENTRA_ID].[USERDATA] ([ID])
GO
ALTER TABLE [SCH_CENTRA_ID].[USERDATA] CHECK CONSTRAINT [USERDATA_USERDATA_RESPONSIBLE_USER_FK]
GO
ALTER TABLE [SCH_CENTRA_ID].[USERDATA]  WITH CHECK ADD  CONSTRAINT [USERDATA_USERDATA_SUPERVISOR_FK] FOREIGN KEY([USERDATA_SUPERVISOR_ID])
REFERENCES [SCH_CENTRA_ID].[USERDATA] ([ID])
GO
ALTER TABLE [SCH_CENTRA_ID].[USERDATA] CHECK CONSTRAINT [USERDATA_USERDATA_SUPERVISOR_FK]
GO
ALTER TABLE [SCH_CENTRA_ID].[APPLICATIONS_GROUP]  WITH CHECK ADD  CONSTRAINT [APPLICATIONS_GROUP_ENDPOINT_TYPE_UK] CHECK  (([ENDPOINT_TYPE]='TICKET' OR [ENDPOINT_TYPE]='DIRECT' OR [ENDPOINT_TYPE]='API'))
GO
ALTER TABLE [SCH_CENTRA_ID].[APPLICATIONS_GROUP] CHECK CONSTRAINT [APPLICATIONS_GROUP_ENDPOINT_TYPE_UK]
GO
ALTER TABLE [SCH_CENTRA_ID].[CATALOGS_TYPES]  WITH CHECK ADD  CONSTRAINT [TYPES_CATALOGS_SORT_TYPE_CK] CHECK  (([SORT_TYPE]='O' OR [SORT_TYPE]='A'))
GO
ALTER TABLE [SCH_CENTRA_ID].[CATALOGS_TYPES] CHECK CONSTRAINT [TYPES_CATALOGS_SORT_TYPE_CK]
GO
ALTER TABLE [SCH_CENTRA_ID].[GLOBAL_PARAMETERS]  WITH CHECK ADD  CONSTRAINT [GLOBAL_PARAMETERS_TYPE_CK] CHECK  (([TYPE]='B' OR [TYPE]='D' OR [TYPE]='N' OR [TYPE]='S'))
GO
ALTER TABLE [SCH_CENTRA_ID].[GLOBAL_PARAMETERS] CHECK CONSTRAINT [GLOBAL_PARAMETERS_TYPE_CK]
GO
ALTER TABLE [SCH_CENTRA_ID].[MASSIVE_PROCESS]  WITH CHECK ADD  CONSTRAINT [MASIVE_PROCESS_TYPEEVENT_CK] CHECK  (([TYPE_EVENT]='C' OR [TYPE_EVENT]='P'))
GO
ALTER TABLE [SCH_CENTRA_ID].[MASSIVE_PROCESS] CHECK CONSTRAINT [MASIVE_PROCESS_TYPEEVENT_CK]
GO
ALTER TABLE [SCH_CENTRA_ID].[MASSIVE_PROCESS]  WITH CHECK ADD  CONSTRAINT [MASSIVE_PROCESS_RESULT_UK] CHECK  (([RESULT]='P' OR [RESULT]='C' OR [RESULT]='I'))
GO
ALTER TABLE [SCH_CENTRA_ID].[MASSIVE_PROCESS] CHECK CONSTRAINT [MASSIVE_PROCESS_RESULT_UK]
GO
ALTER TABLE [SCH_CENTRA_ID].[MASSIVE_PROCESS]  WITH CHECK ADD  CONSTRAINT [MASSIVE_PROCESS_STATE_UK] CHECK  (([STATE]='Y' OR [STATE]='N' OR [STATE]='S'))
GO
ALTER TABLE [SCH_CENTRA_ID].[MASSIVE_PROCESS] CHECK CONSTRAINT [MASSIVE_PROCESS_STATE_UK]
GO
ALTER TABLE [SCH_CENTRA_ID].[MASSIVE_PROCESS]  WITH CHECK ADD  CONSTRAINT [MASSIVE_PROCESS_TYPEACTION_UK] CHECK  (([TYPE_ACTION]='D' OR [TYPE_ACTION]='U' OR [TYPE_ACTION]='C'))
GO
ALTER TABLE [SCH_CENTRA_ID].[MASSIVE_PROCESS] CHECK CONSTRAINT [MASSIVE_PROCESS_TYPEACTION_UK]
GO
ALTER TABLE [SCH_CENTRA_ID].[TYPE_USERS]  WITH CHECK ADD  CONSTRAINT [TYPES_USERS_TYPE_CK] CHECK  (([TYPE]='S' OR [TYPE]='T'))
GO
ALTER TABLE [SCH_CENTRA_ID].[TYPE_USERS] CHECK CONSTRAINT [TYPES_USERS_TYPE_CK]

