USE [CENTRA_ID]
GO

CREATE TABLE SCH_CENTRA_ID.TEMPLATE_PROFILES_AD
    (
        ID BIGINT NOT NULL IDENTITY,
        TRANSACTIONAL_PROFILE_ID BIGINT NOT NULL,
	ACTIVATE_MAIL INT ,
	MAILBOX_TYPE NVARCHAR(20),
	SHOULD_CHANGE_PASSWORD_FIRST_TIME INT ,
	SHOULD_NOT_CHANGE_PASSWORD INT ,
	PASSWORD_NOT_EXPIRE INT ,
	ACCOUNT_CONTAINER TEXT,
	GROUP_AD TEXT,
	EXCHANGE_ADVANCED_OWA INT,
	EXCHANGE_ADVANCED_ACTIVE_SYNC INT,
	SIP INT,
	TERMINAL_SERVICES_PROFILE NVARCHAR(20),
	CONNECT_FOLLOWING_DRIVE INT,
	TERMINAL_SERVICES_HOME_DIRECTORY NVARCHAR(100),
	ALLOW_LOGON_TO_TERMINAL_SERVER INT,
	FIELD_ACTIVATE_MAIL_ID BIGINT ,
	FIELD_MAILBOX_TYPE_ID BIGINT ,
	FIELD_SHOULD_CHANGE_PASSWORD_FIRST_TIME_ID BIGINT ,
	FIELD_SHOULD_NOT_CHANGE_PASSWORD_ID BIGINT ,
	FIELD_PASSWORD_NOT_EXPIRE_ID BIGINT ,
	FIELD_ACCOUNT_CONTAINER_ID BIGINT ,
	FIELD_GROUP_AD_ID BIGINT ,
	FIELD_EXCHANGE_ADVANCED_OWA_ID BIGINT ,
	FIELD_EXCHANGE_ADVANCED_ACTIVE_SYNC_ID BIGINT ,
	FIELD_SIP_ID BIGINT ,
	FIELD_TERMINAL_SERVICES_PROFILE_ID BIGINT ,
	FIELD_CONNECT_FOLLOWING_DRIVE_ID BIGINT ,
	FIELD_TERMINAL_SERVICES_HOME_DIRECTORY_ID BIGINT ,
	FIELD_ALLOW_LOGON_TO_TERMINAL_SERVER_ID BIGINT ,
        VALID INT NOT NULL,
        CONSTRAINT TEMPLATE_PROFILE_AD_PK PRIMARY KEY (ID),
        CONSTRAINT TEMPLATE_PROFILE_AD_TRANSACTIONAL_PROFILE_FK FOREIGN KEY (TRANSACTIONAL_PROFILE_ID) REFERENCES SCH_CENTRA_ID.GLOBAL_PROFILES (ID),
        CONSTRAINT TEMPLATE_PROFILE_AD_FIELD_ACTIVATE_MAIL_FK FOREIGN KEY (FIELD_ACTIVATE_MAIL_ID) REFERENCES SCH_CENTRA_ID.FIELDS (ID),
        CONSTRAINT TEMPLATE_PROFILE_AD_FIELD_SHOULD_CHANGE_PASSWORD_FIRST_TIME_FK FOREIGN KEY (FIELD_SHOULD_CHANGE_PASSWORD_FIRST_TIME_ID) REFERENCES SCH_CENTRA_ID.FIELDS (ID),
        CONSTRAINT TEMPLATE_PROFILE_AD_FIELD_SHOULD_NOT_CHANGE_PASSWORD_FK FOREIGN KEY (FIELD_SHOULD_NOT_CHANGE_PASSWORD_ID) REFERENCES SCH_CENTRA_ID.FIELDS (ID),
        CONSTRAINT TEMPLATE_PROFILE_AD_FIELD_PASSWORD_NOT_EXPIRE_FK FOREIGN KEY (FIELD_PASSWORD_NOT_EXPIRE_ID) REFERENCES SCH_CENTRA_ID.FIELDS (ID),
        CONSTRAINT TEMPLATE_PROFILE_AD_FIELD_ACCOUNT_CONTAINER_FK FOREIGN KEY (FIELD_ACCOUNT_CONTAINER_ID) REFERENCES SCH_CENTRA_ID.FIELDS (ID),
        CONSTRAINT TEMPLATE_PROFILE_AD_FIELD_GROUP_AD_FK FOREIGN KEY (FIELD_GROUP_AD_ID) REFERENCES SCH_CENTRA_ID.FIELDS (ID),
        CONSTRAINT TEMPLATE_PROFILE_AD_FIELD_EXCHANGE_ADVANCED_OWA_FK FOREIGN KEY (FIELD_EXCHANGE_ADVANCED_OWA_ID) REFERENCES SCH_CENTRA_ID.FIELDS (ID),
        CONSTRAINT TEMPLATE_PROFILE_AD_FIELD_EXCHANGE_ADVANCED_ACTIVE_SYNC_FK FOREIGN KEY (FIELD_EXCHANGE_ADVANCED_ACTIVE_SYNC_ID) REFERENCES SCH_CENTRA_ID.FIELDS (ID),
        CONSTRAINT TEMPLATE_PROFILE_AD_FIELD_SIP_FK FOREIGN KEY (FIELD_SIP_ID) REFERENCES SCH_CENTRA_ID.FIELDS (ID),
        CONSTRAINT TEMPLATE_PROFILE_AD_FIELD_TERMINAL_SERVICES_PROFILE_FK FOREIGN KEY (FIELD_TERMINAL_SERVICES_PROFILE_ID) REFERENCES SCH_CENTRA_ID.FIELDS (ID),
        CONSTRAINT TEMPLATE_PROFILE_AD_FIELD_CONNECT_FOLLOWING_DRIVE_FK FOREIGN KEY (FIELD_CONNECT_FOLLOWING_DRIVE_ID) REFERENCES SCH_CENTRA_ID.FIELDS (ID),
        CONSTRAINT TEMPLATE_PROFILE_AD_FIELD_TERMINAL_SERVICES_HOME_DIRECTORY_FK FOREIGN KEY (FIELD_TERMINAL_SERVICES_HOME_DIRECTORY_ID) REFERENCES SCH_CENTRA_ID.FIELDS (ID),
        CONSTRAINT TEMPLATE_PROFILE_AD_FIELD_ALLOW_LOGON_TO_TERMINAL_SERVER_FK FOREIGN KEY (FIELD_ALLOW_LOGON_TO_TERMINAL_SERVER_ID) REFERENCES SCH_CENTRA_ID.FIELDS (ID)
    )
GO

ALTER TABLE "SCH_CENTRA_ID"."TEMPLATE_PROFILES_AD" DROP CONSTRAINT "TEMPLATE_PROFILE_AD_TRANSACTIONAL_PROFILE_FK"
GO
ALTER TABLE "SCH_CENTRA_ID"."TEMPLATE_PROFILES_AD" ADD CONSTRAINT
    "TEMPLATE_PROFILE_AD_TRANSACTIONAL_PROFILE_FK "FOREIGN KEY ("TRANSACTIONAL_PROFILE_ID")
    REFERENCES "CENTRA_ID"."SCH_CENTRA_ID"."TRANSACTIONAL_PROFILES"
GO

ALTER TABLE "SCH_CENTRA_ID"."DEFAULT_PROFILES" ADD NAME_COMPANY nvarchar(200)
GO
ALTER TABLE "SCH_CENTRA_ID"."DEFAULT_PROFILES" ADD NAME_DIVISION nvarchar(200)
GO
ALTER TABLE "SCH_CENTRA_ID"."DEFAULT_PROFILES" ADD NAME_AREA nvarchar(200)
GO
ALTER TABLE "SCH_CENTRA_ID"."DEFAULT_PROFILES" ADD NAME_DEPARTMENT nvarchar(200)
GO
ALTER TABLE "SCH_CENTRA_ID"."DEFAULT_PROFILES" ADD NAME_POSITION nvarchar(200)
GO



DELETE FROM SCH_CENTRA_ID.CATALOGS WHERE CATALOGS.CATALOG_TYPE_ID IN (SELECT ID FROM SCH_CENTRA_ID.CATALOGS_TYPES WHERE CODE='TIPOBUZON')

INSERT INTO SCH_CENTRA_ID.CATALOGS_TYPES (CODE, NAME, SORT_TYPE, EDITABLE, VALID, description) VALUES ('TIPOBUZON', 'TIPO DE BUZON', 'A', 1, 1, null)
GO

INSERT INTO SCH_CENTRA_ID.CATALOGS (CODE, NAME, PREDETERMINED, ORDINAL, VALUE_TEXT, VALUE_NUMBER, VALUE_DATE, VALUE_BOOLEAN, catalog_type_id, VALID) 
VALUES ('Tier1', 'TIER 1', 0, null, null, null, null, null, (SELECT ID FROM SCH_CENTRA_ID.CATALOGS_TYPES WHERE CODE='TIPOBUZON'), 1)
GO
INSERT INTO SCH_CENTRA_ID.CATALOGS (CODE, NAME, PREDETERMINED, ORDINAL, VALUE_TEXT, VALUE_NUMBER, VALUE_DATE, VALUE_BOOLEAN, catalog_type_id, VALID) 
VALUES ('Tier2', 'TIER 2', 0, null, null, null, null, null, (SELECT ID FROM SCH_CENTRA_ID.CATALOGS_TYPES WHERE CODE='TIPOBUZON'), 1)
GO
INSERT INTO SCH_CENTRA_ID.CATALOGS (CODE, NAME, PREDETERMINED, ORDINAL, VALUE_TEXT, VALUE_NUMBER, VALUE_DATE, VALUE_BOOLEAN, catalog_type_id, VALID) 
VALUES ('Tier3', 'TIER 3', 0, null, null, null, null, null, (SELECT ID FROM SCH_CENTRA_ID.CATALOGS_TYPES WHERE CODE='TIPOBUZON'), 1)
GO
INSERT INTO SCH_CENTRA_ID.CATALOGS (CODE, NAME, PREDETERMINED, ORDINAL, VALUE_TEXT, VALUE_NUMBER, VALUE_DATE, VALUE_BOOLEAN, catalog_type_id, VALID) 
VALUES ('Tier4', 'TIER 4', 0, null, null, null, null, null, (SELECT ID FROM SCH_CENTRA_ID.CATALOGS_TYPES WHERE CODE='TIPOBUZON'), 1)
GO

delete from SCH_CENTRA_ID.TEMPLATE_PROFILES where TEMPLATE_PROFILES.FIELD_ID in (
select id from SCH_CENTRA_ID.FIELDS where FIELDS.APPLICATION_GROUP_ID 
 in (select ID from SCH_CENTRA_ID.APPLICATIONS_GROUP where code='AD'))
GO

delete from SCH_CENTRA_ID.FIELDS where FIELDS.APPLICATION_GROUP_ID 
 in (select ID from SCH_CENTRA_ID.APPLICATIONS_GROUP where code='AD')
GO


INSERT INTO SCH_CENTRA_ID.FIELDS (CODE, NAME, PREDETERMINED, LENGTH, REQUIRED, TYPE, APPLICATION_GROUP_ID, VALID) VALUES ('activateMail', 'ACTIVAR MAIL', null, 1, 1, 'STRING', (select ID from SCH_CENTRA_ID.APPLICATIONS_GROUP where code='AD'), 1)
GO
INSERT INTO SCH_CENTRA_ID.FIELDS (CODE, NAME, PREDETERMINED, LENGTH, REQUIRED, TYPE, APPLICATION_GROUP_ID, VALID) VALUES ('mailboxType', 'MAILBOX TYPE', null, 100, 1, 'STRING', (select ID from SCH_CENTRA_ID.APPLICATIONS_GROUP where code='AD'), 1)
GO
INSERT INTO SCH_CENTRA_ID.FIELDS (CODE, NAME, PREDETERMINED, LENGTH, REQUIRED, TYPE, APPLICATION_GROUP_ID, VALID) VALUES ('changePasswordNextLogon', 'USER MUST CHANGE PASSWORD AT NEXT LOGON', null, 1, 1, 'STRING', (select ID from SCH_CENTRA_ID.APPLICATIONS_GROUP where code='AD'), 1)
GO
INSERT INTO SCH_CENTRA_ID.FIELDS (CODE, NAME, PREDETERMINED, LENGTH, REQUIRED, TYPE, APPLICATION_GROUP_ID, VALID) VALUES ('userCannotChangePassword', 'USER CANNOT CHANGE PASSWORD', null, 1, 1, 'STRING', (select ID from SCH_CENTRA_ID.APPLICATIONS_GROUP where code='AD'), 1)
GO
INSERT INTO SCH_CENTRA_ID.FIELDS (CODE, NAME, PREDETERMINED, LENGTH, REQUIRED, TYPE, APPLICATION_GROUP_ID, VALID) VALUES ('passwordNeverExpires', 'PASSWORD NEVER EXPIRES', null, 1, 1, 'STRING', (select ID from SCH_CENTRA_ID.APPLICATIONS_GROUP where code='AD'), 1)
GO
INSERT INTO SCH_CENTRA_ID.FIELDS (CODE, NAME, PREDETERMINED, LENGTH, REQUIRED, TYPE, APPLICATION_GROUP_ID, VALID) VALUES ('accountContainer', 'ACCOUNT CONTAINER', null, 500, 1, 'STRING', (select ID from SCH_CENTRA_ID.APPLICATIONS_GROUP where code='AD'), 1)
GO
INSERT INTO SCH_CENTRA_ID.FIELDS (CODE, NAME, PREDETERMINED, LENGTH, REQUIRED, TYPE, APPLICATION_GROUP_ID, VALID) VALUES ('groupAd', 'GROUP AD', null, 500, 1, 'STRING', (select ID from SCH_CENTRA_ID.APPLICATIONS_GROUP where code='AD'), 1)
GO
INSERT INTO SCH_CENTRA_ID.FIELDS (CODE, NAME, PREDETERMINED, LENGTH, REQUIRED, TYPE, APPLICATION_GROUP_ID, VALID) VALUES ('exchangeAdvanceOwa', 'EXCHANGE ADVANCED OWA', null, 1, 1, 'STRING', (select ID from SCH_CENTRA_ID.APPLICATIONS_GROUP where code='AD'), 1)
GO
INSERT INTO SCH_CENTRA_ID.FIELDS (CODE, NAME, PREDETERMINED, LENGTH, REQUIRED, TYPE, APPLICATION_GROUP_ID, VALID) VALUES ('exchangeAdvanceActiveSync', 'EXCHANGE ADVANCED ACTIVE SYNC', null, 1, 1, 'STRING', (select ID from SCH_CENTRA_ID.APPLICATIONS_GROUP where code='AD'), 1)
GO
INSERT INTO SCH_CENTRA_ID.FIELDS (CODE, NAME, PREDETERMINED, LENGTH, REQUIRED, TYPE, APPLICATION_GROUP_ID, VALID) VALUES ('sip', 'SIP', null, 1, 1, 'STRING', (select ID from SCH_CENTRA_ID.APPLICATIONS_GROUP where code='AD'), 1)
GO
INSERT INTO SCH_CENTRA_ID.FIELDS (CODE, NAME, PREDETERMINED, LENGTH, REQUIRED, TYPE, APPLICATION_GROUP_ID, VALID) VALUES ('terminalServicesProfile', 'TERMINAL SERVICES PROFILE', null, 100, 1, 'STRING', (select ID from SCH_CENTRA_ID.APPLICATIONS_GROUP where code='AD'), 1)
GO
INSERT INTO SCH_CENTRA_ID.FIELDS (CODE, NAME, PREDETERMINED, LENGTH, REQUIRED, TYPE, APPLICATION_GROUP_ID, VALID) VALUES ('connectFollowingDrive', 'CONNECT THE FOLLOWING DRIVE', null, 100, 1, 'STRING', (select ID from SCH_CENTRA_ID.APPLICATIONS_GROUP where code='AD'), 1)
GO
INSERT INTO SCH_CENTRA_ID.FIELDS (CODE, NAME, PREDETERMINED, LENGTH, REQUIRED, TYPE, APPLICATION_GROUP_ID, VALID) VALUES ('terminalServicesHomeDirectory', 'TERMINAL SERVICES HOME DIRECTORY', null, 100, 1, 'STRING', (select ID from SCH_CENTRA_ID.APPLICATIONS_GROUP where code='AD'), 1)
GO
INSERT INTO SCH_CENTRA_ID.FIELDS (CODE, NAME, PREDETERMINED, LENGTH, REQUIRED, TYPE, APPLICATION_GROUP_ID, VALID) VALUES ('allowLogonTerminalServer', 'ALLOW LOGON TERMINAL SERVER', null, 100, 1, 'STRING', (select ID from SCH_CENTRA_ID.APPLICATIONS_GROUP where code='AD'), 1)
GO

ALTER TABLE "SCH_CENTRA_ID"."APPLICATIONS_GROUP" DROP CONSTRAINT "APPLICATIONS_GROUP_ENDPOINT_TYPE_UK"
GO
UPDATE "SCH_CENTRA_ID"."APPLICATIONS_GROUP" SET "ENDPOINT_TYPE" = 'AD' WHERE "CODE" = 'AD'
GO

















