USE [CENTRA_ID]
GO
UPDATE "sch_centra_id"."APPLICATIONS" SET "PARENT_ID" = (SELECT ID FROM  "sch_centra_id"."APPLICATIONS" WHERE CODE='AD') WHERE "CODE" = 'BANCS' 
GO
UPDATE "sch_centra_id"."APPLICATIONS" SET "PARENT_ID" = (SELECT ID FROM  "sch_centra_id"."APPLICATIONS" WHERE CODE='BANCS') WHERE "CODE" = 'PPRD'
GO
UPDATE "sch_centra_id"."APPLICATIONS" SET "PARENT_ID" = (SELECT ID FROM  "sch_centra_id"."APPLICATIONS" WHERE CODE='BANCS') WHERE "CODE" = 'LOGIFLOW'
GO
UPDATE "sch_centra_id"."APPLICATIONS" SET "PARENT_ID" = (SELECT ID FROM  "sch_centra_id"."APPLICATIONS" WHERE CODE='BANCS') WHERE "CODE" = 'LGD'
GO
UPDATE "sch_centra_id"."APPLICATIONS" SET "PARENT_ID" = (SELECT ID FROM  "sch_centra_id"."APPLICATIONS" WHERE CODE='BANCS') WHERE "CODE" = 'LPT'
GO
UPDATE "sch_centra_id"."APPLICATIONS" SET "PARENT_ID" = (SELECT ID FROM  "sch_centra_id"."APPLICATIONS" WHERE CODE='BANCS') WHERE "CODE" = 'SCR'
GO
UPDATE "sch_centra_id"."APPLICATIONS" SET "PARENT_ID" = (SELECT ID FROM  "sch_centra_id"."APPLICATIONS" WHERE CODE='BANCS') WHERE "CODE" = 'LSG'
GO
UPDATE "sch_centra_id"."APPLICATIONS" SET "PARENT_ID" = (SELECT ID FROM  "sch_centra_id"."APPLICATIONS" WHERE CODE='BANCS') WHERE "CODE" = 'LSX'
GO
UPDATE "sch_centra_id"."APPLICATIONS" SET "PARENT_ID" = (SELECT ID FROM  "sch_centra_id"."APPLICATIONS" WHERE CODE='BANCS') WHERE "CODE" = 'LTR'
GO
UPDATE "sch_centra_id"."APPLICATIONS" SET "PARENT_ID" = (SELECT ID FROM  "sch_centra_id"."APPLICATIONS" WHERE CODE='BANCS') WHERE "CODE" = 'LGP'
GO
UPDATE "sch_centra_id"."APPLICATIONS" SET "PARENT_ID" = (SELECT ID FROM  "sch_centra_id"."APPLICATIONS" WHERE CODE='BANCS') WHERE "CODE" = 'RHDS'
GO

